### ISSUE TITLE
W3C CSS validation

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#10]
I've verified the CSS with W3C validator and found out tons of errors:

http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fsimple.oceanwp.org%2Fwp-content%2Fcache%2Fmin%2F1%2F922dec8c654346b0ae6aa49490dd17f2.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=it

could you please verify that al css are ok?
I've validated one CSS from your demo too just to check is not a problem on my version.

Thanks so much

**Comment by oceanwp** [comment]
Hi, all the CSS code is fine don't worry :)
