### ISSUE TITLE
Problem with the QuickView mobile responsiveness

### ISSUE THREAD

**Issue by zeinnicholas** [oceanwp/oceanwp#100]
Hey Nic,

I'm about to launch a store website and my client noted that the QuickView popup is misbehaving on smaller screens. The image ends up in front of the product title, price, attributes, etc. After doing some digging I couldn't find what was going wrong, but I managed to verify that this is also the same in one of your demos (the Shoe Store).

I've taken the liberty to take a screenshot of the problem. Can you help me find a solution to this?

Thanks in advance!

Best regards

![captura de tela 32](https://user-images.githubusercontent.com/26891676/41691989-f8acb36a-74d3-11e8-8808-7dbf5d809bf3.png)

**Comment by nicolas-owp** [comment]
Hello, I not quite understood the problem, it is normal that the image and summary are not side by side on mobile view, it would look too weird, the image would be too small and the text too.

**Comment by zeinnicholas** [comment]
If you can see in the screenshot attachment, the feature image is covering (on top of) the product title, price, description and anything that will follow until the image is over. The problem is not the layout changing from two columns to one, is that the featured image is not pushing the right column content to the bottom of it, instead it's over it like if it was absolutely positioned via CSS. The problem is that I couldn't find the right selector to change this behavior with CSS. I think that visitors who happen to tap the QuickView button of the products via mobile won't be able to see the product attributes or description if they want to and won't be able to add the product to cart.

**Comment by nicolas-owp** [comment]
Oh okay, I had misunderstood :)
Thanks for letting me know, fixed for the next release, here the code to fix it now:

```
#owp-qv-wrap .owp-qv-slides {
    display: inline-block;
    vertical-align: top;
}
```
