### ISSUE TITLE
Input checkbox flattened with Ninja Forms

### ISSUE THREAD

**Issue by nickmadedesign** [oceanwp/oceanwp#101]
Standard checkbox inputs while using Ninja Forms (NF) renders the checkboxes flat.

The fix appears to be a 'height: auto' is set by NF but oceanwp sets a 'height: 16px', so I can override it in a child theme, which resolves half of the issue.

The strange thing is, oceanwp sets the checkboxes to 'margin: -3px 10px 0 0 !important; */' , so upon disabling this temporarily and letting NF's default margins take place, the checkboxes are at correct height and placement.

This is under Ninja Forms 3.3.7, WP 4.9.6, tested in Chrome 67.0.3396.87.

**Comment by nicolas-owp** [comment]
Hello, can you send me a link so I can see the issue?

**Comment by nickmadedesign** [comment]
@nicolas-owp Of course, please try viewing this: https://saylaunch.com/sample-1/

**Comment by nicolas-owp** [comment]
Hello, add this css code:

```
input[type="checkbox"] {
    min-width: 16px;
    min-height: 16px;
}
form input[type="checkbox"], form input[type="radio"] {
    margin: .5em 0 !important;
}
```

**Comment by nickmadedesign** [comment]
Thank you for the CSS.

The min-* helped restore those inputs. The margin fix seems to be relevant to the font size/type as .5em worked for that public facing link but a different font family on my private site created a cascading effect. 0.25 em seemed to arbitrarily align them better.

Is it possible to remove/nullify all of the unique checkbox/radio adjustments?

I've never had those types of adjustments play nicely and universally, including mixing in pseudo font-awesome icons.

Thanks!

**Comment by nicolas-owp** [comment]
Hi, as it is a default theme styling, it is a little difficult to completely remove the css for the checkboxes, but the code I gave you fix the issue, you have another problem about this?
