### ISSUE TITLE
Fatal error with shortcode when saving 

### ISSUE THREAD

**Issue by plxrisa** [oceanwp/oceanwp#103]
Hi, 

I have a template in ocean's library made with elementor and I have insert the shortcode: [oceanwp_woo_total_cart] .

The problem is that I can't update the template from wp editor and I'm getting a fatal error. I saw the issue #56 but is closed from March and I still have the problem.

The error is this: 
Fatal error: Uncaught Error: Call to a member function get_cart_total() on null in ......wp-content/plugins/ocean-extra/includes/shortcodes/shortcodes.php:448

Ocean Extra version: 1.4.16

Thank you

**Comment by nicolas-owp** [comment]
Hello, this is very weird because I added a function so the shortcode doesn't work in the Elementor editor especially to avoid this issue. You have the latest version of Elementor, right?

**Comment by plxrisa** [comment]
Yes Nic, everything are in latest versions. 

I found that maybe there is a conflict with yoast plugin. When I deactivate yoast, I can update the template with the shortcode from WP editor. But when I activate it, I see again the error.

I duplicated the site but in localhost the problem dissapears and I don't know why. Maybe because of http://.

Here is the full error:
**Fatal error:** Uncaught Error: Call to a member function get_cart_total() on null in 
...../ocean-extra/includes/shortcodes/shortcodes.php:448 
Stack trace: 
**0** ....../wp-includes/shortcodes.php(319): oceanwp_woo_total_cart_shortcode('', '', 'oceanwp_woo_tot...') 
**1** [internal function]: do_shortcode_tag(Array) 
**2** ....../wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(oceanw...', 'do_shortcode_ta...', '[oceanwp_woo_to...') 
**3** ......wp-includes/class-wp-hook.php(286): do_shortcode('[oceanwp_woo_to...') 
**4** .....wp-includes/plugin.php(203): WP_Hook->apply_filters('[oceanwp_woo_to...', Array) 
**5** ....../wp-content/plugins/wordpress-seo/admin/links/class-link-watcher.php(117): apply_filters('the_content', '[oceanwp_woo_to...') 
**6** ...../wp-content/plugins/wordpress-seo/admin/links/class-link-watcher.php(64) in ......**wp-content/plugins/ocean-extra/includes/shortcodes/shortcodes.php** on line **448**

**Comment by nicolas-owp** [comment]
Hello, is it possible for you to create a staging site? Then check if you have the same issue, if yes, can you create a ticket in oceanwp.org (if you are not a premium user, just open a pre-purchase ticekt) with the login details of an admin and FTP account, this way I will be able to see what is wrong.

**Comment by nicolas-owp** [comment]
Problem fixed in the last release of Ocean Extra :)
