### ISSUE TITLE
Feature Request: Woocommerce Login Customisation

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#105]
How about including the ability to toggle in the customiser the ability to show both login and sign/up register boxes at the same time. 

From a UX point of view, the login or register text which is displayed when not logged in on the "My Account" page isn't obvious as to the interaction required (that the bold text are in fact tabs/links)

**Comment by nicolas-owp** [comment]
Hello, noted on my list :)

**Comment by deebz** [comment]
noticed this still isn't working.

Tested with:
- the vanilla shortcode
- passing a custom URL pointing to http://localhost/my-account 
- passing a custom URL pointing to http://localhost/my-account  and setting the redirect parameter

All tests above result in 404

I tweaked lines 207 & 209 in shortcodes.php as (code below) removing the redirection parameter. 

My tests after removing the code found the following:
- Using the plain shortcode (no paramaters set) the woocommerce logout url is called correctly but when logged out the login url directs to the default wordpress login
- Using the shortcode with a custom URL pointing to http://localhost/my-account  - logout and login links both work desirably

`if ( class_exists( 'WooCommerce' ) ) {
			$logout_url = wc_logout_url();
		} else {
			$logout_url = wp_logout_url();
		}`

**Comment by nicolas-owp** [comment]
Hello, what do you want to do?
