### ISSUE TITLE
Woocommerce Product Achive Display

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#107]
Noticed a possible glitch when configuring woocommerce product archive display view.

Customising ▸ WooCommerce ▸ Archives ▸ Product Entry Media

When set to image swap with only a featured image and no gallery images. The image in the archive view  obtains a left and right margin instead of filling the available image space (see screenshot) This is the same outcome as if selecting just featured image from the dropdown. 

Setting a featured image and gallery image to the same image when using image swap also produces the border.

<img width="775" alt="screenshot" src="https://user-images.githubusercontent.com/462011/42516510-00f28b8a-8456-11e8-8751-97c45bff9161.png">

**Comment by deebz** [comment]
adding the following css rule seems to resolve the issue...
.woo-entry-image-main {
	width:400px;
}

**Comment by nicolas-owp** [comment]
Hello, add directly width: 100%
