### ISSUE TITLE
[Feature Request] - Integrate WPSL with the WooCommerce login forms

### ISSUE THREAD

**Issue by zeinnicholas** [oceanwp/oceanwp#108]
Hey Nic,

Is it possible to add the same integration, already available with the Popup Login extension, with the WordPress Social Login plugin to the WooCommerce login/register forms and multi-step checkout form?

I've tried this option: [https://wordpress.org/support/topic/woocommerce-does-it-work?replies=3#post-5474168](https://wordpress.org/support/topic/woocommerce-does-it-work?replies=3#post-5474168). It works fine in the WC login/register form in my-account. But it's triggering a fatal error in the multi-step checkout form.

I'm a little lost here.

Any thoughts?

Best regards

**Comment by nicolas-owp** [comment]
Hello, unfortunately, it would be a little complicated just to add the social login in those pages.

**Comment by zeinnicholas** [comment]
No problem! Thanks for the reply!

**Comment by nicolas-owp** [comment]
You're welcome :)
