### ISSUE TITLE
Fatal error: Uncaught Error: Class Elementor

### ISSUE THREAD

**Issue by TATIYA** [oceanwp/oceanwp#109]
Hello 
v1.5.19
Elementor plugin not installed and used in the theme.
I guess you should check if the class exist before using it

Fatal error: Uncaught Error: Class 'Elementor\Plugin' not found in /wp-content/themes/oceanwp/inc/woocommerce/woocommerce-config.php:338

**Comment by nicolas-owp** [comment]
Hello, you're right, sorry I forgot to check, I updated the theme to fix this.
