### ISSUE TITLE
Single Post Blog Title heading

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#11]
Hi, i noticed when I read a single blog post , the title is an H2 (must be H1 for SEO).
Is possible to change to H1 so the page have an H1?
Looking in the configurator i was able only to find how to change position of elements:

![image](https://user-images.githubusercontent.com/16102074/28387337-eba57dd6-6cce-11e7-80fa-00d5e862a7a7.png)

I dont know if i'm lost and there is some option to change somewhere but could be nice for SEO to have in the blog post single page the H1 title

![image](https://user-images.githubusercontent.com/16102074/28387363-102b9cf8-6ccf-11e7-8fa8-5ff0f7023824.png)

Ty

**Comment by oceanwp** [comment]
Hi, the H1 is the page header title, where you can put the title of your post, so if you remove the page header and want to put the H1 for the title of your posts, I created a filter "ocean_blog_entries_heading" .

**Comment by HartLarsson** [comment]
anyway in single post (when you read the blog post) the title must be H1 because there are no more page headers/titles around.
For the SEO the H1 is the main content and i think you could implement a change in the single blog posting reading from H2 to H1 by default.

Ty :)

**Comment by oceanwp** [comment]
No, because the H1 is the title of the page header.
But I gave you the wrong filter, it's for the blog entry, here is the filter for the title of the single post "ocean_single_post_heading".

**Comment by HartLarsson** [comment]
i'm not so expert on child theme, how i can mod the child theme to make H1 the title of the blogh post?

**Comment by oceanwp** [comment]
Hi, first, download the latest version of the theme on this repo, then follow this article: http://docs.oceanwp.org/article/453-alter-the-single-post-heading-tag
