### ISSUE TITLE
404 question

### ISSUE THREAD

**Issue by Atollmicro** [oceanwp/oceanwp#111]
Hi
I use the ocean wp theme to create a 404 page by video, but I found that typing https://shop.atolldive.com/sdgdfgdfgf at the URL doesn't link to the set 404 page, or to the original 404 page not found. .﻿
it is still linked to the wordpress preset 404 page
https://www.youtube.com/watch?v=6yo1jnM0DJg

![1](https://user-images.githubusercontent.com/39883426/42640153-421b2f02-8624-11e8-905b-2d7a0b6c8054.JPG)
![2](https://user-images.githubusercontent.com/39883426/42640154-4251731e-8624-11e8-8c47-82455d0391b0.JPG)
![3](https://user-images.githubusercontent.com/39883426/42640156-428f0422-8624-11e8-97a6-ef1c3d4c982d.JPG)

**Comment by nicolas-owp** [comment]
Hello, it seems something related to your host, contact him and ask him why instead of the default 404 page, you have another page?

**Comment by Atollmicro** [comment]
This is the website of my subdomain.
I have another main domain www.atolldive.com on this host. The 404 page of this website is normal.
Can a host have only one 404 page?

**Comment by nicolas-owp** [comment]
Hi, you will need to contact him because there is no redirection in OceanWP, it is the default 404 page of WordPress which is just customized in the theme.

**Comment by Atollmicro** [comment]
Thanks a lot

**Comment by nicolas-owp** [comment]
You're welcome :)

**Comment by Atollmicro** [comment]
I asked the host and forum and got the following reply.

Https://www.linode.com/community/questions/17022/can-a-subdomain-404-page-point-to-a-custom-page#answer-66666

I am puzzled that I used another virtual host to open a subdomain test and the results are normally steerable.

However, in the linode nginx host, the subdomain 404 custom page is not working properly. I don't know if it is different!

**Comment by nicolas-owp** [comment]
Unfortunately, there is nothing I can do on my side.
This is why I always recommend a managed WordPress host, so if you have an issue like this, you contact them, and they give you the solution.
