### ISSUE TITLE
[Feature Request] Icon select in the Customizer

### ISSUE THREAD

**Issue by knightknight** [oceanwp/oceanwp#113]
OceanWP ships with [Font Awesome](https://fontawesome.com) and [Simple Line](http://simplelineicons.com/) Icons but unless your changing the `<i>` within the partial files there is no way to access them. 

Elementor's default is FontsAwesome but OceanWP partials are using Simple Line. Unless there is a way to change Elementor default icon!? It makes sense that OceanWP's where same as Elementors, or make the selectable within the customizer, something similar to the **Scroll to Top** panel with some global settings:

- Select Font (like  [Better Font Awesome](https://wordpress.org/plugins/better-font-awesome/) dropdown): fontsawesome | Simple Line Fonts
- Size

**Comment by nicolas-owp** [comment]
Hello, it is better to change the icons you want via CSS, if I add too many settings in the customizer, it would be too long to load so I only add necessary settings.
What icon do you want to change and with what other icon?

**Comment by knightknight** [comment]
I was while I was editing a duplicated copy of partials/single for a custom post type in my child theme. The icons in the meta.php where Simple Line, where as using Elementor on other areas of the site I was using Font Awesome. My Elementor homepage is using Font Awesome icons the blog page

For the custom post type partial files I just change the `<i class="icon-folder"></i>` to font awesome `<i class="fa fa-folder-o fa-2x" aria-hidden="true"></i>`. So I thought a general/global icon select would make it easier to keep icons the same when your using Elementor and OceanWP. Unless there is a hook to replace all <i>.

**Comment by nicolas-owp** [comment]
It would be too complicated to add a setting to allow users to change every single icon present in different areas of the theme. It would be better to use css so no need to add many files in your child theme.
