### ISSUE TITLE
padding problem in sidebar

### ISSUE THREAD

**Issue by Rayner33** [oceanwp/oceanwp#116]
I have a little problem with left padding in sidebar personalize settings.
Whenever Im trying to change padding left, there is still 30px padding. When Im checking css there is something like this:
.widget-area.sidebar-primary {
    float: right;
    padding-left: 30px;
}
Rest paddings I can edit.

**Comment by nicolas-owp** [comment]
Hello, add this css code int he custom css section of the customizer:

```
.widget-area.sidebar-primary {
    padding-left: 0;
}
```

**Comment by Rayner33** [comment]
sure, but I think that it should work in presonalize panel without changing the css code. If it could be fix in future, will be nice.

**Comment by nicolas-owp** [comment]
It is solved for the next release :)

**Comment by Rayner33** [comment]
Great :) and thx for fantastic work!

**Comment by nicolas-owp** [comment]
You are most welcome :)
