### ISSUE TITLE
Debug : Undefined index variation & variation_id

### ISSUE THREAD

**Issue by aksld** [oceanwp/oceanwp#119]
Hi,

I don't know if I did something wrong.

In my debug.log, i have this :

`PHP Notice:  Undefined index: variation in oceanwp/inc/woocommerce/woocommerce-config.php on line 692
[09-Aug-2018 14:27:55 UTC] PHP Notice:  Undefined index: variation_id in oceanwp/inc/woocommerce/woocommerce-config.php on line 691`

I don't use variation for my products.

**Comment by aksld** [comment]
Hello,

Version 1.5.22

I have a custom form for add_to_cart action. Maybe that's the reason ?

Do I have to add an input related to the variations ?

**Comment by nicolas-owp** [comment]
Hello, having no answer from you, I assume that you solve the issue, feel free to reach me again if it is not the case and you still need help :)
