### ISSUE TITLE
Custom title

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#12]
I try to put a custom title on the Blog page using the OcenWP setting on the page 

![image](https://user-images.githubusercontent.com/16102074/28387806-c50f0af0-6cd0-11e7-989a-dd94dbf6b5f8.png)

but nothing changes on the page, the name remain the menu/page name

![image](https://user-images.githubusercontent.com/16102074/28387824-dfee557e-6cd0-11e7-8baa-6db247f9b772.png)

if instead i input something in **Subheading** field it appear under the "Blog" works correctly.
There is a **locking parameter somewhere** that not allow me to change the Page title default name?

ty

**Comment by oceanwp** [comment]
Hello, you can not change the title via this options on a few pages like your Home page, Blog, Search, etc ...
You must do this via the child theme and the "ocean_title" filter.

**Comment by HartLarsson** [comment]
So Custom Title where is working?

**Comment by oceanwp** [comment]
On all other pages, posts or CPT.

**Comment by HartLarsson** [comment]
ah ok :)
so i need to install a child theme with the function you said to change that page title :)

**Comment by oceanwp** [comment]
Yes, here the child theme: https://github.com/oceanwp/oceanwp-child-theme
And use the filter I gave you.
