### ISSUE TITLE
[Help] Anymore hook/filters for Page Title, height, opacity and bg-color css

### ISSUE THREAD

**Issue by knightknight** [oceanwp/oceanwp#121]
We can modify the [Page Title background image](https://docs.oceanwp.org/article/459-alter-the-page-header-background-image) using filters but are there any for setting the:

- Title: Background Height
- Title: Background Overlay Opacity
- Title: Background Overlay Color

**Comment by nicolas-owp** [comment]
Hello, it is not filters but only CSS for this.

Background Height:
```
.background-image-page-header {
    height: 450px;
}
```
Background Overlay Opacity:
```
.background-image-page-header-overlay {
    -moz-opacity: .5;
    -webkit-opacity: .5;
    opacity: .5;
}
```
Background Overlay Color:
```
.background-image-page-header-overlay {
    background-color: #fe5252;
}
```

**Comment by knightknight** [comment]
@nicolas-owp 👍

Just to add to this for further reference. I was targeting a custom post type archive page template which OceansExtra didn't have any affect on. I also didn't want to affect all the other post/page/cpt's using page title backgorund-image. 

So using the [Alter the Page Header Background Image](https://docs.oceanwp.org/article/459-alter-the-page-header-background-image) function: 

- `if ( is_archive( 'custom-post-type' ) ) { ...}`
or
- `if ( is_archive( 'custom-post-type' ) || is_singular( 'publications' ) ) { ... }`

and combined with a targeted CSS of the post-type's body class:

- `.post-type-archive-custom-post-type .background-image-page-header { ... }`
- `.post-type-archive-custom-post-type .background-image-page-header-overlay { ... }`

**Comment by nicolas-owp** [comment]
Ah okay, yes your code is perfect :)
