### ISSUE TITLE
Updating OceanWP Page settings on Elementor Template don't work on Toolset Type

### ISSUE THREAD

**Issue by daankauwenberg** [oceanwp/oceanwp#122]
On a website running Elementor Pro 2.1.2 and OceanWP 1.5.23 updating the OceanWP settings doesn't work as expected.

The site shows page titles by default. When turning them of on the Elementor Template the page title doesn't show up in the Elementor Editor but does show up when the template is being rendered. Problem occurs on a single template as well on an archive template. The post type is a custom type added with Toolset. When changing an OceanWP setting and clicking update, no revision is added in the list.

To reproduce:

- Create an content type in Toolset
- Make a custom template using Elementor
- Change a default setting from the OceanWP page settings for that template.

Site title settings of Elementor Template:
![screen shot 2018-08-13 at 16 12 58](https://user-images.githubusercontent.com/9211670/44037173-edb36cc8-9f13-11e8-9ec1-80e7febdcc32.png)

Elementor Preview:
![screen shot 2018-08-13 at 16 12 47](https://user-images.githubusercontent.com/9211670/44037187-f9f7d58c-9f13-11e8-809e-f9177b466867.png)

Eventual Rendering:
![screen shot 2018-08-13 at 16 13 13](https://user-images.githubusercontent.com/9211670/44037202-05482dce-9f14-11e8-9ddc-05540ceba8ed.png)

**Comment by nicolas-owp** [comment]
Hello, if you change the settings in the OceanWP Settings, that will change them for the template not the page where you use the template, for this you will need to change the settings via your child theme, the customizer or directly the page.
