### ISSUE TITLE
Slick font files not found

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#123]
Hello

I am checking my logs and the Slick font is not loaded correctly.

`/wp-content/uploads/fonts/slick/slick.ttf` url is 404.

OceanWP Version : 1.5.23 with a child theme.
Scripts & styles enabled, Slick is active.

See the main CSS `https://www.antineahotel.com/wp-content/uploads/oceanwp/main-style.css` is trying to load `../fonts/slick/slick.eot` which should be in `/wp-content/uploads/fonts/` but is not.

Thank you!

**Comment by nicolas-owp** [comment]
Hello, can you tell me how can I replicate the issue? I disabled one script and one style, it doesn't return the error you have on my console.

**Comment by nicomollet** [comment]
@nicolas-owp 
The error show in my Nginx error logs as 404. But not in chrome developer console, I don't know why.

Please look at the file generated by Ocean:
https://www.antineahotel.com/wp-content/uploads/oceanwp/main-style.css

**Comment by nicolas-owp** [comment]
Hi, is it possible for you to create a pre-purchase ticket on oceanwp.org with the login details of an admin account and FTP account on your site? I will try to solve this problem.

**Comment by nicolas-owp** [comment]
Hello, I was finally able to reproduce the issue, it will be fixed for the next release, thanks for letting me know :)
