### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#124]
The ability to set the background to fade out when navigating with a full content width megamenu would be a nice addition

**Comment by nicolas-owp** [comment]
Hello, can you show me an example?
Thank you.

**Comment by deebz** [comment]
https://www.evanscycles.com/
or 
https://www.johnlewis.com/

**Comment by nicolas-owp** [comment]
Ah okay, an overlay when the sub menu is hovered, that's right?

**Comment by deebz** [comment]
That's correct! I personally feel that it helps seperate mega menu type menus from the content a little

**Comment by nicolas-owp** [comment]
Hi, I will try to see if it is possible for a future release :)
