### ISSUE TITLE
Compatibility Issue With Elementor Pro

### ISSUE THREAD

**Issue by plxrisa** [oceanwp/oceanwp#125]
Hi,

For my product page, I have set in customize:
Related Items Count : 4
Related Products Columns: 4
And I can see 1 Row with 4 columns.

But after the latest update (Elementor Pro 2.1.5), I can see in my product page 2 ROWS with 2 COLUMNS each. IF I deactivate the Elementor OR switch to another theme, the related products display as they should.

To test it:
1. Set --> Related Items Count : 4
2. Set -- > Related Products Columns: 4
3. Update to elementor Pro 2.1.5
4. Check the product page
5. Deactivate Elementor OR switch to another theme, (I tested with twenty seventeen)
6. Check again the product page

It seems that Ocean and Elementor have compatibility issue.

**Comment by nicolas-owp** [comment]
Hello, I have tried with other themes, it doesn't work either, I will ask to Elementor what is wrong.

**Comment by plxrisa** [comment]
This issue is resolved.
