### ISSUE TITLE
categories are rendered double

### ISSUE THREAD

**Issue by codeagencybe** [oceanwp/oceanwp#126]
Hello Nicolas,

After latest updates, I notice store categories are now showing double. 
I'm just playing around on my demo server and site and just notice this. 

sidenote: I have created a custom product layout in Elementor Pro and also created a custom archive layout. 
With or without doesn't matter, the cats are always double. 
It happened after the last updates from OWP extras and theme and also Elementor 2.2 and Elementor Pro. 
So I'm not sure which one is causing the culprit. 
It's not a big deal here as it's just a sandbox server, but perhaps this happens also on the live products now if I update those. 
So I'm holding back until it's cleared out where this issue is coming from. 

![image 2018-08-29 at 5 13 56 pm](https://user-images.githubusercontent.com/7568546/44797377-5cd6af00-abaf-11e8-8cf3-69f6e20aea43.png)
URL: http://sharing.codeagency.be/e9a237a99f97

video recording with explanation in customizer:
http://sharing.codeagency.be/7c9741814495

**Comment by nicolas-owp** [comment]
Hello, have you tried to disable your plugins to see if there is a conflict?

**Comment by codeagencybe** [comment]
Hello Nicolas,

It seems to be a combination of OceanWP and JetWooBuilder by Zemez. 
When I disable JWB, it's back to normal. 

When I try theme twenty seventeen with JetWooBuilder, it works fine. 
That's why I though it was an OWP issue at first. 

When I change back to OceanWP, problem is back again. 
I will check with Zemez if they know about this and release a fix.

**Comment by nicolas-owp** [comment]
Hi, yes, let me know if something needs to be added directly in the theme.
