### ISSUE TITLE
How to add a global block in single post template ?

### ISSUE THREAD

**Issue by toton333** [oceanwp/oceanwp#128]
Hi, i have created a section using Elementor in My Library of Theme Panel, and i have its shortcode. I want to put it just below the nav menu bar of the single post on the customizer so that it applies globally to all single posts. How can i achieve it?

**Comment by nicolas-owp** [comment]
Hello, you can easily do that with Ocean Hooks: https://oceanwp.org/extension/ocean-hooks/
