### ISSUE TITLE
Content padding settings not working

### ISSUE THREAD

**Issue by bensteers** [oceanwp/oceanwp#13]
The content padding settings (Customize: General Options -> General Settings -> Content Padding), when set to zero, will update in the customize preview, but when I view the actual page, the padding is still set to 50px. I just tried 1px and that worked so I am guessing it's some check for a false-y value gone wrong.

**Comment by oceanwp** [comment]
Hello, yes indeed, the number 0 does not work in the customizer, it is seen as null so returns the default value.
