### ISSUE TITLE
[oceanwp_woo_total_cart] always show excluding TAX when settings is set to including TAX

### ISSUE THREAD

**Issue by codeagencybe** [oceanwp/oceanwp#134]
Hello Nicolas,

In the Woo popup extension, I have this default line:
[oceanwp_woo_cart_items] items in het winkelmandje ([oceanwp_woo_total_cart])

WooCommerce is set to show pricing including TAX but your shortcode [oceanwp_woo_total_cart] always shows excluding TAX. 
I have been searching if there is a way to control the tax specific for this extension, but I don't see anything. 

You can see issue here: 
http://sharing.codeagency.be/4769fe61868e

Can you please check and see if you can push an update with fix for this? 
Thanks!

**Comment by codeagencybe** [comment]
UPDATE

Same problem with [oceanwp_woo_free_shipping_left]

This one also calculates based on excluding TAX.

**Comment by nicolas-owp** [comment]
Problem fixed :)
