### ISSUE TITLE
The functions.php code to RTL support with Child theme 

### ISSUE THREAD

**Issue by ElchananLevavi** [oceanwp/oceanwp#135]
Hello!
The published code that published in Ocean's site isn't working for me :
https://docs.oceanwp.org/article/455-add-the-rtl-style-to-the-child-theme
I fixed it that way (and offers to change the code in the documentation):
/**
 * Load the parent rtl.css file
 */
function oceanwp_child_enqueue_rtl_style() {
	// Dynamically get version number of the parent stylesheet
	$theme   = wp_get_theme( 'OceanWP' );
	$version = $theme->get( 'Version' );
	// Load the stylesheet
	if ( is_rtl() ) {
		wp_enqueue_style( 'oceanwp-rtl', get_template_directory_uri() . '/rtl.css', array( 'oceanwp-style' ), $version );
	}
}
add_action( 'wp_enqueue_scripts', 'oceanwp_child_enqueue_rtl_style' );

**Comment by nicolas-owp** [comment]
Hello, changed, thanks a lot :)
