### ISSUE TITLE
[BUG] blog single full width | Custom width, bulleted or numbered List

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#136]
Hi Nicolas,
there is a little bug in blog single full width using custom width setting. 
When using an bulleted or numbered List, the width set in customizer is not respected by this elements..
Flows outside the container..

https://imgur.com/a/t27pWez

Best regards,
stefan

**Comment by nicolas-owp** [comment]
Hello, can you send me the single post url where you have this problem?

**Comment by stevek28** [comment]
Hi Nicolas, unfortunately not.. was just localhost.. Attached the post content to recreate..

[style-guide-content.txt](https://github.com/oceanwp/oceanwp/files/2475479/style-guide-content.txt)

Also sometimes after a few changes of width in Customizer-> e.-g- value 0 (full width) 800, 700, 600 and back, the live view doesn't update anymore - only after save the change is visible on the site (outside customizer) again.. This happens sometimes with a few OWP customizer settings..

PS: Could you please have a short look into my question in FB Group concerning Breadcrumbs (14h ago) as well, as no one seems to have an answer..

Thank you!

Greetings,
stefan

**Comment by nicolas-owp** [comment]
Hi, can you try this css code:

```
.single-post.content-max-width .entry-content ul {
    padding-left: 40px;
}
```

For the customizer settings, can you list the settings who don't work well?

For your other issue, it is better to open a support ticket.

Thank you.

**Comment by stevek28** [comment]
Thanks for the code Nicolas! 
Will you fix this in the theme? The css isn't the best option in this case regarding responsiveness..

Sorry, can't tell you right know for which fields in the customizer this happens.. Just my experience using   OWP in the last 2 years.. I will post it here when it happens again..

Ok, I will open a ticket for breadcrumbs..

Thank you!

Have a nice we!

Stefan

**Comment by nicolas-owp** [comment]
I will try to see to add the code directly in the theme yes.
Have a great weekend too :)
