### ISSUE TITLE
Customizer options for displaying Site Title and Tagline ignored

### ISSUE THREAD

**Issue by blinkcursor** [oceanwp/oceanwp#14]
I unchecked "Display Site Title and Tagline" in Customizer > Site Identity but they were still printed in the header.

The file responsible is oceanwp/partials/header/logo.php

Lines 55 and 66 output the title and tagline respectively without first using get_theme_mod to check the customizer setting, hence it has no effect.

I had a quick look with get_theme_mods() and I can't see the option saved any way, even though it is available in the customizer.

**Comment by oceanwp** [comment]
Hello, thank you for letting me know, I had not noticed this option. I will delete it in the next version.
