### ISSUE TITLE
Ocean Extra: scripts in footer

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#142]
Hello

Being using Ocean Extra, and discovered some scripts not being loaded in footer:
share.min.js
mailchimp.min.js

If you could please fix it?
Thank you

**Comment by nicolas-owp** [comment]
Hi, I would need some more information about this, could you create a pre-purchase ticket on oceanwp.org and send me the login details of an admin account? I will check what is wrong.
Thank you.

**Comment by nicomollet** [comment]
@nicolas-owp I don't think you need my credentials to see the `$in_footer` of the functions calls to `wp_enqueue_script` are not set.

All the `wp_enqueue_script` calls could be fixed by setting:
* `$ver` to `false`
* `$in_footer` to `false`

in: 
` wp_enqueue_script( 'oe-social-share', OE_URL . '/includes/widgets/js/share.min.js', array( 'jquery' ) );`

`wp_enqueue_script( 'oe-insta-admin-script', OE_URL .'/includes/widgets/js/insta-admin.min.js', array( 'jquery' ) );`

`wp_enqueue_script('oe-mailchimp-script', OE_URL . '/includes/widgets/js/mailchimp.min.js', array('jquery'));`

Thank you.

**Comment by nicolas-owp** [comment]
Oh sorry, I misread your first message, I taught you had an issue with those two files on your console.
Fixed for the next release.
You are absolutely right, I don't know why, I forgot to do this, fixed for the next release of Ocean Extra.
Thank you :)
