### ISSUE TITLE
[BUG] Typography Setting Line height / OWP - Elementor

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#143]
Hi,
when changing the line height in OWP Customizer / Typography the line height isn't transferred to Elementor pages (Disabled Default Fonts). The rest of the settings work fine..

Fails for All headings and Heading 1-4. Body text Line Height works fine..

Greetings,

stefan

**Comment by nicolas-owp** [comment]
Hello, I can do nothing about that, Elementor has its own line height, you need to change it via the plugin of Elementor.
