### ISSUE TITLE
Google Maps Widget: "Uncaught TypeError: Cannot read property 'firstChild' of undefined"

### ISSUE THREAD

**Issue by levi-beers** [oceanwp/oceanwp#145]
OceanWP Theme: 1.5.28
OceanWP Extras: 1.4.29
OceanWP Elementor Widgets: 1.1.1

Receiving the Uncaught TypeError for property 'firstChild' when Google Maps Widget is used. This also happens on the OceanWP website. See attached image.

<img width="1564" alt="screen shot 2018-10-22 at 11 41 27 am" src="https://user-images.githubusercontent.com/16378407/47302467-8fb98400-d5ef-11e8-940d-8dddf7938e1b.png">

**Comment by nicolas-owp** [comment]
Hello, thank you for letting me know, I work on this problem and I will release a new update as soon as I find a fix.
Thank you :)
