### ISSUE TITLE
Elementor & Ocean compatibility regarding WooCommerce products

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#146]
Hello

Ocean doesn't play well with the new WooCommerce builder from Elementor.
(https://elementor.com/blog/introducing-woocommerce-builder/)

When creating a "Product Archive" template in Elementor, and adding an "Archive Products" widget in the template, the Ocean templates for WC change the default WC classes and make it impossible to customize the "Archive Products" widget.

For example customizing the product title applies styles the `ul.products li.product .woocommerce-loop-product__title` class.
But Ocean doesn't use this class.

So in the end, Ocean and Elementor features are in conflict because they pretty much try to do the same thing.
You might consider this for the future updates.

Thank you.

**Comment by nicolas-owp** [comment]
Hello Nico, yes, some users told me about this, I actually work with Elementor to see and fix all the issues.
Feel free to tell me if you have any other trouble.
Thank you :)

**Comment by nicomollet** [comment]
I manage to do what I want, but really the hardest part it to decide what to do in Elementor or in OceanWP.
Some stuff is better in Ocean, some other is better in Elementor.

I guess you should ensure maximum compatibility with Elementor.
But maybe you could disable Ocean WooCommerce features when Elementor is installed.

**Comment by nicolas-owp** [comment]
I cannot remove the WooCommerce features, a lot of users doesn't use Elementor to create their shop or single product pages.
