### ISSUE TITLE
Strange error from elementor

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#15]
Hi,

i've discovered an error with Elementor (latest version) with oceanWP latest version on the blog page

![image](https://user-images.githubusercontent.com/16102074/29146020-aca330e6-7d5f-11e7-844a-93d8d9c4c3c9.png)

if you give me your email i will send more info about.

**Comment by oceanwp** [comment]
Hello, I know, I have contacted Elementor for that, I wait their answer.

**Comment by HartLarsson** [comment]
thank you i've sent them all debug log to find out where is the problem too.
I hope they will fix or find a solution.

Thank you so much

**Comment by HartLarsson** [comment]
any news?

**Comment by oceanwp** [comment]
Hello, no news yet, if you still have this problem on your site, can you contact the elementor support and create an admin account so they can fix this?
I do not have this error on any of my sites and I do not know how to reproduce it.
Thank you.

**Comment by HartLarsson** [comment]
hi, I gave them an admin access they ask me to disable any plugin but only with elementor enabled i've the same problem. I have sent them the log. and infos ... cross fingers

if you want to see: https://www.lapastadibologna.com/blog/

**Comment by oceanwp** [comment]
I'm pretty sure this will help them to find the issue :)
Thank you.

**Comment by HartLarsson** [comment]
i Hope, the site works anyway seems only aproblem on the main blog page

**Comment by HartLarsson** [comment]
i've received a notice from elementor support that they find the problem and will be fixed in next version.
I will keep you informed!

**Comment by oceanwp** [comment]
Hi, thanks for letting me know, the Elementor support team has also noticed me about that :)
So I close issue, it will be fixed the August 28 by the new Elementor version.
