### ISSUE TITLE
WooCommerce templates out of date

### ISSUE THREAD

**Issue by hjek** [oceanwp/oceanwp#150]
In **WooCommerce** -> **Status** we get a message indicating that the templates included in **OceanWP** are out of date:

> ### Templates
> Overrides: `oceanwp/woocommerce/cart/mini-cart.php`, `oceanwp/woocommerce/content-single-product.php`, `oceanwp/woocommerce/loop/loop-start.php`, `/var/www/html/wp-content/plugins/woo-variation-gallery/templates/product-images.php` version - is out of date. The core version is 3.5.1, `/var/www/html/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php` version - is out of date. The core version is 3.5.1, `oceanwp/woocommerce/single-product/title.php`

**Comment by nicolas-owp** [comment]
Hello, it is not OceanWP but the Woo Variation Gallery plugin who have outdated files :)

**Comment by nicolas-owp** [comment]
Hello, no problem at all :)
