### ISSUE TITLE
Transparent header overlap top bar nav

### ISSUE THREAD

**Issue by BlackShabat** [oceanwp/oceanwp#151]
When I use the top bar with multi-level navigation along with a transparent header, this header overlaps the drop-down menu due to the larger z-index - http://prntscr.com/lficd1

**Comment by nicolas-owp** [comment]
Hello, try this css code in the custom css section of the customizer:
```
#top-bar-wrap {
    z-index: 10000;
}
```

**Comment by BlackShabat** [comment]
Thanks. I've already resolved this problem in my project. But I think It should be fixed in the theme

**Comment by nicolas-owp** [comment]
Hello, I will try to see how to add it in the theme because  I can not adds it by default as it will cause some issue with other header styles.
