### ISSUE TITLE
Infinite scrolling Problem

### ISSUE THREAD

**Issue by ElchananLevavi** [oceanwp/oceanwp#152]
Hello!
The infinite scrolling in my blog works fine in the main posts page, but doesn't working in categorie's archive pages.

The Infinite scrolling javascript is enabled in the Scripts & Styles Panel.
The error in the console when the problem occurs is "Failed to load resource: the server responded with a status of 404 ()" for the url https://www.sivanrahavmeir.com/%d7%94%d7%97%d7%9c%d7%a7-%d7%94%d7%99%d7%95%d7%9e%d7%99/page/2
The problem occurs even when all the plugins are deactivated.
theme version: 1.5.32

Links to the blog:
Category archive url: https://www.sivanrahavmeir.com/החלק-היומי
Main posts page: https://www.sivanrahavmeir.com/%D7%9B%D7%AA%D7%91%D7%95%D7%AA

**Comment by ElchananLevavi** [comment]
I solved it.
https://wordpress.stackexchange.com/questions/172958/custom-permalink-structure-leads-to-be-404-on-pagination

**Comment by nicolas-owp** [comment]
Hello, I'm so sorry for the waiting time, I always answer support tickets and I forgot about GitHub :)
Very glad that you solved your issue.
