### ISSUE TITLE
oceanwp theme cannot show WooCommerce reviews

### ISSUE THREAD

**Issue by kuan5876** [oceanwp/oceanwp#153]
oceanwp theme cannot show WooCommerce reviews, but other wp themes are able to show the reviews. Does anyone know what happened? 

here is my link:

https://tribotexmacao.com/product/10ml/

**Comment by nicolas-owp** [comment]
Hello, have you tried to disable your plugins to see if there is a conflict?

**Comment by nicolas-owp** [comment]
Hi, having no answer from you, I assume that your issue is solved. If it is not, feel free to answer to this topic.
