### ISSUE TITLE
Callout Text not displayed

### ISSUE THREAD

**Issue by sks7g** [oceanwp/oceanwp#154]
Hi Nick,

I'm just taking a first look at the current WP version 5.0, including Elementor and OceanWP (thanks for your work). 

I am using the default layout, I have no demo installed, enabled. 

I just noticed that the "Callout Text" I entered is not displayed ("Lorem ipsum dolor sit amet consectetur ni adipiscing elit" is still displayed).  However, the changed text for the "Callout Button" is displayed.

I think your demos are very good, but I'm missing a "reset function" here, the import, everything cleaned up again. Just such a thought ... (I am currently working with a backup/restore or "WP Reset")
BR Erik

**Comment by nicolas-owp** [comment]
Hello, thank you for the nice words :)
I would need to access your site to be able to know why you cannot change the callout text, could you create a support ticket with admin login details?

For the reset function, there are very good plugins to reset a site so I don't really need to add such a feature on the theme as many users will click n it to see what the button does and will reset their sites :)
