### ISSUE TITLE
Difference between "Customizer" and OceanWP Settings

### ISSUE THREAD

**Issue by sks7g** [oceanwp/oceanwp#156]
If I want to set up a page, I can use the WP Customizer or "Page/Edit/OceanWP Settings". But where is the difference?

If I do the setup under "Page/Edit/OceanWP Settings", it will not be taken over into the "Customizer", the same applies. However, the last setup is taken over, no matter where (example Stiky Header: Background Color).

**Comment by nicolas-owp** [comment]
Hi, the difference is when you change a setting in the customizer, it affect your entire site, if you edit a setting in the OceanWP Settings metabox, it change only on the page/post.
