### ISSUE TITLE
bbPress and BuddyPress compatibility

### ISSUE THREAD

**Issue by harveydogg** [oceanwp/oceanwp#157]
There are some layout/display issues for both bbPress and BuddyPress, which only arise on mobile. I plan to try using some "spaghetti" CSS as a band-aid, but I'm wondering whether you have plans to address them more systematically. (I've attached relevant screenshots.)

![ss_forum topic](https://user-images.githubusercontent.com/22262069/50066942-80d4f500-018c-11e9-95cb-5437f70c3ffd.PNG)

![ss_groups](https://user-images.githubusercontent.com/22262069/50066949-8b8f8a00-018c-11e9-8e77-2b608cedbd4d.PNG)
![ss_group page](https://user-images.githubusercontent.com/22262069/50066950-8c282080-018c-11e9-8f65-0cd75e32dbdb.PNG)

**Comment by nicolas-owp** [comment]
Hi, having no answer from you, I assume that your issue is solved. If it is not, feel free to answer to this topic.
