### ISSUE TITLE
Blank Dashboard item with Ocean Extra

### ISSUE THREAD

**Issue by iamsayan** [oceanwp/oceanwp#159]
Hello, I have found that Ocean Extra v1.5.0 plugin creates an empty item in dashboard menu after home and updates. Link: http://prntscr.com/m6nue7

It can be found at `ocean-extra/includes/wizard/wizard.php on line 98`. Please correct this issue.

**Solution:** Remove this item completely.

`public function hide_ocean_wizard_item() {
        remove_submenu_page( 'index.php', 'owp_setup' );
}`
`add_action( 'admin_head', array( $this, 'hide_ocean_wizard_item' ) );`

Thanks!

**Comment by nicolas-owp** [comment]
Hello, thanks for letting me know, I will try to find a solution, because this one doesn't work, it will remove the setup wizard notice as well.

**Comment by iamsayan** [comment]
But in my case, after activation of Ocean Extra Plugin setup wizard notice is showing. http://prntscr.com/m7d533

**Comment by nicolas-owp** [comment]
Hi, it is not a very good solution, sorry :)
I will need to find how to do it.
