### ISSUE TITLE
Allow WooCommerce images to use lazyload

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#161]
Hello,

At the moment Ocean theme rewrites the WooCommerce pages, like the product archives/lists.

To display the product images, the `wp_get_attachment_image` function is used and this function doesn't have filters to rewrite the `img` tag.
Meaning, those images can't be lazyload-ified.

To allow lazyload, other functions could be used, like:
* `get_the_post_thumbnail()` (WP core function) (which has a filter `post_thumbnail_html` that lazyload plugins use, like A3 Lazy Load, Lazyload by Mohammad Jangda or WP Rocket)
* `$product->get_image()` (WooCommerce function)

I would appreciate a solution to allow lazy load on WooCommerce pages, with Ocean.
What's your take on this?

Thank you

**Comment by nicolas-owp** [comment]
Hi, I will try to see about lazyload, but with the other functions, it is not possible to do what I have done with the styles.
