### ISSUE TITLE
Quantity input needs min-width

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#162]
Hello,

As seen on this image
![quantity](https://user-images.githubusercontent.com/108828/51249521-dd961c00-1993-11e9-9a70-27714f0e6863.PNG)

The quantity field doesn't have enough width to be displayed.
This example is with a product type = grouped. My website is underconstruction for now, can't give the url yet.
How to use Grouped products (WC core function) https://www.sellwithwp.com/creating-woocommerce-grouped-products-version-3-0/

Min-width of 110px on `.quantity` seems to fix the issue.

Thanks

**Comment by nicolas-owp** [comment]
Hello, thanks a lot, the code will be added for the next release.
