### ISSUE TITLE
Popup login localization issue

### ISSUE THREAD

**Issue by infodataservice** [oceanwp/oceanwp#163]
Hi, 
as suggested in this post: https://github.com/oceanwp/oceanwp/issues/84 I used poedit to make italian localization for Popup Login extension, but it simply doesn't work, i can only see english texts in login form, registration forms, reset password form. 
I made attached .po and .mo files and uploaded it in wp-content/plugins/ocean-popup-login/languages, my site is localized as "Italian" in settings page, but italian language file doesn't load correctly.
thank you

[oceanwp-popup-localization.zip](https://github.com/oceanwp/oceanwp/files/2786529/oceanwp-popup-localization.zip)

**Comment by nicolas-owp** [comment]
Hello, sorry for the late answer, do you still have the issue? Because the translation works normally for my case.

**Comment by infodataservice** [comment]
hi. Yes, I still have the issue. I attach a screenshot for you. The only text that changed are the ones editet in the Appearence -> Customize wp menu, but not the one I changed in .po file
Thank you.

![localization-issue](https://user-images.githubusercontent.com/46957668/53330107-f9270780-38ed-11e9-866d-dd4ee4c9531b.PNG)
[localization mo po files.zip](https://github.com/oceanwp/oceanwp/files/2899975/localization.mo.po.files.zip)

**Comment by nicolas-owp** [comment]
Hello, is it possible for you to create a pre-purchase ticket on oceanwp.org, link this topic and to send me the login details of an admin and FTP account? I will try to see what can be wrong.
Thank you.
