### ISSUE TITLE
Display Cart When Product Added

### ISSUE THREAD

**Issue by idarkos** [oceanwp/oceanwp#164]
I love the option to display the cart dropdown when a product is added to the cart but there is a user experience issue currently with it.

When for example you are on a Product Archive page and scrolled down a bit when you add a product to the cart, the dropdown activates which also causes the .owp-cart-overlay to show up while the cart dropdown is not in the viewport. This ends up just showing a 50% black overlay without any indication of what happened which might confuse the visitor.

A good idea might be to have an extra option below the "Display Cart When Product Added" toggle to "Scroll To Cart/Top When Product Added".

Thanks! ☮️

**Comment by nicolas-owp** [comment]
Hello, yes, sorry, I never taught about that because I always use Ocean Sticky Header so the cart is visible when the user scroll, I will fix this in the next release, thanks for pointing it :)
