### ISSUE TITLE
OceanWP mobile

### ISSUE THREAD

**Issue by Moonless-Lotus-Lake** [oceanwp/oceanwp#165]
Hello,
I am having problems with the mobile version.
It doesn't show.
It says: Fatal error: Call to undefined function oceanwp_post_id() in /membri/threeel/wp-content/plugins/ocean-extra/includes/metabox/metabox.php on line 1893

**Comment by RajeebTheGreat** [comment]
Hi @Moonless-Lotus-Lake ,

This issue was solved in previous version updates.
Please make sure you have the latest version of both OceanWP and Ocean Extra plugin.

**Comment by Moonless-Lotus-Lake** [comment]
If I deleted the OceanWP and then reinstalled the newest version, do I need to customize again from the start?

**Comment by RajeebTheGreat** [comment]
No. Your settings/content will be preserved when you update or "delete and reinstall" the theme. 

But if you have directly edited the theme code, it will be lost. You should always use a child theme if you need to edit the theme code.

https://docs.oceanwp.org/article/90-sample-child-theme

Also, note that if you are switching to child theme now, your settings will be lost. First go to Theme Panel > Import/Export and get the export file.

Switch to child theme and and import the settings file.

**Comment by Moonless-Lotus-Lake** [comment]
Hello,
thank you very much, I updated the theme but after that I have this on mobile:

Warning: array_flip(): Can only flip STRING and INTEGER values! in /membri/threeel/wp-content/plugins/essential-addons-for-elementor-lite/includes/class-wpdev-notices.php on line 425
Fatal error: Call to undefined function oceanwp_post_id() in /membri/threeel/wp-content/plugins/ocean-extra/includes/metabox/metabox.php on line 1893

And this on desktop, on the menu:
Warning: array_flip(): Can only flip STRING and INTEGER values! in /membri/threeel/wp-content/plugins/essential-addons-for-elementor-lite/includes/class-wpdev-notices.php on line 425

**Comment by Moonless-Lotus-Lake** [comment]
The ocean extra is the latest version 1.5.0

**Comment by RajeebTheGreat** [comment]
Hi,

That error is from Essential Addons for Elementor unrelated to OceanWP? Can you please confirm you updated Ocean Extra plugin as well?

**Comment by Moonless-Lotus-Lake** [comment]
Yes, it's updated.
I thought it was solved because for a sec on the mobile was okay, then I refreshed the page on mobile and then it's gone again with that fatal error again.

**Comment by RajeebTheGreat** [comment]
Hi,
I suggest you contact OceanWP Support here - https://wordpress.org/support/theme/oceanwp/

There may be some other problem I can't diagnose without knowing more details.

**Comment by Moonless-Lotus-Lake** [comment]
Yes, it's updated.
I thought it was solved because for a sec on the mobile was okay, then I refreshed the page on mobile and then it's gone again with that fatal error again.
