### ISSUE TITLE
SEO Improvements for Woocommerce Integration

### ISSUE THREAD

**Issue by meerkatnomanners** [oceanwp/oceanwp#166]
2 Issues I discovered that are improvements to SEO standards.
1. Product Titles should be H1 not H2 that is hard-coded in associated theme file.
2. An instance of text "Cart" is in an H4 within "oceanwp-cart-sidebar-wrap" This should not be a header and instead a paragraph tag or similar.

**Comment by nicolas-owp** [comment]
Hello, you are absolutely right,

1. I will add a setting to allow users to choose which title tag they want, because the H1 is in the page header by default.

2. I will fix this in the next release.

Thank you.
