### ISSUE TITLE
JS error on scrolling : woo-floating-bar.min.js

### ISSUE THREAD

**Issue by shirokoweb** [oceanwp/oceanwp#167]
Hi, console shows a JS error when scrolling page.

OceanWPVersion : 1.6.3
Elementor PRO : 2.4.3
WooCommerce :  3.5.4

```
TypeError: a.offset(...) is undefined[Learn More] woo-floating-bar.min.js:1:100
<anonymous> https://website.tld/wp-content/themes/oceanwp/assets/js/third/woo/woo-floating-bar.min.js?ver=1.6.3:1 dispatch2jQuery

dispatch
handle 
```

**Comment by shirokoweb** [comment]
Update : this occures when OWP extra is not installed...

**Comment by nicolas-owp** [comment]
Hello, go to the WooCommerce > Single Product section of the customizer and disable the floating bar.
