### ISSUE TITLE
"Undefined" definition after clicking WooCommerce related product Add to cart button

### ISSUE THREAD

**Issue by shirokoweb** [oceanwp/oceanwp#168]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of OceanWP.

## Description

When clicking on "Add to cart" button on a related product (at bottom single product page), it shows "undefined" string instead of "View cart" string.
Appears to be related to :
ocean_after_archive_product_add_to_cart_inner
ocean_after_archive_product_add_to_cart

## Styeps to reproduce

Visit a single product page
Click "Add to cart" on any related product (woocommerce_after_shop_loop_item)
String displays "Undefined" instead of "View cart"

## Isolating the problem
- [X] This bug happens with OceanWP theme active (and WooCommerce).
- [X] This bug happens with OceanWP CHILD theme active (and WooCommerce).
- [ ] This bug happens with a default WordPress theme active (and WooCommerce).
- [ ] This bug happens with Storefront theme active (and WooCommerce).
- [X] This bug happens with French FR_fr language activated.
- [X] This bug happens with English EN_us language activated.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.12
	PHP Version: 7.2.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right

== WordPress Environment ==
	Version: 5.1
	Site URL: https://domain.tld
	Home URL: https://domain.tld
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: childtheme
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.6.4
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Ocean Extra
		Version: 1.5.3
		Author: OceanWP

	WooCommerce
		Version: 3.5.5
		Author: Automattic
</details>

**Comment by nicolas-owp** [comment]
Hello, what is your PHP version? Have you tried to disable your plugins to see if one of them could cause this issue?

**Comment by shirokoweb** [comment]
@nicolas-owp PHP Version: 7.2.15 as mentioned in System info.
There is no other plugins installed beside WooCommerce.
Fresh WP install

**Comment by nicolas-owp** [comment]
Hi, yes, sorry, I didn't saw it, can you create a pre-purchase ticket on oceanwp.org and send me the login details of an admin account? I will try to see what is wrong.

**Comment by shirokoweb** [comment]
Hi @nicolas-owp, thanks for answering on a sunday.
Form submitted as requested.

**Comment by nicolas-owp** [comment]
You're welcome :)

**Comment by yawalkar** [comment]
Hey @nicolas-owp,

I just tried on your demo page and the bug is replicable there as well. See screencast below from your demo -

![screen recording 2019-03-03 at 03 39 pm](https://user-images.githubusercontent.com/4975549/53693720-61805800-3dca-11e9-9cc4-f153c14441cc.gif)

Any quick solution?

**Comment by shirokoweb** [comment]
Problem is not visible when "Enable add to cart ajax" option is checked :
Customize > WooCommerce > Single product
![image](https://user-images.githubusercontent.com/6638982/53695899-87edc580-3dc1-11e9-95d9-9fd35df3f0af.png)

**Comment by nicolas-owp** [comment]
Hi, I will see what is wrong. It shouldn't act like this.

**Comment by shirokoweb** [comment]
The problem is with undefined **_oceanwpLocalize.view_cart_** in woo-floating-bar.js
As a Q&D fix you can use default WooCommerce param handler : wc_add_to_cart_params.i18n_view_cart

```
			// View cart text.
			if ( ! oceanwpLocalize.is_cart && $button.parent().find( '.added_to_cart' ).length === 0 ) {
				$button.after( ' <a href="' + oceanwpLocalize.cart_url + '" class="added_to_cart wc-forward" title="' +
					wc_add_to_cart_params.i18n_view_cart + '">' + wc_add_to_cart_params.i18n_view_cart + '</a>' );
			}
```

instead of 

```
			// View cart text.
			if ( ! oceanwpLocalize.is_cart && $button.parent().find( '.added_to_cart' ).length === 0 ) {
				$button.after( ' <a href="' + oceanwpLocalize.cart_url + '" class="added_to_cart wc-forward" title="' +
					oceanwpLocalize.view_cart + '">' + oceanwpLocalize.view_cart + '</a>' );
			}
```

Then deregister oceanwp-woo-floating-bar and register fixed one (in your child's theme functions.php) :

```
function oceanwp_child_enqueue_parent_style() {
	// Dynamically get version number of the parent stylesheet (lets browsers re-cache your stylesheet when you update your theme)
	$theme   = wp_get_theme( 'OceanWP' );
	$version = $theme->get( 'Version' );
	// Load the stylesheet

	if(is_product()){
			wp_dequeue_script('oceanwp-woo-floating-bar');
			wp_enqueue_script('oceanwp-woo-floating-bar',get_stylesheet_directory_uri(). '/assets/js/woo-floating-bar.js', array( 'jquery' ), false, true);
			
	}
	
	wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array( 'oceanwp-style' ), $version );
}
add_action( 'wp_enqueue_scripts', 'oceanwp_child_enqueue_parent_style' );
```

**Comment by nicolas-owp** [comment]
Thanks everyone, issue fixed, please, download the GitHub version and tell me if everything works correctly?
Thank you.
