### ISSUE TITLE
Move widgets to other footers

### ISSUE THREAD

**Issue by mr-j0nes** [oceanwp/oceanwp#169]
Once I have a widget setup to my needs, let's say in Footer 1 and later I decide that I should have put it in Footer 2, it would be good if the framework allowed me to move it. Currently I just need to add similar widget to Footer 2 and set it up from scratch.

Additionally it would be good to be able to enable/disable certain widget, currently I have to delete it and lose all the setup in it.

**Comment by nicolas-owp** [comment]
Hello, I misunderstood the issue, if you add a widget on your footer and you want to add it to another area, just drop it there, you don't need to re-add the widget.

**Comment by mr-j0nes** [comment]
Hi Nicolas, sorry I didn't explain myself well.

Imagine I am in Widgets->Footer 1, and I have a widget "About Me"
I want to move that widget to Widgets -> Footer 2.

Is it possible ?

**Comment by nicolas-owp** [comment]
Hi, yes, of course, you just need to drag the widget to Footer 2.

**Comment by mr-j0nes** [comment]
Thanks for the quick reply. 
I am trying to drag it but it just goes up and down. I cannot see Footer 2 unless I exit, but if I exit, I don't see the widget "About Me" anymore..

![image](https://user-images.githubusercontent.com/24613872/53687528-ea997f80-3d35-11e9-8445-ee18e09a3392.png)

Not sure I'm understanding how to do it.

**Comment by nicolas-owp** [comment]
Ah okay, you are in the customizer, go directly to Appearance > Widgets instead.

**Comment by mr-j0nes** [comment]
Excellent, now I see, thank you, I didn't know you can do it also from there.

**Comment by nicolas-owp** [comment]
You're welcome :)
