### ISSUE TITLE
Typo in German translation (Copywright instead of Copyright)

### ISSUE THREAD

**Issue by nepa** [oceanwp/oceanwp#17]
There is a typo in the German translation file (`de_DE.po`).

"Copywright" should be "Copyright", since there is no such word.

The correct translation would be "Urheberrecht", but in the context of this theme "Copyright" is perfectly fine. There are three occurrences in the file.

**Comment by oceanwp** [comment]
Hello, thank you, this will be fixed in the next release.

**Comment by nepa** [comment]
Nicolas, unfortunately, you only fixed one occurrence of "Copywright". But as stated in my issue, there were three occurrences of "Copywright".

Please fix the remaining two errors as well. Thank you.

**Comment by oceanwp** [comment]
Hi, you're right, I don't noticed the other one, fixed :)
