### ISSUE TITLE
Why the need to capitalize some texts?

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#170]
Hello

Something is strange in Ocean for some months now, you decided to capitalize WooCommerce tables and buttons.
It doesn't sound like a good practise for force capitalization in CSS, especially for non-english users.

Is there a possibility to make you consider removing this styling?
Thank you

![capitalize](https://user-images.githubusercontent.com/108828/54035013-9fa9bd00-41b8-11e9-8ebb-e5ff3f42e950.PNG)

**Comment by shirokoweb** [comment]
@nicomollet as a quick fix, you could use a custom CSS rule (and for everything that has no setting parameters in theme panel) :
```
/*  Remove capitalization */
.woocommerce table.shop_table td {
    text-transform: none !important;
}
```
Further more, you could completely replace theme's styling for WooC ommerce registering your own with WordPress functions : [wp_register_style()](https://codex.wordpress.org/Function_Reference/wp_register_style) & [wp_deregister_style()](https://codex.wordpress.org/Function_Reference/wp_deregister_style)

**Comment by nicomollet** [comment]
@shirokoweb Yes thank you, my request was more for a long term fix, I don't think it's standard to force capitalization.

**Comment by RajeebTheGreat** [comment]
Hi @nicomollet,

Thank you for your suggestion. This has been noted and will be addressed as soon as possible.
