### ISSUE TITLE
Support for Woocommerce Social Login in Popup Login (with code reference)

### ISSUE THREAD

**Issue by EnterpriseBranding** [oceanwp/oceanwp#173]
Hi.

This is a request to add support for the Woocommerce Social Login plugin @ [https://docs.woocommerce.com/document/woocommerce-social-login/](url)

Because there is not in a way native support, I just wrote a hook around the current hook for the Wordpress Social Login plugin. You can see I am just working around the native oceanwp hooks.

I did it with PHP in the code as well, because `do_shortcode()` was not processing the output in the popup login. All is working well this method.

```php
if (!function_exists('wsl_load_plugin_textdomain')) {

    // I'm just safely calling this function to signal to the OceanWP hook to fire, as I am not using this social login plugin

    function wsl_load_plugin_textdomain() {}
    
    // Call our OceanWP Login form hook

    add_action('opl_wp_social_login', function() {

         // Loads the Woocommerce Social Login Buttons

        if (function_exists('woocommerce_social_login_buttons')) { woocommerce_social_login_buttons(); }
        
    });

    // Call our OceanWP Register form hook
    
    add_action('opl_wp_social_register', function() {

         // Loads the Woocommerce Social Login Buttons

        if (function_exists('woocommerce_social_login_buttons')) { woocommerce_social_login_buttons(); }
        
    });

}
```

The result is as the following...

![image](https://user-images.githubusercontent.com/6123260/54574192-c8566180-49c5-11e9-91d6-7fb03f48d9bf.png)

**Comment by RajeebTheGreat** [comment]
Hi @EnterpriseBranding 

Can you please contact us through a pre-purchase form on oceanwp.org - https://oceanwp.org/pre-purchase-question/

We would need more details before the support can be added.
