### ISSUE TITLE
Core Gallery in post in not maxedwidthed

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#174]
Hello

In this example https://www.antineahotel.com/actualites/famille-saint-malo/ the core gallery div is not contained.

I had to hard code a fix:
```
.single-post.content-max-width .entry-content .gallery {
    max-width: 1200px;
    margin: 0 auto;
}
```

Can you please fix it in Ocean?
Classic editor is used FYI.
Thanks

**Comment by nicomollet** [comment]
It doesn't look like this space is managed anymore. Still there @nicolas-owp ?

**Comment by nicolas-owp** [comment]
Hi, very sorry for such a late answer, we work on many things and we forgot to check the issues here. I will add the code in the theme, thank you.
