### ISSUE TITLE
Blank/Whitescreen after migrating site. 

### ISSUE THREAD

**Issue by MarcMurrayUpfront** [oceanwp/oceanwp#179]
I've just moved the site from a local environment to a test server and am recieving the following error:

`Fatal error: Uncaught Error: Call to undefined function oceanwp_post_id() in /home/u573747/mylife-test.upfront.ie/wp-content/plugins/ocean-extra/includes/metabox/metabox.php:1893 Stack trace: #0 /home/u573747/mylife-test.upfront.ie/wp-includes/class-wp-hook.php(288): OceanWP_Post_Metabox->body_class(Array) #1 /home/u573747/mylife-test.upfront.ie/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /home/u573747/mylife-test.upfront.ie/wp-includes/post-template.php(815): apply_filters('body_class', Array, Array) #3 /home/u573747/mylife-test.upfront.ie/wp-includes/post-template.php(578): get_body_class(Array) #4 /home/u573747/mylife-test.upfront.ie/wp-content/plugins/elementor-pro/modules/theme-builder/views/theme-support-header.php(22): body_class() #5 /home/u573747/mylife-test.upfront.ie/wp-content/plugins/elementor-pro/modules/theme-builder/classes/theme-support.php(71): require('/home/u573747/m...') #6 /home/u573747/mylife-test.upfront.ie/wp-includes/class-wp-hook.php(286): ElementorPro\Modules\ThemeBuild in /home/u573747/mylife-test.upfront.ie/wp-content/plugins/ocean-extra/includes/metabox/metabox.php on line 1893`

I am using:
- Elementor
- OceanWP
- Ocean Extra
- Essential Addons for Elementor

When I de-activate ocean extra I get a header and nav loading but no body of any page, nor do the links on the nav work or go anywhere, instead going to this url:
about:blank#blocked

Any ideas as to how this has happened?

**Comment by RajeebTheGreat** [comment]
Hi @MarcMurrayUpfront ,

The error message points to a undefined function `oceanwp_post_id` which is actually present on the theme code as you can see here - https://github.com/oceanwp/oceanwp/blob/master/inc/helpers.php#L290

Please make sure you are on the latest version of the OceanWP theme.

That being said, Github issues are for reporting bugs. I'll be closing this issue. Please ask support questions on the forum - https://wordpress.org/support/theme/oceanwp/
