### ISSUE TITLE
OceanWP issue on editing

### ISSUE THREAD

**Issue by mdano123** [oceanwp/oceanwp#18]
when accessing the dashboard on my account, 
and try to edit my pages,
About me 
Contact me
, all of the wordings are all on the vertical portion.
Please check. 

![img_2199](https://user-images.githubusercontent.com/32720312/31468791-f6e012e4-af11-11e7-922b-41492c3b0060.JPG)

**Comment by oceanwp** [comment]
Hello, I will need to access your site to see what is wrong.
You have this issue only with OceanWP or also with another theme? If you have the same issue on another theme, you will need to see this with the Elementor support team.

**Comment by nicolas-owp** [comment]
Hello, having received no response from you, I assume that your issue is solved.
Feel free to answer to this topic if it is not.
