### ISSUE TITLE
Breadcrumb display both text & icon

### ISSUE THREAD

**Issue by AurelienRevault** [oceanwp/oceanwp#180]
The home item shows both icon & text. Moreover, there is an additionnal ">" after home text.
Here is the problem (website is in french home is displayed as "Accueil") :
https://www.bbgr.com/qui-sommes-nous-bbgr/

Here is a previous version using oceanwp 1.5.32, without issue
https://codeshifting.com/bbgr2/qui-sommes-nous-bbgr/

**Comment by RajeebTheGreat** [comment]
Hi @AurelienRevault,

Thank you for reporting this. Can you please mention which theme version are you using?

**Comment by AurelienRevault** [comment]
At the time of writing, it was the latest version available, I think 1.6.3.

**Comment by nicolas-owp** [comment]
Hello, it was probably just a cache issue as I only see the home icon.

**Comment by AurelienRevault** [comment]
No that is because I downgraded oceanwp to version 1.5.32 in production. At the time I looked at ocean's code and there was a diff between 1.5.32 and 1.6.3 that could explain the bug.

**Comment by nicolas-owp** [comment]
Ah okay, have you cleared your cache? Also, if you have disabled any style or script in Theme Panel > Scripts & Styles, go there and click Save Changes, then clear your cache.
