### ISSUE TITLE
Custom CSS Enqueues after Elementor Post CSS

### ISSUE THREAD

**Issue by thezenmonkey** [oceanwp/oceanwp#181]
I've noticed that the any CSS added to the customizer is enqueued after Elementor's Post specific CSS. It should load before so that it doesn't override any Post specific styling.

**Comment by fxaviers** [comment]
A similar problem is also occurring with CSS for WooCommerce. It is being inserted as "style" inside the html, which prevents customizations such as the Elementor.

![ocean](https://user-images.githubusercontent.com/17536232/56606634-0e15d380-65dd-11e9-8a11-39201fe31c7c.png)
OceanWP

---

![storefront](https://user-images.githubusercontent.com/17536232/56606654-179f3b80-65dd-11e9-9de1-69be424480b6.png)
Store Front (without style).

**Comment by RajeebTheGreat** [comment]
Hi @thezenmonkey ,

Custom CSS section is customizer is supposed to the CSS that overrides every other CSS enqueued or added on the page. That is why it is loaded after all the CSS.
