### ISSUE TITLE
Style Enhancement for Quantity selector on Firefox

### ISSUE THREAD

**Issue by shirokoweb** [oceanwp/oceanwp#183]
On Firefox, the quantity selector is displayed twice when "WooCommerce Quantity Buttons" JS is enabled (Theme Panel > Scripts & Style) :
![image](https://user-images.githubusercontent.com/6638982/55667969-7a65a880-5863-11e9-918a-1074e58cc786.png).

CSS should include :
```
.woocommerce input[type="number"] {
    -moz-appearance:textfield;
}
```
![image](https://user-images.githubusercontent.com/6638982/55668062-9c135f80-5864-11e9-9447-beaa474a1631.png)

**Comment by RajeebTheGreat** [comment]
Thank you for reporting this. This has been fixed with #cd2565f and will be included in theme update soon.
