### ISSUE TITLE
WooCommerce Archive Pages with Infinite Scroll & Lazy Load

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#188]
Hello,

I use OceanWP Infinite Scroll on my WooCommerce Archive Pages.
WP Rocket is activated with Lazy Load on Images.

On my website and for example this page (https://www.boutique-thalassotherapie.com/categorie-produit/spa/) the last scrolling page doesn't display images. Lazy Load doesn't seem to load.

Is this something related to Ocean's Infinite Scroll? Or is it WP Rocket problem?
Thank you

Ocean 1.6.7
WooCommerce 3.5.3
WP Rocket 3.3.1.1

![lazylaodbug](https://user-images.githubusercontent.com/108828/56507900-1e697800-6523-11e9-81c3-9d5d3be8487d.PNG)

**Comment by nicolas-owp** [comment]
Hi, unfortunately, we are aware of this problem but we never find a way to solve this, when infinite scroll is used with lazy load, the images act this way.

**Comment by nicomollet** [comment]
FYI I found a way to fix it.
It needs to be on WP Rocket part (which does the lazy load thing):
https://github.com/wp-media/rocket-lazyload-common/pull/36

**Comment by nicolas-owp** [comment]
Hi, very glad that this issue is fixed, thanks for giving the solution :)
