### ISSUE TITLE
Disabling "Main" Menu Assignment Impacts Social Menu in Header

### ISSUE THREAD

**Issue by andrewmarconi** [oceanwp/oceanwp#19]
## Summary:

Unassigning the "Main" menu placement impacts the visibility of the social menu in the header block above.

## How to Repeat:

- Customize > Header > General -- Set Style to "Medium"
- Make sure all three elements are visible (search box, logo, social menu)
- (Verify that the social menu is visible, obvs)
- Appearance > Menus > Uncheck the "Main" menu assignment.

##  What Happens:

- The social menu disappears in addition to the main menu.

## What Was Actually Expected:

- Only the main menu should disappear.

**Comment by oceanwp** [comment]
Hello, this is the normal behavior because the Social are in the main menu so if there is no main menu, the social cannot be there.

**Comment by andrewmarconi** [comment]
Sorry. Not sure if I wasn't clear, or if I just don't understand how the layout really exists. I have this:

[TOP BAR]
[HEADER-LEFT: searchbox] [HEADER-CENTER: logo] [HEADER-RIGHT: socialmenu]
[MAIN MENU: wp_menu_assignment]

You're saying that socialmenu is attached to the wp_menu?

**Comment by oceanwp** [comment]
I will try to fix this for the next release but yes right now the social in the header are attached to the main menu.

**Comment by andrewmarconi** [comment]
OK, thanks for such a quick resolution.

**Comment by oceanwp** [comment]
You are most welcome :)

**Comment by oceanwp** [comment]
I just updated the file, it was a small code to remove, download the theme from Github and you will see the social even if you don't have a main menu :)

**Comment by marianagomezur** [comment]
hi, i want to hide the section of social icons on the header in the Ocean WP theme but i can´t find the way to do that. Maybe you could help me, i see in this threadyou are talkink about it, do i have to choose a different menu (not the main menu) so that they won`t appear?
