### ISSUE TITLE
Single Product Page Images Scroll Too Far

### ISSUE THREAD

**Issue by DynAggelos** [oceanwp/oceanwp#190]
When you have the single product set to Full-Width in the Customizer, each successive image in the product gallery scrolls a little bit further to the right than the last, making the edges of the previous image visible. This doesn't seem to happen when I set the single product to 100% Full-Width.

Example Link: https://saffiregrills.com/product/large-platinum-grill/

**Comment by eramits** [comment]
Hello @DynAggelos,

I didn't understand it clearly. Can you please share a little video of the issue so that I can check it?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details. No similar issues were reported. Feel free to start a new thread if you're still experiencing problems on your end
