### ISSUE TITLE
breadcrumbs.php get_day_links error

### ISSUE THREAD

**Issue by sanders41** [oceanwp/oceanwp#191]
I keep getting the following error in my apache2/error.log

> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function get_day_link(), 1 passed in /var/www/html/wp-content/themes/oceanwp/inc/breadcrumbs.php on line 938 and exactly 3 expected in /var/www/html/wp-includes/link-template.php:546\nStack trace:\n#0 /var/www/html/wp-content/themes/oceanwp/inc/breadcrumbs.php(938): get_day_link('2019')\n#1 /var/www/html/wp-content/themes/oceanwp/inc/breadcrumbs.php(427): OceanWP_Breadcrumb_Trail->add_day_archive_items()\n#2 /var/www/html/wp-content/themes/oceanwp/inc/breadcrumbs.php(205): OceanWP_Breadcrumb_Trail->add_items()\n#3 /var/www/html/wp-content/themes/oceanwp/inc/breadcrumbs.php(65): OceanWP_Breadcrumb_Trail->__construct(Array)\n#4 /var/www/html/wp-content/themes/oceanwp/partials/page-header.php(62): oceanwp_breadcrumb_trail()\n#5 /var/www/html/wp-includes/template.php(724): require('/var/www/html/w...')\n#6 /var/www/html/wp-includes/template.php(671): load_template('/var/www/html/w...', false)\n#7 /var/www/html/wp-includes/general-template.php(168): locate_template(Array, t in /var/www/html/wp-includes/link-template.php on line 546

Would changing line 938 in inc/breadcrumbs.php from:
`$this->items[] = sprintf( '<a href="%s">%s</a>', esc_url( get_day_link( get_the_time( 'Y' ) ), get_the_time( 'm' ), get_the_time( 'd' ) ), $day );` 

to:

 `$this->items[] = sprintf( '<a href="%s">%s</a>', esc_url( get_day_link( get_the_time( 'Y' ), get_the_time( 'm' ), get_the_time( 'd' ) ) ), $day );` resolve this error?

**Comment by sanders41** [comment]
I tried the above change and it causes the archive page to throw a 500 error so that isn't the solution. Any other ideas to try?

**Comment by eramits** [comment]
@sanders41 Extremely sorry for the late response. This issue will be fixed with the next update of the theme  - https://developer.wordpress.org/reference/functions/get_day_link/
