### ISSUE TITLE
Breadcrumb logic fails for nested categories

### ISSUE THREAD

**Issue by weewyum** [oceanwp/oceanwp#192]
We have a site using heavily nested categories and have noticed the default breadcrumb logic cannot seem to handle this without mixing up product categories in the breadcrumb itself.

For example the following link:

https://www.tek-tanks.com/product-category/tanks/series-a-tanks/series-a-baffled-tanks/

Shows "Products>Series A Tanks>Tanks>Series A Baffled Tanks" instead of Products>Tanks>Series A Tanks>Series A Baffled Tanks.

Using woocommerce_breadcrumb() on a development site **always** displays the correct breadcrumb path. I have another site using oceanwp using hooks to change the breadcrumb back to default. Is there any reason Oceanwp chooses to not use woocommerce_breadcrumb()?

**Comment by eramits** [comment]
Hello @weewyum,

Have you updated the theme to the latest version? Can you also tell me the steps to replicate the issue?

**Comment by MarkHollo** [comment]
Due to the lack of activity, we're closing this thread for now.

If you're still experiencing this problem and believe it's a bug, please comment so that we can re-open it.

Thank you for building with OceanWP
