### ISSUE TITLE
Error in Ocean Extra plugin

### ISSUE THREAD

**Issue by krol1k** [oceanwp/oceanwp#193]
/includes/shortcodes/shortcodes.php 
line 60

get_template_part( 'partials/header/mobile-icon' );
change to 
get_template_part( 'partials/mobile/mobile-icon' );

**Comment by AlexdeBorba** [comment]
Hello @krol1k 

Can you update to the latest version of Ocean Extra and tell us if the issue still persists?

Thank you.
