### ISSUE TITLE
Topbar social links with target="_blank" should have noopener / noreferrer

### ISSUE THREAD

**Issue by antnettleship** [oceanwp/oceanwp#194]
Hiya,

Noticed an issue when running Chrome's Lighthouse audit that the social links in the top bar do not include the recommended `noopener` or `noreferrer` rel attribute when using `target: '_blank'` https://developers.google.com/web/tools/lighthouse/audits/noopener?utm_source=lighthouse&utm_medium=devtools

https://github.com/oceanwp/oceanwp/blob/f374d5658185ad951d51df500cf10e09dd1fdc25/partials/topbar/social.php#L79

https://github.com/oceanwp/oceanwp/blob/f374d5658185ad951d51df500cf10e09dd1fdc25/partials/topbar/social.php#L103

**Comment by eramits** [comment]
Hello @antnettleship,

The issue has been fixed with the theme v1.7.9. Kindly update the theme to the latest version.
