### ISSUE TITLE
iframe width:100% breaks rendering of Podlove Player embed on mobile

### ISSUE THREAD

**Issue by DanielBaulig** [oceanwp/oceanwp#195]
I am using Ocean WP as well as Podlove Player on my blog. On mobile devices the rendering of Podlove Player overflows the width of the viewport due to a iframe { width: 100% } CSS rule in Ocean WP. Removing this CSS restores the rendering and does not seem to have any negative impact on any other aspects of my setup of the theme (FWIW).

In theory I should be able to just override that CSS using custom CSS. However, it does not seem possible to restore the default iframe behavior using CSS. Setting width: default; in a more specific CSS rule does not restore the iframe behavior in such a way that the rendering bug disappears. Only entirely removing the CSS width: 100% rule seems to be doing that.

This link takes you to the Podlove Player Github where I originally reported the bug until they made me aware it's a problem introduced by a Ocean WP CSS rule:
https://github.com/podlove/podlove-web-player/issues/461#issuecomment-494246592

I had originally simply removed the CSS in my install of Ocean WP, which worked until I updated Ocean WP, which obviously nuked away those changes. I am looking for a more sustainable way to get this fixed upstream.

Possible fixes:
- Remove the width: 100% rules applied to all iframes (and objects and embeds) and apply a more specific rule to those iframes that Ocean WP actually cares about.
- Add an optional opt-out class to the rule, e.g. 

````:not(.wp-ocean-default-iframe-width) iframe { width:100%; }````

This way it's easy for an author to opt out out of the 100% rule for specific iframes or groups of iframes.

**Comment by eramits** [comment]
Hello @DanielBaulig 

Can you please tell me the steps to replicate the issue so that I can check it? I didn't see the issue with iframe and not any user reported an issue about it.
