### ISSUE TITLE
Homepage title override

### ISSUE THREAD

**Issue by Tom-V** [oceanwp/oceanwp#196]
https://github.com/oceanwp/oceanwp/blob/f374d5658185ad951d51df500cf10e09dd1fdc25/inc/helpers.php#L1937

Is there any reason why this is not just?
`$title = esc_html__( 'Recent Posts', 'oceanwp' );`
Because this is returned without passing the `apply_filters( 'ocean_title', $title )` at the end of the function, this can't easily be changed in a child theme

**Comment by eramits** [comment]
Hello @Tom-V 

We have fixed this issue and it will be included in the next update of the theme v1.8.0. Thank you for pointing on it.
