### ISSUE TITLE
Not able to add custom font

### ISSUE THREAD

**Issue by manwenick** [oceanwp/oceanwp#198]
Hello!

I bought the oceanwp bundle in the hope, that the custom fonts works. 
I followed the instructions in this video https://docs.oceanwp.org/article/128-how-to-add-custom-fonts but I can't see the added custom font in the settings. 
I use the oceanwp theme (not oceanwp child theme!) Maybe this is the problem? But in the video the font is also added in the child theme, but in the settings (end of the video) you can see that the oceanwp theme is used. 

What do I do wrong? 
Do I need to restart apache after the change of the code-snippet?

Thank you!

**Comment by eramits** [comment]
Hello @manwenick,

Have you followed the documentation to add the custom fonts? - https://docs.oceanwp.org/article/128-how-to-add-custom-fonts
