### ISSUE TITLE
Mobile menu style "sidebar" responsiveness 

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#199]
Site scaling instead of overlay as with dropdown menu style on mobile devices..

Issue details here:
https://www.facebook.com/groups/OceanWP/permalink/2404074759681996/

Thank you!

Greetings,
stefan

**Comment by AlexdeBorba** [comment]
Hello @stevek28 

Have you associated a specific mobile menu to the mobile version? If not, I strongly suggest you do so in order to avoid that long gap you have got there.
