### ISSUE TITLE
social menu lost all of css

### ISSUE THREAD

**Issue by jerzyk** [oceanwp/oceanwp#20]
OceanWP 1.4.1

after upgrade to newest theme social menus lost it's css - it is displayed as standard ul list despite what checkboxes are selected in theme panel (menu types css)

**Comment by oceanwp** [comment]
Hello, you just need to clear your cache. If you have disabled any script or style, go to Theme Panel > Scripts & Styles, click Save Changes then clear your cache, that will solve the issue :)

**Comment by jerzyk** [comment]
I would like this to be so simple, really... I've checked this (with cleaning cache) before posting this issue... in plain word: clearing cache, saving css and then cleaning cache does not help

**Comment by oceanwp** [comment]
You have updated Ocean Extra to its latest version?
Because it is just a CSS issue, logically it should work if you update your CSS file by saving in the Scripts & Styles page.

**Comment by jerzyk** [comment]
updated via wp updater to 1.4.1 (wordpress 4.8.2, rest of the ocean's plugins updated to latest versions too)

social menu is being shown as default style ul, just after logo, main menu is pushed down. on mobile and tablet, social menu is still visible - both behind logo and in hamburger menu

**Comment by jerzyk** [comment]
I've disabled all css & js saved, then switched on all, saved, then returned to initial settings (without needed ones) then theme settings - disable & re0enable social meta - and it is back
can be that there is an migration issue from 1.3.x to 1.4.x ?

**Comment by oceanwp** [comment]
Hi, it is because I have replaced the social id by a class, users just need to click on the save changes button of the Scripts & Styles page, then cleared their cache and it work as it should.
Do you use cloudflare on your site? If yes, you also need to clear its cache.

**Comment by jerzyk** [comment]
I did this (save changes button of the Scripts & Styles page) several times, but this did not bring any effect to the site, then it worked after clearing all of the options, then switching them all on - so this looks like an issue with configuration, maybe just saving - without changes - didn't update a configuration?
you know - browser is not sending any info about unchecked checkboxes...

just trying to help, to find where was (is) an issue...

**Comment by oceanwp** [comment]
The problem is that I have not touched this page :)
When I change a class as for the social menu, the CSS file generated when you click the Save Changes button on this page needs to be re-generated, so logically, user just need to click the button, I do not understand why this not working for you, maybe a little bug.
