### ISSUE TITLE
Woocommerce add to cart and remove to cart ajax  bug

### ISSUE THREAD

**Issue by franc3sc0s92** [oceanwp/oceanwp#200]
Hi, I need to resolve an oceanwp issue.
When i add or remove with ajax two or more item the sistem bug.

It do only the last ajax action. 
can you resolve?

**Comment by AlexdeBorba** [comment]
Hello @franc3sc0s92,

Which caching are you using on the server? The Varnish Cache is the common issue when it comes to handling WooCommerce Ajax interaction, such as adding products to Cart, for instance.

**Comment by AlexdeBorba** [comment]
@franc3sc0s92, can you please updated us on this Issue?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details. No similar issues were reported. Feel free to start a new thread if you're still experiencing problems on your end
