### ISSUE TITLE
404 template does't respect margins enable/disable

### ISSUE THREAD

**Issue by tinola** [oceanwp/oceanwp#201]
Hello :)

I created (using Elementor Free) template for 404 error handling in the OceanWP Theme Library and activated it in customization panel.

It doesn't matter whether "Margins" option is Enable or Disable, the top and bottom margin remains always visible.

![owp](https://user-images.githubusercontent.com/3160125/62863583-7e21a400-bd09-11e9-9ba8-40f7e8605451.png)

Regards

**Comment by AlexdeBorba** [comment]
Hello @tinola,

Have you created the 404 page using Elementor? If so, you should set the margins using the builder and see if that works for you.

Best regards

**Comment by tinola** [comment]
Hello @AlexdeBorba,

Thank you for the answer.
I double checked it. There's no margins in Elementor builder.
If I click preview-eye icon in the Elementor or click 404 page preview link in WP admin Theme Library, then everything is OK, no margins. But "outside" the Elementor or WP admin, there are still top & bottom margins (50px of height). Really don't understand why :/

**Comment by AlexdeBorba** [comment]
@tinola, can you update me on this issue, please?

**Comment by tinola** [comment]
@AlexdeBorba, how can I get you via e-mail? I'll provide you more details, screenshost, whatever you want...

**Comment by MarkHollo** [comment]
Hello @tinola,

I'm unsure whether you've reached support about this, but to clarify something out - this is not a bug, and margins are used only on the SIDES while we use top and bottom padding. If you still haven't been able to figure this out, you can reach post any (support) questions either on the [official WordPress forum](https://wordpress.org/support/theme/oceanwp/) or our [Facebook Community Support group](https://www.facebook.com/groups/OceanWP).

Please note that GitHub is for Bug and Issues report only, and we are not in the position to provide (regular) support outside of our official support channels. If you're a client, you can also open a ticket with us, and share all relevant details there.

Thank you
