### ISSUE TITLE
butterbean not defined still keeps happening

### ISSUE THREAD

**Issue by tannerchung** [oceanwp/oceanwp#202]
I've looked at all the issues from OceanWP and Elementor about this "butterbean not defined" issue and don't see a resolution in any of them in Github. They seemed to be closed, ignored, or passed on to each other.

I'm still getting the butterbean error and when checking the console and it happens when trying to edit a post with Elementor, it points to this script

```
			<script type="text/javascript">
				( function( api ) {
					if ( _.isObject( api ) && _.isFunction( api.render ) ) {
						api.render();
					}
				}( butterbean ) );
			</script>
```

What is this? How do we fix it? Can this thread be a definitive answer on what the next steps are?

![Screenshot_081219_113330_AM](https://user-images.githubusercontent.com/3707037/62877430-06497e80-bcf5-11e9-864f-dec4a912682d.jpg)

**Comment by tannerchung** [comment]
This happens when trying to edit a post with Elementor.

**Comment by eramits** [comment]
@tannerchung 

I tried to replicate this issue without any luck. Can you please tell me the steps to replicate the issue so that I can troubleshoot it?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details and inability to replicate on our end. Feel free to start a new thread if you're still experiencing problems on your end
