### ISSUE TITLE
Custom Search Page in Elementor, Cannot Hide Header

### ISSUE THREAD

**Issue by DeathStapler** [oceanwp/oceanwp#203]
Hello,

I had created a custom Search Results Page in Elementor's Theme Builder.  I followed these directions: https://docs.elementor.com/article/357-customize-the-search-results-archive

The issue is when I edit the Theme Builder - Template. In the OceanWP Settings, I set Display Page Title to Disabled, but it still displays the Page Title.  I also tried setting a background image for the Title: Background Image, but that didn't work either.

I'm using the latest version of Elementor and OceanWP Theme.

**Comment by eramits** [comment]
Hello @DeathStapler,

Are you still looking for help? GitHub issue page is only for reporting the bug of the theme and oceanwp plugins. For support, kindly open a support ticket on oceanwp support or use the OceanWP support forum on Wordpress.
