### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Elementor

### ISSUE THREAD

**Issue by stanakatik** [oceanwp/oceanwp#206]
I have not been able to use Elementor after the update. I have mentioned error in the log. I have switched to default theme twenty seventeen and Elementor works fine. Please let me know what can I do further to resolve the issue. Thanks.

PHP: 2019-08-27 07:12:36 [error X 28][/home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/includes/base/controls-stack.php::1933] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1022 and defined in /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/includes/base/controls-stack.php:1933
Stack trace:
#0 /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/includes/base/controls-stack.php(1022): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/includes/base/controls-stack.php(1775): Elementor\Controls_Stack->get_data('settings')
#2 /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings()
#3 /home3/prismits/public_html/production/sagarbrothers.in/wp-content/plugins/elementor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by eramits** [comment]
Hello @stanakatik 

Are you using the latest version of the Elementor and Ocean Elementor widget plugin?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details. No similar issues were reported. Feel free to start a new thread if you're still experiencing problems on your end
