### ISSUE TITLE
“Woo Popup” Plugin does not work

### ISSUE THREAD

**Issue by clement-menard** [oceanwp/oceanwp#207]
The plugin “Woo Popup” does not work on my website.

I thought there was an incompatibility with “YITH Booking and Appointment for WooCommerce Premium” plugin, which creates special "booking products" but i got the same problem with a standard "simple product"...

When clicking on “Add to cart”, the popup is displayed, but no product actually adds to the cart (which remains 0 products). An idea of a solution?

Exemple: Yith Booking Product (Elementor Theme builder active) : https://tinyurl.com/yyk8wl6d
Exemple: Simple Product (Elementor THeme off) : https://tinyurl.com/y4xpf988

**Comment by eramits** [comment]
Hello @clement-menard,

Please update the theme to the latest version and check it is working or not.
