### ISSUE TITLE
REQUEST: Adding "Blog Post Title" Heading

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#21]
Thank you for the amazing theme, i would like to see in a next version a Add inside the Blog Post Title.
A possibility to select the Heading value (H1,H2,H3....Hn).
Actually is fixed to H2, that is not really correct for SEO, because normally the Title of any blogPOst must be H1.
![image](https://user-images.githubusercontent.com/16102074/32116441-ea5cc568-bb4a-11e7-9fcc-ad63103fc1d3.png)

Thanks

**Comment by nicolas-owp** [comment]
Hello, you can change the heading tag in the Blog > Blog Entries section.
