### ISSUE TITLE
Categories shown on product listing grid view not constrained

### ISSUE THREAD

**Issue by thecryptodrive** [oceanwp/oceanwp#211]
![image](https://user-images.githubusercontent.com/22358264/65296443-8a2a3c80-dbb8-11e9-8067-82a27dcb267f.png)
This happens on the camera shop theme when a few categories are selected per product.

**Comment by eramits** [comment]
Hello @thecryptodrive 

This issue will be fixed with the next update of the theme. Thank you for reporting it.
