### ISSUE TITLE
Upgrade to FontAwesome 5 and issues with icon usage

### ISSUE THREAD

**Issue by therealgilles** [oceanwp/oceanwp#212]
What's the plan to upgrade to the FontAwesome 5 library?

Additionally, although I understand why some of the css was written this way, it makes it impossible to easily upgrade to FontAwesome 5 using the shim they provide:

```
From oceanwp/assets/css/woo/woocommerce.css:
.woocommerce button.button.loading:after {
  ...
  font-family: 'FontAwesome';
  ...
  content: '\f110';
  ...
}

```

**Comment by AlexdeBorba** [comment]
Hello @therealgilles 

The answer would be yes, in fact, our next update includes Font Awesome 5 support, which means that your issue will be resolved pretty soon.

**Comment by AlexdeBorba** [comment]
Hello @therealgilles 

Just to update you that we have released a new version that supports Font Awesome 5.
