### ISSUE TITLE
Product Title conflict with Oceanwp

### ISSUE THREAD

**Issue by Papersp** [oceanwp/oceanwp#213]
Hello guys, 

I am using Elementor to create a single product page (woocommerce) but as soon as the title widget text is inserted I get an error. I mean the title does not show up at all. Does anyone have a solution about this conflict with oceanwp theme? Thanks in advance!
![Screen Shot 2019-09-26 at 21 26 52](https://user-images.githubusercontent.com/50213543/65733509-7d6c8380-e0a5-11e9-97ed-0b309391df1b.png)

**Comment by eramits** [comment]
Hello,

Can you please share the product page URL so that I can check it?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details. No similar issues were reported by other Elementor users. Feel free to start a new thread if you're still experiencing problems on your end
