### ISSUE TITLE
cart added on checkout page isn’t align properly on mobile screens

### ISSUE THREAD

**Issue by radun101** [oceanwp/oceanwp#214]
hi!
thanks for this great theme! really love it.
but have a small problem.when it comes to mobile after i add the cart to checkout page it appears more than page alignment. please check this link for screenshot. - [https://imgur.com/HRS7PVt](https://imgur.com/HRS7PVt )(i got this screenshot on my mobile after zooming out the page).

Also i have installed following plugin for checkout .
[https://wordpress.org/plugins/woocommerce-direct-checkout/](https://wordpress.org/plugins/woocommerce-direct-checkout/)
and i contacted the developer of that plugin and he sent me the following statement.

"Hello
Looks like your theme is removing the default woocommerce stylesheet and replacing with a custom CSS.The CSS is missing the shop_table_responsive rules .
You should contact your theme developer to include those rules or copy and paste from the woocommerce style sheets into your site.This is how it should look like"
[
https://quadlayers.com/woocommerce-direct/](
https://quadlayers.com/woocommerce-direct/)

**Comment by eramits** [comment]
Hello @radun101 

Have you updated the theme to the latest version to check the issue? Can you please mention the steps to replicate it?

**Comment by radun101** [comment]
Hi thanks for the response. i moved to Astra theme and got there support to resolve the issue on 2019 November. thanks again.
