### ISSUE TITLE
OceanWP extensions not WPML compliant

### ISSUE THREAD

**Issue by FlyThePlanet** [oceanwp/oceanwp#215]
Hi,

The OceanWP theme is WPML compliant…
https://docs.oceanwp.org/article/438-how-turning-oceanwp-multilingual-with-wpml

But it look like all its extensions are not 🙁

Like Cookie Notice. We can’t have the notice in multiple languages.
Same for the Table widget of Ocean Elementor. Impossible to have its content translated in multiple languages.

Examples:

– Cookie Notice
We can find the string to translate in WPML > Theme and plugins localization > ocean-cookie-notice > “By continuing to use this website, you consent to the use of cookies in accordance with our Cookie Policy.” > Translations.

But despite the fact that the translation exists, it’s never displayed. I’m using the French translation and whether the visitor visits the site in French, French is set as default language or the registered user has French set as website language, the notice is always displayed in English (as set in Appearance > Customize > Cookie Notice > Content), never in French!

– Ocean Elementor Widgets
Here the translation strings are not even available.
Try to…
– Create a new page > Edit with Elementor > Add a Section
– Add the Ocean Table widget in the section > Edit the Cell Text of 1 header and 1 content cell
– Save the page
– Go to Menu > Pages > Create a language translation for the new page

You should see all the Table widget strings to translate, edited or not, but there’s nothing!

So all this makes me think that no extension is WPML compliant. OR I ended up right on the ones that are not.

Thanks to have a look.

------------------------------

Tests done on:
- WordPress 5.2.3
- OceanWP 1.7.1
- Ocean Cookie Notice 1.0.5
- Ocean Elementor Widgets 1.1.9
- Elementor 2.7.3
- php 7.1 & 7.3

**Comment by eramits** [comment]
Hello @FlyThePlanet 

We will check the issue and try to improve it with the next version of the extensions so that it can work well with WPML.

**Comment by FlyThePlanet** [comment]
@AlexdeBorba sorry but it's not an enhancement request. It's bugs to fix.
OceanWP & its extensions are supposed to be WPML compliant...

- https://docs.oceanwp.org/article/438-how-turning-oceanwp-multilingual-with-wpml
- https://wordpress.org/support/topic/oceanwp-extensions-not-wpml-compliant/#post-11945072
- https://docs.oceanwp.org/article/679-ocean-elementor-widgets-changelog (cf. 1.0.16: "Added: Compatibility with WPML for each widgets")

**Comment by MarkHollo** [comment]
Hello @FlyThePlanet,

Apologies for the delayed reply and thank you for taking the time to provide us with feedback.

Per WPML team's request, we have been waiting some new changes and a "green light" from them in regards to making OceanWP and all Ocean plugins WPML compatible. That has now been established and we'll do our best to make everything functional again so be on the lookout for new updates :)

Thank you for building with OceanWP

**Comment by FlyThePlanet** [comment]
Hi @MarkHollo ,

Thanks for your answer.
Good to know you guys are starting considering working on this major bug that makes your theme not really international.

But I'm sorry, it's not because you start considering working that the issue is closed.
1st. you start considering working (completed!)
2. you indeed work on the issue
3. you fix the issue
4. you release the fix
5. you make sure users confirm it's fixed
6. and at last, you close the ticket!
