### ISSUE TITLE
Problem with Freemius

### ISSUE THREAD

**Issue by watchpci** [oceanwp/oceanwp#216]
J'ai payé 2 licences, mais j'ai voulu les supprimer, mais impossible de se faire rembourser et annulé comme supprimer, Freemius fait la sourde oreille et n'entend rien, soit-disant 14 jours de garantie remboursement, mais à ce jour malgré le jours même de l'installation j'ai demandé de me rembourser (début septembre), je ne le suis toujours pas.
-------------------------------------------------------------------
I paid 2 licenses, but I wanted to delete them, but impossible to get reimbursed and canceled as delete, Freemius turned a deaf ear and hears nothing, so-called 14 days money back guarantee, but so far despite the days of the installation I asked to pay me back (early September), I still am not.

**Comment by AlexdeBorba** [comment]
Hello @watchpci 

I would suggest you open a support ticket so that we can take a closer look at this issue for you.

**Comment by watchpci** [comment]
J'ai utilisé les service de Paypal, sinon OceanWP n'a jamais répondu a ma requête
faire attention, depuis les service de Freemius que des soucis

**Comment by AlexdeBorba** [comment]
Hello @watchpci 

I suggest you to open a support ticket, in English, so that we can follow and reply accordingly.
