### ISSUE TITLE
Size issues with YouTube videos

### ISSUE THREAD

**Issue by FlyThePlanet** [oceanwp/oceanwp#220]
Following this ticket https://github.com/oceanwp/oceanwp/issues/120, I confirm that there's an issue with how OceanWP displays YouTube videos in posts. All the issues below don't occurs with the default Twenty Something WP themes.

If you take a YouTube video like this one...
https://www.youtube.com/watch?v=k5mcctm8Pqg

As far as I know, there are 3 ways to add it in a WordPress post:
1/ Copy/paste the video share URL in the WP post, Visual mode. In this particular case it's this URL...
`https://youtu.be/Ir7J0eEuWgk`

2/ Copy/paste the video embedding code in the WP post, Text mode. In this particular case it's this code...
`<iframe width="560" height="315" src="https://www.youtube.com/embed/k5mcctm8Pqg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

3/ Copy/paste the video website URL in the WP post, Visual mode. In this particular case it's this URL...
`https://www.youtube.com/watch?v=k5mcctm8Pqg`

Problem, once you publish and display the post...

- For the case #1, it looks like when we add the share URL in the editor in Visual mode, the URL is automatically converted into a full width player, while the editor is much wider than the future post width in the blog. But when we publish and display the post, the high height of the player is kept, the width is descaled to 100% of the post width and we end up with a square player and a video with black stripes above and below the image...
![image](https://user-images.githubusercontent.com/39710808/66835789-70360c80-ef60-11e9-8b75-6d8cc0a7ce37.png)

- For the case #2, when we add the code in the editor in text mode, then switch to Visual mode, the editor is properly displayed according to the size requested in the code (width="560" height="315"). But when we publish and display the post, once again the small height of the player is kept, the width is enlarged to 100% of the post width and we end up with a wide player and a small video with black stripes on the left and the right of the image...
![image](https://user-images.githubusercontent.com/39710808/66835741-5ac0e280-ef60-11e9-88ac-6e06488395d5.png)

- At last for the case #3, when we add the website URL in the editor in Visual mode, the URL is automatically converted into a big player, as once again the editor is much wider than the future post width in the blog. But when we publish and display the post, both height and width are proportionally descaled and that's the only case where we can end up with a normal player and video size...
![image](https://user-images.githubusercontent.com/39710808/66836162-24d02e00-ef61-11e9-9cb8-dc7b54b5b44b.png)

So the case No. 1 and 2 must be fixed.
But regarding the 2nd case, **please don't force a player at 100% width of the post. You need to respect the setting in the iframe code**.

Thanks!

-------------------------------
WordPress 5.2.4
OceanWP 1.7.1
PHP 7.1 to 7.3

**Comment by eramits** [comment]
Hello @FlyThePlanet 

We will try to improve it in the next version of the theme to fix it.

**Comment by FlyThePlanet** [comment]
Ok. Waiting.

**Comment by eramits** [comment]
I tested the issue and found that when you embed a video through a visual editor, a responsive video wrapper automatically applies to the video. The same thing is not happening when you are adding the embed code in the code editor. I hope it will clear the confusion and it is not a bug. Code Editor works like this way.

**Comment by FlyThePlanet** [comment]
What do you call a visual editor? Which visual editor?
And which type of URL are you using?

**Comment by FlyThePlanet** [comment]
*2020.03.26* - 1.8.0:
**Fixed** Huge space on YouTube video embedding.
https://docs.oceanwp.org/article/653-oceanwp-theme-changelog

I've not found any fix regarding videos in this version.

Last thing...
- Videos added via the 3 methods are all correctly displayed in the WP admin
- Videos added via the 3 methods are all correctly displayed in the Twenty Something WP themes front-end.
- But videos added via the methods #1 & #2 are not correctly displayed in the OceanWP front-end. So it's a specific bug of OceanWP.
BTW, adding a video via the "Insert/edit media" button of TinyMCE is equivalent to the method #2 and is also not working well with OceanWP (small video with black stripes on the left and the right of the image).

**Comment by eramits** [comment]
It is because when you add the video using the visual mode, OceanWP adds a responsive video wrapper while in other methods, it doesn't.

**Comment by FlyThePlanet** [comment]
Well, of course it's all about what OceanWP adds around the URL but it's not limited to one mode vs another one.
Case #1 = Visual mode & NOK
Case #2 = Text mode & NOK
Case #3 = Visual mode & OK

Look at what's the wrapper add for case #3, it may help fixing case #1 .
And for all cases, look at the wrapper added by the Twenty Something themes for each of those 3 cases and it may also help you fixing your wrappers.

**Comment by miller79** [comment]
Any further updates or workarounds for this issue?  I’m running into this as well with the latest version of Wordpress and OceanWP on PHP 7.1.
