### ISSUE TITLE
Add the controls directly on the Posts and Comments in the blog

### ISSUE THREAD

**Issue by FlyThePlanet** [oceanwp/oceanwp#221]
Hi @nicolas-owp ,

Answering my ticket of June 4 2018, you asked me to provide you with an example of my enhancement request, that you could implement for the next release.

But it seems the answer was lost afterwards, as nothing came.

So I post the enhancement request here, so that I/we can have a tracking.

The idea is to ease the work of Contributors to Admins by adding the controls directly on the Posts and Comments in the blog.
Currently, we only have the `EDIT` button on comments...
___
![image](https://user-images.githubusercontent.com/39710808/66868139-143da900-ef9d-11e9-893f-9b44885e63d3.png)
___

But why only the EDIT button?
Why only on comments?
No idea.

I suggest to add all the controls on Post and Comments, according to the user's role of course...
___
![image](https://user-images.githubusercontent.com/39710808/66868238-44854780-ef9d-11e9-8223-f2795dfc7337.png)
___
It would help a lot to save time and it should be quite easy for you to add.
Thanks!

**Comment by eramits** [comment]
Hello @FlyThePlanet,

Can you please explain the issue more? Do you want more controls on the comment section? Can you please list the controls that you want?

**Comment by FlyThePlanet** [comment]
Quick question: is Nicolas still working on OceanWP?
We exchanged on a ticket via email, he perfectly understood the request and said he will implement it.
