### ISSUE TITLE
Add a wrapper for header based on condition

### ISSUE THREAD

**Issue by gianghl1983** [oceanwp/oceanwp#223]
Hi, I have some custom header (per specific pages - transparent ones, I called them A-Type Headers) and normal header (minimal style) for the rest (Blog, Archive, Products....). How can add a wrapper class to A-Type, so I can CSS them differently from others.

I understand of changing color/ font..per specific page (Header Settings). But some element not there, such as Cart Icon, Header's border-bottom.

If I target them by CSS, it will affect all other pages (Home = transparent > So I want Cart = Green, but other pages minimal header then a black Cart...). So, if we have an option of a header wrapper...we can target individually. Currently, I must use Yellow Pencil to adjust Cart color on Homepage.

Thank you!

**Comment by eramits** [comment]
Hello @gianghl1983 

You can use the header with the class to target the header style and modify it as per your need. For minimal header style, you can use `#site-header .minimal-header`
