### ISSUE TITLE
Timeline widget > Dates not visible & inapropriate responsive view

### ISSUE THREAD

**Issue by FlyThePlanet** [oceanwp/oceanwp#224]
Hi,

There are 2 issues with the Timeline widget of the Ocean Elementor Widgets plugin.

#1 When we look at the page in Smartphone or Tablet view, the date of each entry of the timeline is not visible any more, making the timeline a line with no time!

The Timeline widget on desktop...
![image](https://user-images.githubusercontent.com/39710808/67151177-187e0500-f2c2-11e9-976b-992bf8488a3e.png)

The Timeline widget on smartphone or tablet...
![image](https://user-images.githubusercontent.com/39710808/67151179-22076d00-f2c2-11e9-80a9-b3e63c6a889f.png)

Steps to reproduce:
- WP Admin > Pages > Add New
- Set a Title > Edit with Elementor
- Drag the Timeline widget on the default section
- Edit Timeline > Content > Layout > Source > Custom Content
- Edit Timeline > Content > Additional Options > Meta > No (useless & ugly to repeat the date in desktop view)
- Switch to Tablet & Mobile view

#2 Using the responsive template with all entries on the same side for tablets is definitively inappropriate.
Please stick to the normal templates with the entries on both side of the timeline. There's far enough space on Tablet screens.

**Comment by eramits** [comment]
Hello @FlyThePlanet 

To fix this issue, we have to modify the template design completely. We will try to improve the design of the widget to make it more user friendly.

**Comment by FlyThePlanet** [comment]
> To fix this issue, we have to modify the template design completely.

Are you sure?
Even for the 2nd issue? To me you just have to change the responsive breakpoint of the tablet, that's all.

> We will try to improve the design of the widget to make it more user friendly.

I agree with the qualification of "enhancement" but then why don't you leave the ticket open?
