### ISSUE TITLE
Top bar OceanWP template in Wordpress - the  social icons are not properly

### ISSUE THREAD

**Issue by Firchester** [oceanwp/oceanwp#226]
/* Social menu */
.oceanwp-social-menu { float: left; }
.oceanwp-social-menu.simple-social { right: auto; left: -8px; }
.oceanwp-social-menu.social-with-style { right: auto; left: -2px; }
.oceanwp-social-menu ul li { float: right; }

**Comment by eramits** [comment]
Hello @Firchester 

I didn't understand the issue clearly. Can you please explain it more?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while, so closing this due to lack of details. Feel free to start a new thread if you're still experiencing issues
