### ISSUE TITLE
Ocean Extra and Elementor issue

### ISSUE THREAD

**Issue by Nickbackstrom** [oceanwp/oceanwp#229]
Hi

Ocean Extra Plugin and Elementor will not wrk together. I caught get the pro to load and when I creat a new page I get this error:

Uncaught Error: Call to undefined function op_portfolio_taxonomy() in /home/hi2oyhwt/public_html/wp-content/plugins/ocean-portfolio/ocean-portfolio.php:389
Stack trace:
#0 /home/hi2oyhwt/public_html/wp-includes/class-wp-hook.php(286): Ocean_Portfolio->display_sidebar('sidebar')
#1 /home/hi2oyhwt/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters('sidebar', Array)
#2 /home/hi2oyhwt/public_html/wp-content/themes/oceanwp/inc/helpers.php(596): apply_filters('ocean_get_sideb...', 'sidebar')
#3 /home/hi2oyhwt/public_html/wp-content/themes/oceanwp/sidebar.php(22): oceanwp_get_sidebar()
#4 /home/hi2oyhwt/public_html/wp-includes/template.php(722): require_once('/home/hi2oyhwt/...')
#5 /home/hi2oyhwt/public_html/wp-includes/template.php(671): load_template('/home/hi2oyhwt/...', true)
#6 /home/hi2oyhwt/public_html/wp-includes/general-template.php(111): locate_template(Array, true)
#7 /home/hi2oyhwt/public_html/wp-content/themes/oceanwp/inc/helpers.php(550): get_sidebar()
#8 /home/hi2oyhwt/public_html/wp-inc

Any help gratefully recieved.

**Comment by AlexdeBorba** [comment]
Hello @Nickbackstrom,

There are no known issues with Ocean Extra alongside with Elementor.

Have you updated to the latest version of Ocean Portfolio and OceanWP theme that came out a two days ago? If not, I strongly advise you to do so as well as to check if you have everything up to date.
