### ISSUE TITLE
[Feature request] [Bug] Feature suggestions & Bugs for Mobile Header, Sticky Header, Sidebar, Footer Callout, Etc.

### ISSUE THREAD

**Issue by Zunichi** [oceanwp/oceanwp#23]
Hi Nick!

Your theme is kickass! We just bought your extensions and they are absolutely worth every penny. Thanks for your efforts. Couple of feature suggestions though, in case it's not in the pipeline yet:

FEATURE REQUESTS:
* Add option to set header height in mobile
* Add option to set sticky header shrink height in mobile
* Add option to hide sidebar in mobile (global and post-specific)
* Add option to customize the Footer Callout button (such as size, padding, icon, etc.)
* Add option to add links to all fields in the Contact Info widget (currently only the email and website are given the link option). Also add an option to the map section, to add image or google maps embed. Lastly, more customization with the icons.
* Add more customization options to the widget titles (ex. hide line before text, set a different icon, etc.)
* For the Theme Buttons option in customizer, is it possible to have it so that whatever styling we set there, will override the button styling that's being set by Elementor?

BUGS:
* Some options in Typography are not being set when theme is paired with Elementor (ex. line-height for some headers, etc.)
* Setting the Top Bar paddings to "0" is not being set. It just defaults to the original value. I believe it happens for some other options as well but can't remember.

Again, thanks for the great theme!

**Comment by nicolas-owp** [comment]
Hello, thanks a lot for the nice words and these feature requests, I will take them all into account :)

For Elementor, you just need to go in the plugin settings and disable the default typography and color settings, that will take the theme typography and color instead.

For the top bar that doesn't work, I'm already aware of this bug but I don't found a solution yet, when you put 0, it is seen as null in the customizer so return the default value.

**Comment by Zunichi** [comment]
I actually had the "disable the default typography and color" settings checked. Although I realized that the line-height rule in customizer doesn't work for the H1-H4 tags in the Elementor Heading widget. It could be an Elementor issue then since that means that enabling the "disable the default typography and color" setting doesn't fully work.

**Comment by nicolas-owp** [comment]
-- Please reply above this line --

Hello,

 This is just an automated email to let you know we have received your
ticket. We will try and reply to your ticket within 24
hours (Monday-Friday) but depending on support load it may take us
longer to reply to the topic.

 Thanks!

**Comment by nicolas-owp** [comment]
A page builder plugin like Elementor can override the theme style.

**Comment by Zunichi** [comment]
I just remembered, it would also be nice to have an option to add text drop shadow to the page title.

**Comment by nicolas-owp** [comment]
Hi, things like drop shadow or hide sidebar on mobile needs to be done via a child theme, I cannot add too many options in the customizer otherwise it will be too long to load. I created two articles in the documentation to hide the sidebar globally and per post:
http://docs.oceanwp.org/article/478-hide-your-sidebar-on-mobile-globally
http://docs.oceanwp.org/article/479-hide-your-sidebar-on-mobile-per-post

**Comment by Zunichi** [comment]
Thanks.
