### ISSUE TITLE
Icons disappeared since 1.7.2

### ISSUE THREAD

**Issue by Okkx** [oceanwp/oceanwp#230]
Hello,

I noticed a new issue after updating to oceanwp 1.7.2

Arrows next to subcategories located on the left show squares on computed when resized to mobile dimension and also on mobile devices.

![192E0B68-E2E9-4687-A475-9129AEB7F458](https://user-images.githubusercontent.com/57640921/68617348-605e0980-04c7-11ea-963f-ccde537f960b.png)
![6B90A335-2895-444C-8D6E-29A6BFC73D6F](https://user-images.githubusercontent.com/57640921/68617349-605e0980-04c7-11ea-94b6-b7c07b4ea117.jpeg)

**Comment by bitojoe** [comment]
I would like to chime in and state that I'm also I'm facing this issue currently. Looking at the changelog, it appears that the oceanwp team updated to FontAwesome-5. 

Below is the full revised changelog for 1.7.2:
> ### *2019.10.30* - 1.7.2:
> * **Fixed** - Use WooCommerce product object functions.
> * **Fixed** - Updated sidr.js to latest version.
> * **Fixed** - Rank Math SEO Breadcrumb issue.
> * **Added** - Updated to FontAwesome-5 to fix the version conflict.
> * **Fixed** - Searchform compatibility with WPML.
> * **Added** - Updated version number and changelog.

I believe that OceanWP needs to update all of their stylesheets to incorporate the new font-family name.

**Comment by Okkx** [comment]
Fixed in version 1.7.3
