### ISSUE TITLE
After updating Wordpress 5.3 Version

### ISSUE THREAD

**Issue by ermradulsharma** [oceanwp/oceanwp#231]
Warning: Declaration of QuietSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in /home/frrxog7lfccb/public_html/bodega/wp-content/plugins/ocean-extra/includes/wizard/classes/QuietSkin.php on line 12
![wod](https://user-images.githubusercontent.com/15956546/68759780-5f97b580-0636-11ea-8a4b-9749b0e083f9.JPG)

**Comment by watchpci** [comment]
i confirm this error with ocean Extra 1.5.18 but after update with 1.5.19 no appaers

environment 5.3 Wordpress
Woo 3.8

wp-content/plugins/ocean-extra/includes/wizard/classes/QuietSkin.php:12
Plugin: ocean

Declaration of QuietSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args)

![Error after WP Upgrade-2019](https://user-images.githubusercontent.com/34822934/68830391-cf945300-06ab-11ea-8d1b-4a41546f389c.jpg)

**Comment by ermradulsharma** [comment]
it also up to date but still the problem occurs on my website...
![extra](https://user-images.githubusercontent.com/15956546/68834802-a213cd80-06dc-11ea-82f6-d2ef90d55889.JPG)

**Comment by AlexdeBorba** [comment]
Hello,

Please update to Ocean Extra 1.5.19, which was released one month ago, and do let us know if the issue persists while providing steps on how to reproduce it, and error logs so that we can take a closer look at it.

Regards
