### ISSUE TITLE
[1.7.3] Check in check boxes fail to load

### ISSUE THREAD

**Issue by Okkx** [oceanwp/oceanwp#232]
Hello,

I see the issue with arrows not showing in 1.7.2 version has been patched, thank you! 👍 

Unfortunately, a weird glitch is appearing with the check sign in check boxes. It displays a square when ticked (tried on Google Chrome latest version)

See the glitch below 

![check box](https://user-images.githubusercontent.com/57640921/68821039-73223b00-068d-11ea-83fc-a6bacb674e94.PNG)

A temporary fix suggested by a user on the oceanwp free support forum is to change the checkbox weight. It works but this seems like a weird fix, doesn't it ?

What is wrong in the first place ?

I tried clearing all my brower cache, so it does not appear to be related with browser cache

**Comment by watchpci** [comment]
same symptom with woocommerce 3.8 on the page final order (payment)

selection type of payment

![cata](https://user-images.githubusercontent.com/34822934/68830657-87296500-06ac-11ea-9d97-dd270fdb82b6.JPG)

**Comment by eramits** [comment]
Hello,
 
All these issues have been fixed with the v1.7.3. Please clear your cache or check the site using a different browser.

**Comment by watchpci** [comment]
Hello eramits, i not agree with you

the screenshot has realised with oceanWP Version: 1.7.3 and the navigatorlast Opera
Chrome, Firefox have the same symptoms, test also on several hosting platform, it's the same result

for your info all cache is cleared

with the Edge 16.0 browser, there are no characters

the latest versions that are provided for OceanWP are catastrophic

PS : each of my browser when closing it are set to clear the cache

**Comment by watchpci** [comment]
visit www-staging.watchpci.com and check this

**Comment by eramits** [comment]
There is no issue on my end. Many other users had the same issue but no one reported it again after the update. See the screenshot of your site - 

![img5](https://user-images.githubusercontent.com/43537450/68835492-3af71880-06de-11ea-97f7-88bd9fb89c56.PNG)

**Comment by watchpci** [comment]
how do you explain that it does not work on any of our browser and even on mobile with safari

> (all cache has been purged)

**mobile**
![IMG_7775](https://user-images.githubusercontent.com/34822934/68840929-f2326600-06c3-11ea-9d96-3907088d2c71.PNG)
**OPera**
![opera with css](https://user-images.githubusercontent.com/34822934/68840952-fcecfb00-06c3-11ea-93c1-aa4b9385aa2d.JPG)
**Firefox**
![firefox with style](https://user-images.githubusercontent.com/34822934/68840962-00808200-06c4-11ea-96cc-c2df1a1b9a12.JPG)

**even on another client computer (chrome)**
![IMG_7776](https://user-images.githubusercontent.com/34822934/68841172-679e3680-06c4-11ea-8ba1-c4bceaa86137.jpeg)

**Comment by Okkx** [comment]
Same issue on a computer that never visited the website before and with a freshly installed Firefox latest version 

![checkbox](https://user-images.githubusercontent.com/57640921/68844807-ae8f2a80-06ca-11ea-8193-3725901e6388.JPG)

I really don't think it is cache related (and I have no caching plugin on this website)

**Comment by eramits** [comment]
Please see the attached screenshot. Tested it with Firefox and Chrome - http://prntscr.com/pwx68w

**Comment by ermradulsharma** [comment]
i am also facing these issues on my website.
