### ISSUE TITLE
[bug] Mobile menu don't work with Products widget

### ISSUE THREAD

**Issue by fxaviers** [oceanwp/oceanwp#234]
When using the Elementor native "Products" widget, the mobile menu doesn't work.
However the error is not caused on all devices, Chrome desktop simulation the error is not noticed. Chrome for Android and iOS, as well as the default iOS browser, when there is a Products widget on the page, causes the menu button to be compromised.
I can privately provide a URL where the problem can be viewed.

**Comment by eramits** [comment]
Hello @fxaviers 

Can you please a support ticket on the oceanwp.org and share the site URL so that I can check the issue?

**Comment by MarkHollo** [comment]
Due to inactivity, but also because no similar issues were ever reported, I'm closing this thread for now.

If you're still experiencing this problem and do feel it's a bug, please place a new comment with more details and we'll consider reopening again.

Thank you
