### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by bobmulder** [oceanwp/oceanwp#235]
I like this theme! Because it's open source its perfect for GIT managed develoment, however the package can't be loaded using `composer require` because there is no `composer.json` file, and the package isn't registered at packagist.org.

Can this be done? This would be great!

Regards, Bob

**Comment by aksld** [comment]
Hello,

Maybe, for the moment, you can use : https://wpackagist.org/search?q=oceanwp&type=any&search= ?

**Comment by bobmulder** [comment]
I completely missed that oceanwp is added to wpackagist, @aksld! Guess the the need of a `composer.json` is gone now? :)

**Comment by AlexdeBorba** [comment]
Hello @bobmulder,

We will add this to our roadmap.

Thank you.
