### ISSUE TITLE
Page title typography in two places / confusing

### ISSUE THREAD

**Issue by ElectricFeet** [oceanwp/oceanwp#237]
Page title typography is in two places in the Customizer:
1) in **Typography > Page title** , which has _Font Family/Weight/Style/Size + Text Transform + Line Height + Letter Spacing_ and 
2) in **General options > Page title**, which has other settings related to to the page title area **_AND_** the color of the page title.

The font color settings for everything (I think) -- certainly for all other headings H1/2/3/4 -- are placed in the **Typography** section, so it is odd that the color of the page title should not be in **Typography** where all the others are.

It is also confusing because, whereas in the rest of the theme the color and font size are always together, in the case of the page title, they are separated.

For example, the footer widgets heading text and size are both under typography, even though more detailed color stuff is elsewhere. It seems to be a general principle that color and font-size are together in the settings

I recommend that the color setting for the page title be moved under **Typography > Page title**.

**Comment by ElectricFeet** [comment]
p.s. I just noticed that the **General options > Page Title Subheading** has the color setting in it, which adds even more reasoning for the **General options > Page Title** to have the color setting in it.

**Comment by eramits** [comment]
Hello @ElectricFeet 

Yes, you are correct. Typography settings don't have the color option. You need to change the color from the relative customizer settings.
