### ISSUE TITLE
Search overlay not working as designed on mobile

### ISSUE THREAD

**Issue by ElectricFeet** [oceanwp/oceanwp#238]
The search overlay is not working as designed on some window sizes, depending on the user setting of breakpoints.

## Working as designed:
Customize the mobile menu and select:
- Mobile Menu Style: _Full screen_;
- Mobile Menu Search: _checked_; and
- Breakpoints: _From 959px_.

Then size the window to any size between 767px and 959px and click the search icon. The search overlay drops down. 

## Not working:
- Now customize the mobile menu breakpoint to: _From 767px_.

With the window still sized to any size between 767px and 959px, click the search icon. The search overlay does not drop down. Or rather, it does, but it's hidden by CSS.

It looks like it's picking this up from around line 6076 of the style.css, where a media query sets the _#searchform-overlay_ to display none (with _!important_--ouch) at under 960px.

It looks like that rule should be modified, based on the user setting of when the mobile menu kicks in.

**Comment by eramits** [comment]
Hello @ElectricFeet 

Can you please share your site link so that I can check it? I tested it on my end and it is working fine.

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details and inability to replicate the issue on our end. No similar issues were reported. Feel free to start a new thread if you're still experiencing problems on your end
