### ISSUE TITLE
MegaMenu JS issue

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#239]
I've noticed that the megaMenu's can be buggy. I've set my instance of megamenu to be roughly 900px wide with 3 content columns. Sometimes this just displays as one column wide, but with content still being squashed into 3 columns.

I think i've pinpointed the issue to being within the megaMenu.js file as I recently trialled using the caching plugin PageSpeedNinja and found that if I minified the JS I always ended up with my Megamenu collapsing to one column.

I found that the PSN plugin massively improved site load times, so I'm keen to use it, but the biggest saving comes via minifying JS, thus making this untenable.

**Comment by eramits** [comment]
Hello @deebz 

Can you kindly share your site link so that I can check it? Also, mention the steps to replicate the issue.

**Comment by deebz** [comment]
Site is [https://www.baizewoolfabrics.co.uk](url) replicating the issue is tricky. I noticed it mostly when I've moved the mouse to the menu, before the rest of the page has fully loaded.

I've just tried now and haven't been able to replicate myself. Though I did just updated the ocean extra plugin? What I have noticed just now is that there's a focus line appearing around menu items that are non-clickable if they are clicked.
<img width="311" alt="mega-menu" src="https://user-images.githubusercontent.com/462011/77633634-a92ed000-6f47-11ea-9bce-919c102424aa.png">

**Comment by deebz** [comment]
Version 3.1.0 has a new issue with the menu. When installed all megamenu submenu's disappear until hover over where they should be. Also the animation for the megamenu drop down is from the side rather than down.

**Comment by MarkHollo** [comment]
Hello @deebz,

Thank you for constantly reporting problems to us and helping us make OceanWP better for everyone. We'd like you to know that we read all your threads even if we don't respond to them immediately, we definitely check everything you report as we consider you one of our own :)

This problem has been resolved so we'll close this thread, but in case you notice anything else, we count on you :)

Happy New Year and Happy Holidays on behalf of the entire OceanWP team
