### ISSUE TITLE
Grey box display on hover of 2 elements on my menu with Edge and Safari

### ISSUE THREAD

**Issue by alex74960** [oceanwp/oceanwp#240]
Hello,

I have a little problem with [the menu of my website ](https://lepupdechaine.com/)on some browsers.
Indeed, with Safari and Edge, a grey box diplay when I hover two item on my menu. 
This elements are “association” and “revue”. On the element “association”, the sub elements have this display bug.

I have inspect the code with the console on this different browsers and I don’t found anything of strange.
I don’t know where came from this problem.

Can you help me to solve it please?

My WordPress version is 5.3.2 and I use Ocean WP Sticky Header for my menu.

Thanks so much!

The website where I need help:

[https://lepupdechaine.com/](https://lepupdechaine.com/)

Screenshots of the problem:

[Screen 1](https://i.imgur.com/t7HRBne.png)
[Screen 2](https://i.imgur.com/bvQXuix.png)
[Screen 3](https://i.imgur.com/2HIqEmt.jpg)

**Comment by alex74960** [comment]
> Hello,
> 
> I have a little problem with [the menu of my website ](https://lepupdechaine.com/)on some browsers.
> Indeed, with Safari and Edge, a grey box diplay when I hover two item on my menu.
> This elements are “association” and “revue”. On the element “association”, the sub elements have this display bug.
> 
> I have inspect the code with the console on this different browsers and I don’t found anything of strange.
> I don’t know where came from this problem.
> 
> Can you help me to solve it please?
> 
> My WordPress version is 5.3.2 and I use Ocean WP Sticky Header for my menu.
> 
> Thanks so much!
> 
> The website where I need help:
> 
> https://lepupdechaine.com/
> 
> Screenshots of the problem :
> 
> [Screen 1](https://i.imgur.com/t7HRBne.png)
> [Screen 2](https://i.imgur.com/bvQXuix.png)
> [Screen 3](https://i.imgur.com/2HIqEmt.jpg)

**Comment by eramits** [comment]
Hello @alex74960 

I didn't see any issue on your site. Do you still have it or know the steps to replicate it?

**Comment by alex74960** [comment]
Hello @eramits 

No I still have the issue. The issue is only on Safari and Edge. 
It appears when we keep the mouse on the item.

**Comment by eramits** [comment]
It is happening but only for those menu items that have title attributes. Try to remove it or follow this link for a workaround - https://stackoverflow.com/questions/15364063/is-it-possible-to-hide-the-title-from-a-link-with-css
