### ISSUE TITLE
Bug report: OceanWP javascripts won’t execute on fast pages

### ISSUE THREAD

**Issue by Peroks-01** [oceanwp/oceanwp#241]
OceanWP’s main javascript functions (main.min.js) are attached using the deprecated

`$(document).on("ready", handler)`

instead of

`$(document).ready(handler)`

[The jQuery documentation says:](https://api.jquery.com/ready/)

> There is also $(document).on( “ready”, handler ), deprecated as of jQuery 1.8 and removed in jQuery 3.0. Note that if the DOM becomes ready **before** this event is attached, the handler will **not** be executed.

When optimizing your OceanWP site for speed – which is extremely important for SEO reasons – this is exactly what happens: OceanWP functions are not attached in time and none of the OceanWP main javascript functions are executed. So, currently OceanWP actually prevents you from speeding up your website.

Fortunately, there is a very simple fix to this bug: Just replace the deprecated `$(document).on("ready", handler)` with `$(document).ready(handler)`. This will btw also remove the jQuery Migrate warnings in the javascript Console.

**Comment by eramits** [comment]
Hello @Peroks-01 

Thank you for reporting this issue. We will try to improve it in the next update of the theme.

**Comment by MarkHollo** [comment]
Resolved with 1.8.3 version
