### ISSUE TITLE
ocean wp issue

### ISSUE THREAD

**Issue by subodh1821** [oceanwp/oceanwp#245]
Hi,

my site is not working since morning and when i have checked so it comes that my theme is creating a problem and shows.

PHP Fatal error: Call to undefined function oceanwp_html_classes() in /home/yourloan/public_html/wp-content/themes/oceanwp/header.php on line 9.

so kindly help me with same

**Comment by eramits** [comment]
Hello @subodh1821 ,

Can you share your site link? Are you using the child theme?

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while, so closing this due to lack of details. No similar issues have been reported. Feel free to start a new thread if you're still experiencing problems on your end
