### ISSUE TITLE
OceanWP 1.7.4 / Ocean Elementor Widgets - Fatal Error

### ISSUE THREAD

**Issue by PorterBytes** [oceanwp/oceanwp#246]
I have a client that is getting a 500 internal server error since updating to 1.7.4. It is also possible the Ocean Elementor Widgets plugin was updated as well, but the dates for the former align better with our report.

Disabling the Ocean Elementor Widgets plugin removes the 500 error, but It's also possible functionality of that plugin is hooked into the theme, and given the stack below, it's hard to tell if the theme or plugin is the culprit.

Memory limit is 256MB, so no issue there.

The logs are as follows:

`Uncaught Error: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /nas/content/live/comealive/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1023 in /nas/content/live/comealive/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1913
sanitize_settings()
wp-content/plugins/elementor/includes/base/controls-stack.php:1023
get_data()
wp-content/plugins/elementor/includes/base/controls-stack.php:1776
get_init_settings()
wp-content/plugins/elementor/core/base/base-object.php:132
ensure_settings()
wp-content/plugins/elementor/core/base/base-object.php:40
get_settings()
wp-content/plugins/ocean-elementor-widgets/modules/button-effects/widgets/button-effects.php:35
get_style_depends()
wp-content/plugins/elementor/includes/base/element-base.php:183
enqueue_styles()
wp-content/plugins/elementor/includes/managers/widgets.php:437
enqueue_widgets_styles()
wp-content/plugins/elementor/includes/preview.php:185
enqueue_styles()
wp-content/plugins/elementor/includes/preview.php:71
Elementor\{closure}()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/class-wp-hook.php:312
do_action()
wp-includes/plugin.php:478
do_action()
wp-includes/script-loader.php:2670
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:288
apply_filters()
wp-includes/class-wp-hook.php:312
do_action()
wp-includes/plugin.php:478
do_action()
wp-includes/general-template.php:2879
wp_head()
wp-content/themes/oceanwp/header.php:14
require_once()
wp-includes/template.php:722
load_template()
wp-includes/template.php:671
locate_template()
wp-includes/general-template.php:41
get_header()
wp-content/themes/oceanwp/page.php:12
include()
wp-includes/template-loader.php:98
require_once()
wp-blog-header.php:19
require()
index.php:17
There has been a critical error on your website.`

**Comment by MarkHollo** [comment]
Hello @PorterBytes,

1.7.4 OceanWP theme update is not relevant to Ocean Elementor Widgets at all. What version of OEW are you using? PHP version? Is your client getting the 500 error when he wants to use the Elementor editor or on the entire website?

Also, make sure you are running PHP 7+ (except for 7.4 for now), and that Ocean Extra is also up to date 1.5.20, OEW 1.2.0, as well as WordPress 5.3.2

Memory limit could be an issue if you are running an eCommerce site and using Jetpack, so increasing to 512M would be preferable.

If you have already checked all these, and everything meets the conditions, check for a possible plugin conflict. Disable all non-Ocean plugins one by one, and check the editor/site after disabling each by refreshing the page

**Comment by PorterBytes** [comment]
@MarkHollo 

The 500 error only exists when going into a page (this site has no "posts"), and clicking the "Edit with Elementor" button in the editor. It begins to load, appears to even complete actually (the progress bar at the top), and then the error is displayed.

![image](https://user-images.githubusercontent.com/1664812/72263217-759a0600-35e6-11ea-8beb-afe5c855098c.png)

I've tried disabling plugins 1 by 1, and the only plugin that's made a difference thus far, is disabling Ocean Elementor Widgets. That said, Ocean Extra is 1.5.20, Wordpress up to date, PHP on 7.2, but the Ocean Elementor Widget plugin is on 1.1.3. I'm hoping that's it, as again, disabling that fixes the issue. For whatever reason, that plugin shows as up to date, though working on a client site, so not sure how everything is set up. 

Checking the site now, to see what the deal is there.

**Comment by PorterBytes** [comment]
Just wanted to report back, that the outdated Ocean Elementor Widget Add-On plugin was the cause of the issue. Since the admin didn't tell me it was out of date, I never even though to check. Other paid plugins I use, such as Advanced Custom Fields, tell me when I'm out of date, even if the license key isn't input. I don't know what systems are in place, or what I may have missed, but consider this route if possible.

As for how this happened - the client decided not to host with us, so it's likely they lost their activation key between migration. Not knowing any better, and with the admin area not saying it was out of date, it slowly fell behind, until eventually creating an error.

All in all, issue fixed. I appreciate you responding over the weekend with thorough information, much appreciated!
