### ISSUE TITLE
Quantity buttons not counting properly

### ISSUE THREAD

**Issue by david-strejc** [oceanwp/oceanwp#247]
I got OceanWP + plugin for decimal values in quantity fields in WooCommerce.

When I am adding or distracting values - I got value converted to 12 decimals like:

11.530000000000001 - instead of 11.53 

I've identified and hotfixed javascript code:

I am not familiar enough with Javascript and I was not able to find out why is parseFloat sometime giving valuje with 12 decimals.

`wp-content/themes/oceanwp/assets/js/third/woo/devs/wooQuantityButtons.js`

I've hotfixed it with toFixed(2) - which in my case is enough decimals

` 
var value = $currentQuantity + parseFloat( $step );
$quantityBox.val(value.toFixed(2));
`

**Comment by eramits** [comment]
Hello @david-strejc 

Thank you for reporting the issue. We will fix it in the next update of the theme.
