### ISSUE TITLE
Parallax Footer Issue

### ISSUE THREAD

**Issue by andrefff** [oceanwp/oceanwp#25]
Hello! I'm using the Megagym demo.
When I turn on the parallax effect of the footer widget, the background color of the site turns white, even when I change the color of the background, nothing happens.

**Comment by nicolas-owp** [comment]
Hello, thank you for pointing this issue, it will be fixed for the next release :)

**Comment by andrefff** [comment]
Nice Nicolas! 
Do I have to reinstall the theme? or it will update automatically?

**Comment by nicolas-owp** [comment]
Hi, no, no need to reinstall it, you will have a update notification in your dashboard when I will release the new version :)

**Comment by andrefff** [comment]
Awesome, you are the best!

**Comment by nicolas-owp** [comment]
You're welcome :)
