### ISSUE TITLE
Unable to Upload Logo 

### ISSUE THREAD

**Issue by k16cuny** [oceanwp/oceanwp#250]
my OceanWP version is 1.7.4 

Appearance --> Customize --> Header --> Logo --> Select Logo

When selecting an image file in Media Library and clicking on SELECT, it just hangs on Crop Image window and it's all big blank page. Nothing happens when clicking on SELECT button repeatedly. See screenshot. 

![image](https://user-images.githubusercontent.com/46762514/72832918-c3041c00-3c53-11ea-8921-4319fd3abb5d.png)

**Comment by eramits** [comment]
Hello,

Try to disable other plugins one by one to check for a possible conflict. I checked the issue on my end but don't have the same.

**Comment by k16cuny** [comment]
> Hello,
> 
> Try to disable other plugins one by one to check for a possible conflict. I checked the issue on my end but don't have the same.

I should have thought of that in the first place. I did what you suggested and it turns out that the plugin - "Enhanced Media Library" is causing the problem. Thank you!
