### ISSUE TITLE
Attibute Archives dont work result count

### ISSUE THREAD

**Issue by marcofrasson** [oceanwp/oceanwp#252]
The attributes of WooCommerce have the possibility to activate archives or not. The default is no, but when activated, OceanWP does not recognize the result count.

See this attribute page with 600 products, without result count: https://bit.ly/3aPZoXg

And this category with 700 products and with correct result count: https://bit.ly/37D0SCj

**Comment by marcofrasson** [comment]
Any feedback?

**Comment by marcofrasson** [comment]
@eramits They asked to report the bug here, but with no return. What do I need to do?

**Comment by eramits** [comment]
Hello @marcofrasson, 

The 'result count' doesn't work with the attributes. Can you share a screenshot of the error if I'm missing your question?

**Comment by marcofrasson** [comment]
I passed the links, it doesn't work ???

**Comment by eramits** [comment]
Hello @marcofrasson 

We are working on to improve the theme and will try to fix this issue on the next update of the theme.

**Comment by eramits** [comment]
@marcofrasson 

This issue has been fixed with theme version 1.8.2.
