### ISSUE TITLE
fullscreen header fails

### ISSUE THREAD

**Issue by Antriel** [oceanwp/oceanwp#253]
Using the latest version. Seems like the line 1699 shouldn't be commented.
https://github.com/oceanwp/oceanwp/blob/master/inc/helpers.php#L1700

The issue isn't visible in the admin editor preview, but once fullscreen header setting is applied, any standard page load errors.

Uncaught Error: Call to undefined function is_plugin_active() in /home/vq015200/www/wp-content/themes/oceanwp/inc/helpers.php:1700

  | Stack trace:
  | 0 www/wp-includes/class-wp-hook.php(288): oceanwp_add_search_to_menu('&lt;li id=&quot;menu-it...', Object(stdClass))
  | 1 www/wp-includes/plugin.php(206): WP_Hook-&gt;apply_filters('&lt;li id=&quot;menu-it...', Array)
  | 2 www/wp-includes/nav-menu-template.php(247): apply_filters('wp_nav_menu_ite...', '&lt;li id=&quot;menu-it...', Object(stdClass))
  | 3 www/wp-content/themes/oceanwp/partials/header/nav.php(155): wp_nav_menu(Object(stdClass))
  | 4 www/wp-includes/template.php(724): require('/home/vq015200/...')
  | 5 www/wp-includes/template.php(671): load_template('/home/vq015200/...', false)
  | 6 www/wp-includes/general-template.php(168): locate_template(Array, true, false)

**Comment by eramits** [comment]
Hi @Antriel,

This issue will be fixed with the next update of the OceanWP theme (v1.7.5).
