### ISSUE TITLE
Page Title Background Image Doesn't Load

### ISSUE THREAD

**Issue by emlaIT** [oceanwp/oceanwp#254]
I'm using a different background image for the page title on each page but when I change pages the background image doesn't change. If I hit Shift+F5 sometimes it changes but not all the time. The images are all below 200KB and the issue happens with caching on and off (I disabled W3 Cache in order to test) and is the same in a private browser.
The site is https://chateaulanguedoc.com.

**Comment by eramits** [comment]
Hello,

I checked your site and the images are loading fine.
