### ISSUE TITLE
Elementor styling for WooCommerce Products Archives and Archive Products widgets unaffected

### ISSUE THREAD

**Issue by nickmadedesign** [oceanwp/oceanwp#257]
Hello,

The styling for the WooCommerce Products Archives and Archive Products widgets are not applying for a lot of the elements — Image, Title, etc.

![oceanwp-elementor-woocommerce-1-min](https://user-images.githubusercontent.com/40440324/75097216-14b30580-5576-11ea-8a27-56ae9d69341d.gif)

Deactivating OceanWP and activating TwentyTwenty fixes the issue (as discovered by Elementor support).

I can supply credentials to login to the test site directly, if need be.

**Specs**
OceanWP v1.7.5
OceanWP Extra v1.5.20
WordPress v5.3.2
Elementor v2.9.2
Elementor Pro v2.8.4

Thanks!

**Comment by eramits** [comment]
Hello @nickmadedesign,

Can you please open a ticket on oceanwp support and share the login details so that I can check the issue?

**Comment by nickmadedesign** [comment]
Hi @eramits 

I haven't purchased an extension or bundle yet, so I can't use the support ticket system on the OceanWP site. 


I can add it on WordPress.org but is there a method for supplying credentials privately?

Thanks!

**Comment by eramits** [comment]
You can open a pre-purchase ticket from the oceanwp.org site. Don't forget to link the GitHub issue page. 

Use this link - https://oceanwp.org/pre-purchase-question/
