### ISSUE TITLE
Mini Cart Thumbnail Size

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#258]
Probably more of a feature request rather than a bug. Decoupling the aspect ratio used for the product archive pages from the minicart/basket dropdown.

Minicart thumbnail looks off if it isn't set to 1:1 - is there a workaround I can override in code to the $thumbnail so that it pulls the square version?

Cheers

**Comment by eramits** [comment]
Hello @deebz 

Can you share a site link so that I can check the issue? Also, add a screenshot of the issue.

**Comment by deebz** [comment]
Hi,
The site isn't live yet, still working on it locally. Screenshot attached of the minibasket.

<img width="350" alt="mini-basket" src="https://user-images.githubusercontent.com/462011/77632484-f6aa3d80-6f45-11ea-9422-3fbee6ebffb0.png">

**Comment by eramits** [comment]
Hello,

Can you please share a working site link where I can see it?

**Comment by deebz** [comment]
hi,

Sorry for the long delay in responding. I am still working on the site locally, so don't have it up on a live web server currently

**Comment by MarkHollo** [comment]
Due to lack of inactivity, I'm closing this thread for now.

If you feel this feature enhancement is important and have more details to share, please comment and we'll consider re-opening it again.

Thank you for taking the time to share your ideas with us and thank you for building with OceanWP
