### ISSUE TITLE
Product links are not avalible on the Order page if Woocommerce setting "Hide out of stock items from the catalog" is active

### ISSUE THREAD

**Issue by ashomokdev** [oceanwp/oceanwp#259]
The issue is: Product links are not avalible on the Order page if Woocommerce setting "Hide out of stock items from the catalog" is active.
Expected behavior: Product links are avalible on the Order page independently of the "Hide out of stock items from the catalog" setting.

**Comment by eramits** [comment]
Hello @ashomokdev,

Can you please tell me the steps to replicate the issue?

**Comment by ashomokdev** [comment]
Sure.
1. Create test order on Woocommerce + Ocean WP site.
2. Go to My account->Orders- Order details
3. Check products links (a hrev) - it works.

4. Go to WP admin console->Woocommerce->Settings->Products->Inventory->Out of stock visibility->put checkmark to Hide out of stock items from the catalog.
5. Go to your site ->My account->Orders-> Order details
6. Check products links (a hrev) - it NOT works.

It will be good to have links works because user want to have acces to the full data of his purchase. 
Links visibility should not depends on 'Hide out of stock items from the catalog' setting.

**Comment by eramits** [comment]
Hello @ktchan1811

We were not very active on the Github issue page but now we will check it regularly. Regarding the issue, I tested it on my end but don't have the same issue. If you are still looking for a solution, kindly share a screenshot.
