### ISSUE TITLE
Previous versions

### ISSUE THREAD

**Issue by marcos-alexandre82** [oceanwp/oceanwp#260]
I'm working on a project that uses version 1.6.7 and modifications were made directly to the theme by the previous developer, without creating a child theme.

Where can I download version 1.6.7 so that I can diff them and more easily identify what changes have been made?

Tks

**Comment by AlexdeBorba** [comment]
Hello @marcos-alexandre82 

You can download previous versions of our theme through [WordPress SVN](https://themes.svn.wordpress.org/oceanwp/).

I hope this helps.

**Comment by marcos-alexandre82** [comment]
Tks @AlexdeBorba ;)
