### ISSUE TITLE
Cannot remove actions

### ISSUE THREAD

**Issue by bobmulder** [oceanwp/oceanwp#263]
Hi there,

in order to make my webshop using Elementor and Yoast SEO working together I need to remove the action added here: https://github.com/oceanwp/oceanwp/blob/master/inc/woocommerce/woocommerce-config.php#L184.

Because the class is initiated without assigning it to a global variable (none at all) at https://github.com/oceanwp/oceanwp/blob/master/inc/woocommerce/woocommerce-config.php#L2395 I am not able to `remove_action` this method.

Can you assign this class to a global variable to make it possible to remove this action?

**Comment by eramits** [comment]
Hello @bobmulder 

I'll try to improve it in the next update of the OceanWP theme.

**Comment by bobmulder** [comment]
That's great, @eramits! Thank you and good luck 😊
