### ISSUE TITLE
Top Bar > Social Icons > Email sets "mailto:http://"

### ISSUE THREAD

**Issue by AviramV** [oceanwp/oceanwp#264]
This creates an unusable email link that looks like this:
mailto:http://example@example.com

Please remove "http://" from the created link.

**Comment by LITUATUI** [comment]
I have this problem too.

**Comment by MarkHollo** [comment]
Hello @AviramV and @LITUATUI,

Thanks for reaching out and apologies for the inconvenience. This was actually my mistake when I was working on Accessibility Improvements, so sincere apologies once again. It will be resolved with the next update. 

In the meantime, you can edit the files and replace (only for Skype and Email options) `$esc_url` with `esc_attr( $url )` in **partials/topbar/social.php** and **partials/header/social.php** or if you need any help with that, please let me know.

Have a wonderful week

**Comment by AviramV** [comment]
Hi @MarkHollo,
Thanks for your reply and the suggested fix -- works great :)

Have a safe and healthy week!

**Comment by eramits** [comment]
Hello,

This issue will be fixed with the theme version 1.8.3.
