### ISSUE TITLE
'Uncaught ReferenceError: Cookies is not defined' caused by woo-scripts.min.js

### ISSUE THREAD

**Issue by valdrinkoshi** [oceanwp/oceanwp#265]
`Uncaught ReferenceError: Cookies is not defined` error is originated by woo-scripts.min.js. After some investigation, it looks like wooGridList.js uses the [js-cookie API](https://github.com/js-cookie/js-cookie) 

https://github.com/oceanwp/oceanwp/blob/f374d5658185ad951d51df500cf10e09dd1fdc25/assets/js/third/woo/devs/wooGridList.js#L33

but this dependency is not included in the woo-scripts.min.js dependencies
https://github.com/oceanwp/oceanwp/blob/8eb4428f4a50f349451e5400b50a1014d1087f84/functions.php#L468

This error happens in the homepage of the website, where no woocommerce frontend plugins/widgets are used (hence their js-cookie dependency won't be loaded "for free")

**Comment by eramits** [comment]
Hello @valdrinkoshi 

This issue will be fixed with the theme v1.8.3.
