### ISSUE TITLE
Duplicate Menu Options

### ISSUE THREAD

**Issue by hirenshah** [oceanwp/oceanwp#266]
Does anyone else have these menu settings duplicated for all existing and new menu items?

https://i.imgur.com/a0Rc7nj.png

**Comment by NasKadir123** [comment]
> Does anyone else have these menu settings duplicated for all existing and new menu items?
> 
> https://i.imgur.com/a0Rc7nj.png

Me too, it's because of new Wordpress version 5.4.
You can see this issue here https://core.trac.wordpress.org/ticket/49500.

**Comment by eramits** [comment]
Hello @hirenshah and @NasKadir123 

This issue will be fixed with the next version 1.8.3. 

Thank you
