### ISSUE TITLE
Templates saved with Elementor not showing up in Footer Widget section

### ISSUE THREAD

**Issue by bobbzeen** [oceanwp/oceanwp#267]
When I create a template using the Elementor, I cannot see the saved and published template in Footer Widget drop down menu. Also, I have a couple of templates that have been created a few months ago. When I modify them and save the modifications, the changes are not being shown on the website.

**Comment by eramits** [comment]
Hello @bobbzeen 

Try to follow the link for a fix - https://docs.oceanwp.org/article/600-how-to-create-a-custom-footer

For support related queries, please go to the OceanWP Facebook group/Wordpress support forum page or open a ticket at the oceanwp.org.

Thank you
