### ISSUE TITLE
The problem of masonry layout images overlapping!

### ISSUE THREAD

**Issue by mfa95** [oceanwp/oceanwp#268]
hi, the oceanwp theme is great! i like it. There is an important problem for me. Have you noticed the problem with the masonry layout layout? The new images in infinite scroll start from the top of the page. The pictures are intertwined first, then correct. It doesn't act like a block, it acts like a ghost. This is the site address, please check [Arkaplanlar.com](https://arkaplanlar.com) . Open the page and scroll down. you will see the pictures intermingle. please watch in slow motion. I also looked at the demos on the official site, they also have a problem. have I been able to express myself? (sorry for my english. i'm using translate.)

**Comment by eramits** [comment]
Hello @mfa95 

I tested the issue but didn't see it on my local test site.

**Comment by MarkHollo** [comment]
We haven't heard back from you in a while. Closing this due to lack of details and inability to replicate the issue on our end. No similar issues were reported. Feel free to start a new thread if you're still experiencing problems on your end
