### ISSUE TITLE
Offcanvas filter and  order by alignment in mobile view in oceanwp theme

### ISSUE THREAD

**Issue by Madhuraj971** [oceanwp/oceanwp#269]
Hii, 
in my site i have used ocean wp theme, the off canvas filter in tablet and desktop mode looks ok but in mobile modeoffcanvas button and sort by button  it is not side by side,  it is going above the sort button. please let me know how to do it.
site link: [(https://www.vavsy.com/?product_cat=best-selling)]

![7550b05d-d524-46b5-96f0-f9df130d0019](https://user-images.githubusercontent.com/63596235/79126346-62e9c580-7dbd-11ea-87b6-e3ede90c10f9.jpg)
![2afe289e-28d2-41d2-9812-5001ba0fff86](https://user-images.githubusercontent.com/63596235/79126356-65e4b600-7dbd-11ea-8fbe-de3e96d13e28.jpg)
![86fab74e-dbb5-4934-bd18-7f68f8576545](https://user-images.githubusercontent.com/63596235/79126358-667d4c80-7dbd-11ea-97a9-885c8a423e9c.jpg)

**Comment by eramits** [comment]
Hello @Madhuraj971 

For support related queries, please go to the OceanWP Facebook group/Wordpress support forum page or open a ticket at the oceanwp.org.

I also checked your site but you are not using the OceanWP theme. You can fix the issue with some css code.
