### ISSUE TITLE
oceanWP hooks conflict with elementor 

### ISSUE THREAD

**Issue by prodrigovieira** [oceanwp/oceanwp#27]
I would like to use a custom header and footer for my site using the elementor or oceanWP library.

The problem is that when I change the header of my site using OceanWP library, the elementor does not load, it is stopped in the loading screen with the logo.

If I use hooks it also conflicts. This is all updated, I'm using the latest version of elementor and elementor pro, and also the latest version of OceanWP and oceanExtras.

If I use the standard OceanWP header conflict does not happen, the elementor loader page works normally, the problem is when I add hooks or change the header.

Existe alguma solução ?

here is a video with the problem: [https://www.youtube.com/watch?v=NXWgxvy6MK0&feature=youtu.be](url)

Thank you!

**Comment by nicolas-owp** [comment]
Hello, what is your PHP version?
Also, have you reached the Elementor support team? Maybe they know what causes this issue and will give you a solution.

**Comment by nicolas-owp** [comment]
Hello, having no answers from you, I assume that you found a solution to fix this problem so I close this topic.

Feel free to answer if you still need help with it.

**Comment by Jean-Gabriel1982** [comment]
Bonjour, à priori tout fonctionne bien pour le moment le problème n’est pas revenu.

Je me permettrai de revenir vers vous si cela se manifeste encore ;-)

Un grand merci encore pour votre aide rapide !!

—-
Cordialement,
Jean Gabriel GILLARD

Le 8 janv. 2018 à 17:18, Nicolas Lecocq <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello, having no answers from you, I assume that you found a solution to fix this problem so I close this topic.

Feel free to answer if you still need help with it.

**Comment by nicolas-owp** [comment]
De rien :)
Oui n'hésitez pas à me re-contacter.
