### ISSUE TITLE
How to hide woo-floating-bar

### ISSUE THREAD

**Issue by Penny27** [oceanwp/oceanwp#270]
Hi, 

I'm working on a site using OceanWP free version but I have a problem to hide the woocommerce floating bar.

Can you help me to hide/remove it?

example on: https://www.ortovivai.com/prodotto/kasam/
![1](https://user-images.githubusercontent.com/63616138/79164046-82deb080-7de0-11ea-9e03-8517508d23ca.png)

Waiting for news
Thanks

**Comment by eramits** [comment]
Hello @Penny27 

For support related queries, please go to the OceanWP Facebook group/Wordpress support forum page or open a ticket at the oceanwp.org. 

To disable the floating bar, kindly go to Customize > Woocommerce > Single Product section and disable it. 

Thank you
