### ISSUE TITLE
Calling undefined function in header.php in line 19

### ISSUE THREAD

**Issue by abdelgayoom** [oceanwp/oceanwp#273]
after updating the theme  it's bring error saying undefined function in header.php in line 19 then I went in the header.php and and delete 
~~~~
<?php wp_body_open(); ?>
~~~~
after I delete the called function it work fine

**Comment by eramits** [comment]
Hello @abdelgayoom,

Backward compatibility for wp_body_open() will be added on theme version 1.8.3. 

Thank you
