### ISSUE TITLE
Problème récurent d'apparence du site

### ISSUE THREAD

**Issue by Jean-Gabriel1982** [oceanwp/oceanwp#28]
Bonjour,
J'ai régulièrement des soucis d'apparence de mon site fait avec OceanWP. J'aime énormément OceanWP, mais de temps en temps, assez régulièrement, lorsque j'ouvre mon site, j'obtiens une apparence plutôt embêtante ..

![capture](https://user-images.githubusercontent.com/20370038/34604622-d2e7dc52-f208-11e7-8628-7c7fa1b954ab.png)

La présentation "normale" devrait être ainsi 

![capture2](https://user-images.githubusercontent.com/20370038/34604736-361f3d9c-f209-11e7-92e8-275e82939aca.png)

Je ne suis pas expert en code, css et autres, merci de votre aide !
Cordialement, Jean-Gabriel

**Comment by nicolas-owp** [comment]
Bonjour, allez dans Theme Panel > Scripts & Styles et activez tous les scripts et styles, cela devrait résoudre le problème.
Sur certain serveur cette fonctionnalité fonctionne mal.

**Comment by Jean-Gabriel1982** [comment]
Bonjour un grand merci ! J’avais juste désactivé la feuille css de la barre supérieure. A priori ça a l’air de refonctionner :-)

—-
Cordialement,
Jean Gabriel GILLARD

Le 5 janv. 2018 à 15:42, Nicolas Lecocq <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour, allez dans Theme Panel > Scripts & Styles et activez tous les scripts et styles, cela devrait résoudre le problème.
Sur certain serveur cette fonctionnalité fonctionne mal.

**Comment by nicolas-owp** [comment]
De rien :)
