### ISSUE TITLE
Layout Error after 1.8.4 Update

### ISSUE THREAD

**Issue by luizeof** [oceanwp/oceanwp#283]
After updating OceanWP to version 1.8.4 I found this bug in the Blog layout.

![c4f42cf4-e12d-4ebc-b3c2-073c8ab04c0a](https://user-images.githubusercontent.com/257004/86613633-43aba000-bf88-11ea-9a4c-254bbb0a7791.png)

**Comment by eramits** [comment]
Hello @luizeof 

Are you still seeing this issue with v1.8.5? Can you share the page URL where you have this issue?

**Comment by luizeof** [comment]
hello @eramits after the update the issue was solved .... url = https://luizeof.com/br/

Thanks !!!
