### ISSUE TITLE
Multisite url errors

### ISSUE THREAD

**Issue by Sarah-p** [oceanwp/oceanwp#29]
I'm using a multisite install with sub-directories. With domain mapping enabled, ssl installed, and when viewing a blog archive/single with a featured image or related posts featured image, the url of the image is pulling from the multisite home domain instead of the mapped domain. Like this:

https://www.home-domain.com/sub-site-name/wp-content/uploads/sites/[site number]/image-name.jpg

when it should be:

https://www.sub-site-domain.com/wp-content/uploads/sites/[site number]/image-name.jpg

This causes a GET 403 error.

**Comment by nicolas-owp** [comment]
Hello, this is not related to OceanWP, you will need to see this with your web host.

**Comment by Sarah-p** [comment]
My host is fine. The urls were working fine till I updated the theme and the images urls are pulling the correct url via Elementor.

**Comment by nicolas-owp** [comment]
Hi, have you the same issue if you use the default WordPress theme? If yes, it comes from your server.
There is nothing in OceanWP to change URL.
