### ISSUE TITLE
theme default list-style-type for <ol> causing issues in Rich Text Editor

### ISSUE THREAD

**Issue by akhatri** [oceanwp/oceanwp#298]
**OceanWP version - 1.8.9**
I'm using a child theme of OceanWP and it looks like the base/rest CSS of the main OceanWP theme has following CSS
```
list-style-type: decimal
```
![ol-style-type](https://user-images.githubusercontent.com/2246544/93873225-45ece300-fcc9-11ea-9f71-79dd20008acc.PNG)

I believe this is used in most cases but there are scenarios where I need to use alphanumeric lists and this can be done by my content team as they specify the 'type' attribute in HTML. If this extra line of CSS is removed from the theme CSS, then it works as expected. 

Unfortunately I tried to use initial but that does not solve the issue so I think this extra line of CSS might not be required as it prevents users from using the standard `<ol>` numbering styles.

**list style markup**
![list-style-types-markup](https://user-images.githubusercontent.com/2246544/93873283-5dc46700-fcc9-11ea-9a74-1137478d3c0c.PNG)

**Output**
![output](https://user-images.githubusercontent.com/2246544/93873307-69179280-fcc9-11ea-867a-0ab55be176d3.PNG)

**Expected output after removing the extra CSS line**
![output-expected](https://user-images.githubusercontent.com/2246544/93873453-a2e89900-fcc9-11ea-9967-1d06067841b7.PNG)

**Comment by eramits** [comment]
Hello,

We were not very active on the Github issue page but now we will check it regularly. I tested the issue but don't have the same as you have. If possible and still have the issue, kindly share the page URL. For now, I'm closing this issue. You can always open a new one.
