### ISSUE TITLE
Don't use IDs as css selector 

### ISSUE THREAD

**Issue by luizbills** [oceanwp/oceanwp#3]
I noticed that you use a lot of ID in css. This is problematic because ID has more priority than classes in css forcing users to use `!important`. e.g:

```
div#red {
  background-color: red;
}

div.blue {
  background-color: blue; 
}
```
The result is a div with red background.

---

I also noticed that you use a lot `!important` in css, another thing that makes it even harder to extend the theme.

---

Any plans to resolve these issues?

**Comment by oceanwp** [comment]
Hello,

I use IDs only to elements present once in a page like the header, footer, etc, if you want to modify the css of its elements, you do not need to put !important, you just need to add exactly the same code in your child theme or via the customizer for it to work.

Likewise for !important, it is used for the css that you do not need to modify as for the page margin, if you disable the margin via the OceanWP Settings metabox, I use !important to be sure there is no margin at all.

**Comment by luizbills** [comment]
thank you for your feedback.
