### ISSUE TITLE
Missing partials/edit-post ?!

### ISSUE THREAD

**Issue by NautHnim** [oceanwp/oceanwp#3]
Like the title. When i go to a page like sample page, it not show Edit link.

**Comment by oceanwp** [comment]
Hello, it is not present but I can add it for the next version if you want.

**Comment by NautHnim** [comment]
Oh no :) I just think it is a  shortcoming. If no, please forget it :).
Sorry for my bad english.

**Comment by oceanwp** [comment]
Okay,
Your english is perfect :)
