### ISSUE TITLE
Helpful additions to customizer

### ISSUE THREAD

**Issue by jezweb** [oceanwp/oceanwp#30]
Enjoying using oceanwp in conjunction with elementor. A few things I would like to suggest be added to customizer:
- headings 5 and 6
- font sizes defined in em
- styling controls for (gravity) forms

**Comment by nicolas-owp** [comment]
Hello, most users don't use h5 and h6 so it will have options in the customizer for nothing, more options I add in it and slower it will be to load.
For the font size in em, I think about something to allow users to add em px and %.
For the forms, it is via the General Options > Forms in the customizer.

Feel free if you have any other suggestions :)
