### ISSUE TITLE
[BUG] portfolio page have bug

### ISSUE THREAD

**Issue by andykao1026** [oceanwp/oceanwp#300]
HI
1、There are 25 portfolio in total
![image](https://kod.digit-seed.com/website/2020-10-13_220134.jpg)

2、I set Appearance > Customize > Portfolio > General> Posts Per Page to 3  
![image](https://kod.digit-seed.com/website/2020-10-13_215813.jpg)

3、The Permalinks setting to Post name
![image](https://kod.digit-seed.com/website/2020-10-13_220846.jpg)

4、but go to the second page, it still shows 404
https://andy.juncreate.com.tw/portfolio/
username:andy
passwd:andy@0000

![image](https://kod.digit-seed.com/website/2020-10-13_215850.jpg)
![image](https://kod.digit-seed.com/website/2020-10-13_215915.jpg)

**Comment by eramits** [comment]
Hello,

We were not very active on the Github issue page but now we will check it regularly. Do you still have this issue with your site? If yes, then try to reset the permalink settings under Dashboard > Settings > Permalink to fix it.
