### ISSUE TITLE
Breadcrumbs don't allow for product sub-categories

### ISSUE THREAD

**Issue by MarkTatterTierney** [oceanwp/oceanwp#301]
In the breadcrumbs.php file the add_post_terms function orders the terms so that the parent is always first. I think this should be reversed.

Currently it checks to see if the first term has parents and if not just adds the first term to the items array.

It will never find a parent in the first item though. See line 1195 ish...

```
// Sort the terms by ID and get the first category.
if ( function_exists( 'wp_list_sort' ) )
	$terms = wp_list_sort( $terms, 'term_id' );

else
	usort( $terms, '_usort_terms_by_ID' );

$term = get_term( $terms[0], $taxonomy );
```

I think the terms array needs to be ordered in descending order by term id.

Like this:

```
// Sort the terms by ID and get the first category.
if ( function_exists( 'wp_list_sort' ) )
	$terms = wp_list_sort( $terms, 'term_id', 'DESC' );

$term = get_term( $terms[0], $taxonomy );
```

**Comment by eramits** [comment]
Hello,

We were not very active on the Github issue page but now we will check it regularly. Do you still have this issue with your site? If yes, kindly share a screenshot so that I can check it.
