### ISSUE TITLE
Add another column in the lower footer

### ISSUE THREAD

**Issue by Xumeiquer** [oceanwp/oceanwp#303]
It would be really amazing to have an extra column in the lower footer. Something like the top header where you can place 2 columns.

Thank you.

**Comment by eramits** [comment]
Hello @Xumeiquer,

We were not very active on the Github issue page but now we will check it regularly. You can use the oceanwp custom footer option to design it as per your need - https://docs.oceanwp.org/article/600-how-to-create-a-custom-footer
