### ISSUE TITLE
Please upgrade FontAwesome

### ISSUE THREAD

**Issue by khag7** [oceanwp/oceanwp#304]
Please upgrade to the latest version of fontawesome

Since 5.13 they change some css to improve webfont loading and it improves score using Google Lighthouse page testing, which is something that is important to my client.

**Comment by MarkHollo** [comment]
Hello @khag7,

Thanks for reaching out and apologies for the delayed reply. We are really not in the position to provide support on GitHub as well.

Font Awesome has been updated with OceanWP 2.0.0 version. You can also r[ead more about those changes and some new features in our blog post](https://oceanwp.org/blog/oceanwp-20-coming-out-what-to-expect/).

Hope this helps, and in case of any other issue, feel free to start a new thread.

Thank you for building with OceanWP
