### ISSUE TITLE
singlphp and archive.php not in wordpress theme

### ISSUE THREAD

**Issue by Amasiani** [oceanwp/oceanwp#305]
Need to make a change in the wordpress theme in the single.php and archive.php for my Easy property listing plugin to display single listing but the files are not in the main wp-content folder. Rather is in a subfolder, How do i connect the single.php and archive.php in the subfolder to work with Easy property listing plugin that require the files to be in the main wp-content folder?

**Comment by eramits** [comment]
Hello @Amasiani 

We were not very active on the Github issue page but now we will check it regularly. I didn't understand your question properly. Files are in the related plugin folder, right? In this case, I'll suggest you contact the plugin support to ask how to override their listing template. If I misunderstood your question, feel free to let me know.
