### ISSUE TITLE
How to force desktop site on mobile view

### ISSUE THREAD

**Issue by krevathiraj** [oceanwp/oceanwp#309]
can i knw how to force desktop site in oceanwp

**Comment by MarkHollo** [comment]
Hello @krevathiraj,

Apologies for the delayed reply, we are really not in the position to provide regular support outside of our support channels.

You can change the **Mobile Menu Breaking Point** via **Customize > Header > Mobile Menu**. The larger the number the later will the mobile menu appear. However, this will affect the mobile menu alone. The rest of the content will still be adjust for the screens automatically, regardless whether you've used default WordPress pages or a page builder to create content.

![image](https://user-images.githubusercontent.com/51923873/106867763-46ad7100-66ce-11eb-9c89-295a052302ff.png)

Please note, GitHub is for BUG and ISSUES report only. For any other (support) questions, please use the [official WordPress forum](https://wordpress.org/support/theme/oceanwp/) or join the[ OceanWP Facebook Community Support group](https://www.facebook.com/groups/OceanWP).

Hope this helps. Best of luck with your website
