### ISSUE TITLE
Improvement and addition to links used to close the editor

### ISSUE THREAD

**Issue by jezweb** [oceanwp/oceanwp#31]
The bottom left cross icon shows an option to return to dashboard and to view the page. This doesn't seem to be completely intuitive. There's no option to leave the editor without opening a new tab.
![screen shot 2018-01-10 at 3 26 05 pm](https://user-images.githubusercontent.com/13249054/34755797-a0f0abdc-f61a-11e7-9048-5e619ab0e079.png)

Perhaps if the options were:
- finish editing (goes to the page without editor enabled, in the same tab)
- view page (opens in new tab)
- page settings (opens page in wordpress dashboard)
- go to dashboard (goes to the landing page of wordpress dashboard)

**Comment by nicolas-owp** [comment]
Hello, this is not related to OceanWP but Elementor, you will need to open a topic in their github.
