### ISSUE TITLE
2.0.2 Woocommerce link decoration

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#312]
Just to say having got version 2.0.2 running - the woocommerce links were all underlined by default - although documentation says that the link styling has been removed. I've had to add a rule into my css to disable it.

**Comment by MarkHollo** [comment]
Hello @deebz,

Apologies for the belayed reply, we are really not in the position to provide support outside official support channels. For that purpose you can use either the [WordPress forum](https://wordpress.org/support/theme/oceanwp/) or our [Facebook Community Support group](https://www.facebook.com/groups/OceanWP).

This issue has been resolved, so you might have experienced caching problems. You can remove the CSS rule, make sure to purge all cache thoroughly and then check again. In case of any problems, you can reach us on above mentioned channels or submit a ticket if you're a client.

Please note that GitHub is for Bug and Issue reports only.

Thank you for building with OceanWP
