### ISSUE TITLE
Multi-step checkout does not validate fields before clicking next button

### ISSUE THREAD

**Issue by harsha-sira** [oceanwp/oceanwp#315]
**Steps to recreate**

Go to customing using below path, Woocommerce -> Checkout
Enable multi-step checkout

<img width="307" alt="Screenshot 2021-01-16 at 12 12 58" src="https://user-images.githubusercontent.com/8362657/104799389-c1345080-57f4-11eb-80e8-9f83420adba3.png">

but it does not validate fields before clicking the next button.

does not validate on Next button click
<img width="1090" alt="Screenshot 2021-01-16 at 12 19 34" src="https://user-images.githubusercontent.com/8362657/104799436-1e300680-57f5-11eb-9f53-58dbfa61f114.png">

Validations only happen just before the payment. Not for each step

**Comment by cmaile** [comment]
Any news/workaround regarding this issue? 

Same behavior with Wordpress 5.6 with OceanWP v2.0.2.

**Comment by eramits** [comment]
Hello,

Sorry for the late response. This issue will be fixed in the next update of the OceanWP theme for sure.
