### ISSUE TITLE
Header images not shown when no video is set

### ISSUE THREAD

**Issue by maurice0800** [oceanwp/oceanwp#317]
**The problem**
When you try to set a header image through Customizer the header image is not shown as long as no video has been set. Is this intended behavior? 
My clients wanted a header image set on all pages but no video on the front page. This does not seem to be possible with the current theme.

**Possible fix**
We fixed this with changing partials/header/layout.php 
`if ( function_exists( 'has_header_video' ) && has_header_video() ) {`
to
`if ( function_exists( 'has_header_video' ) && (has_header_video() || has_header_image()) ) {`

**Comment by MarkHollo** [comment]
Hello @maurice0800,
