### ISSUE TITLE
Medium Header Style Anchor Links Issue

### ISSUE THREAD

**Issue by MarkHollo** [oceanwp/oceanwp#318]
Medium Header style not functioning with anchor links since WP 5.6, tested and confirmed both on Elementor and Gutenberg - not scrolling to the anchor if on the same page or not "leading" to the anchor if on another page.

**Comment by eramits** [comment]
Hi @MarkHollo

As far as I know, this issue is related to js and since @mohammadTaghiElmi converted the theme into plain js, it will good if he takes a look at it. I have also created a CH ticket and assigned him.

**Comment by mohammadTaghiElmi** [comment]
@MarkHollo @eramits 

Fixed.
