### ISSUE TITLE
Breadcrubms disappear. 

### ISSUE THREAD

**Issue by andrefff** [oceanwp/oceanwp#32]
Hi, I dont know what happed, but my breadcrumbs disappear. I already checked the box at page tittle, but not happens.

**Comment by nicolas-owp** [comment]
Hello, do you use Yoast SEO? If yes, go to the plugin settings and enable Yoast SEO breadcrumb.

**Comment by andrefff** [comment]
I really like you, Thanks

Im a premium user yours. :)

**Comment by nicolas-owp** [comment]
You are most welcome :)
I close this topic then, feel free to reach me if you have any issue with the theme :)
