### ISSUE TITLE
WordPress new feature of comment cookies opt-in checkbox did not work in OCEANWP theme

### ISSUE THREAD

**Issue by tonytanlh** [oceanwp/oceanwp#320]
WordPress new feature of comment cookies opt-in checkbox did not work in OCEANWP theme , even we enable this function in WordPress setting>discussion>comment cookies opt-in checkbox, please look into it, thank you!

**Comment by tonytanlh** [comment]
![image](https://user-images.githubusercontent.com/37864848/111874039-480cd180-89ce-11eb-8b0d-6c493c382094.png)

**Comment by eramits** [comment]
Hello @tonytanlh 

It is working fine with the theme. I think you have tested the issue when you are logged in. In that case, all the details are already there and only a comment box appears without the name, website and email fields.

Try to logout first, then check the features. It will work fine. I tested it on my end and didn't see any issue.
