### ISSUE TITLE
Styling Issues within Gutenberg Editior

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#324]
Just installed 2.0.4 and noticed when I edit Gutenberg-based blog posts all the text takes on strange styling.

In 2.0.3 the text in the Gutenberg editor is set to helvetica and at normal body text size. With 2.0.4 installed the body text in the editor follows what I have used for the front end, but the text size is between 40px and 50px making edits impossible.

Added screenshot as issue persists in 2.0.6
<img width="1010" alt="Screenshot 2021-04-30 at 11 01 26" src="https://user-images.githubusercontent.com/462011/116680578-bec0c580-a9a3-11eb-85b4-050a68be8959.png">

**Comment by eramits** [comment]
Hello @deebz,

Sorry for the late response. I'm not able to replicate this issue. Can you please share the steps to replicate it? Have you also tested this issue with the latest version 2.0.8?

**Comment by deebz** [comment]
Hi @eramits,

I haven't tried 2.0.8 yet... but will do.

As for the steps to replicate. This is tricky as I created the post with gutenberg blocks in version 2.0.3 but didn't do anything unusual or unexpected when building the layout.

Sorry I couldn't expand on this further. Will test 2.0.8 and feedback

**Comment by deebz** [comment]
Check 2.0.8 and the issue persists.
It affects the standard wordpress paragraph block (see screenshot above) when set to text size _default_ changing to _normal_ fixes the font size of the text. However the text size of the buttons isn't being obeyed and is still rendered massive.

**Comment by deebz** [comment]
also just noticed that the responsive styles are also lost, when they were functioning as expected in version 2.0.3

**Comment by eramits** [comment]
I have tested all the issues you have mentioned above but don't have the same and didn't reproduce it. Can you test the issue on a fresh site? Can you please share the screenshot for the broken responsive style as you mentioned above?

**Comment by MarkHollo** [comment]
Hello @deebz, we haven't heard back from you but we would really like to investigate this on your end if the issue is still present.

Kindly open a (prepurchase) ticket on oceanwp.org, with all necessary details (admin and FTP login) to a test/staging site where we can troubleshoot this and find the cause.

Thank you very much for your help in advance

**Comment by deebz** [comment]
Hi @MarkHollo,

Strangely this is no longer an issue for me. Updated to ocean 2.1.1 and default font size renders in Gutenberg at the correct size - AFTER - the page has fully loaded. I do see this now on new posts/pages. The initial paragraph is displaying a larger font size until I click into it to edit.

Unfortunately, I don't have a development site with this site running on to give you access to. I do suspect this is more to do with the order in which css is being loaded in with relation to some of the Gutenberg block plugins I'm running alongside OceanWP.

Thank you for your time and interest in this
