### ISSUE TITLE
Multi-step checkout flow is broken when not signed in

### ISSUE THREAD

**Issue by tobyaherbert** [oceanwp/oceanwp#326]
Hey there,

We're experiencing problems with multi-step checkout since version 2.0.5 whereby guest users see an `undefined` error when clicking "I don't have an account" from the 'Login' step.

This appears to have been caused by [this commit](https://github.com/oceanwp/oceanwp/commit/56ab06e1ae02087a21b3e814c3f1e734e7926ff3#diff-02703398f7fee6a0768bc9bc6bf2c57e5a28fe0f970e0ae52a2d8c87c3ebe650) as rewinding its changes resolves the issue.

It looks like it's checking to make sure billing details have been provided but the user hasn't actually arrived at that step yet so they can't possibly have provided them.

Could someone take a look at this please?

Thanks

**Comment by tobyaherbert** [comment]
Hey again,

I can see that a new version was released (2.0.7) to fix these issues and I can confirm that we're now able to move on to the next step, but the fields are all highlighted in red when you arrive on the page which isn't the nicest of user experiences.

We've also now got another issue whereby if you don't check the 'Create account' checkbox you can't proceed as the validations are still enforcing requirement of the password field which shouldn't be required to check out as a guest.

**Comment by eramits** [comment]
Hello @tobyaherbert,

Sorry for the delayed response. For a quick response, please open a ticket at the oceanwp support page. 

For this issue, it is fixed and comes with the next theme version update. If you want to test it, kindly use this branch - https://github.com/oceanwp/oceanwp/tree/theme-dev
