### ISSUE TITLE
Long Variation Names Overflowing

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#328]
Discovered this one recently when adding slightly longer variation attributes to variable products. The text wraps and the overflow is displayed.

Simple enough CSS fix but maybe one to look into?

CSS I used for the fix:
.variations .theme-select { overflow:hidden;}

<img width="488" alt="Screenshot 2021-04-30 at 10 19 18" src="https://user-images.githubusercontent.com/462011/116675281-903fec00-a99d-11eb-8c82-e999d7031b0f.png">

**Comment by eramits** [comment]
Hi @deebz 

I have added the fix in the theme. It will come with the next version of the theme. 

Thank you

**Comment by deebz** [comment]
Hi @eramits 

Always happy to help
