### ISSUE TITLE
Feature Request: Custom Body Classes

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#329]
Allow custom classes to be added to body tag of pages/posts.

Use case. I have certain pages and posts that I want to apply a general style rule to, but other pages that use the same page template but I want to except from the style rule. I currently use a duplicated version of page.php with a custom class in the `<div id="#content-wrap" class="container">` which works but feels unwieldy.

At the moment the only way to differentiate between pages that I want included and excluded are using this custom template or through page id's which is a little hard to keep track of.

It would be nice to be able to add as an option in the general OceanWP settings box on each page.

<img width="1166" alt="Screenshot 2021-04-30 at 10 37 19" src="https://user-images.githubusercontent.com/462011/116677377-0c3b3380-a9a0-11eb-94f2-fdabd2ac438d.png">

**Comment by eramits** [comment]
Hi @deebz 

Actually, it is a very good idea. I'll add this feature in the next update of the Ocean Extra plugin so that you can use it.

**Comment by deebz** [comment]
Hi @eramits

Glad you like the idea and think it's worth including!

**Comment by eramits** [comment]
The setting has been added. It will be available in the next update of Ocean Extra. 

[https://github.com/oceanwp/ocean-extra/commit/9cebf76abb29aa6c359708588fc41cfab79cc496](url)

**Comment by MarkHollo** [comment]
Hello @deebz,

Settings have been added to the Ocean Extra 1.7.6 version. Thank you for the idea, and we hope you and all other users will find it useful :)

If you would like to contribute by sharing more suggestions or have a feature request, you can also use our [Feature Request form](https://oceanwp.org/feature-requests/)

Have a great day
