### ISSUE TITLE
Warning notice after last update

### ISSUE THREAD

**Issue by AntonLitvin** [oceanwp/oceanwp#336]
Hello.
After last update to ver 2.1.1 I have in header warning notice about basket icon
Notice: Undefined index: fas fa-shopping-basket in C:\OpenServer\domains\ocean-wp.loc\wp-content\themes\oceanwp\inc\oceanwp-theme-icons.php on line 780
![123](https://user-images.githubusercontent.com/19684210/124081505-4f735a80-da54-11eb-8699-ba503429add6.jpg)

**Comment by MarkHollo** [comment]
Hello @AntonLitvin,

Navigate to Customize > WooCommerce > Menu Cart, reselect the icon for the cart and that should fix the problem

**Comment by AntonLitvin** [comment]
@oceanwp, Yes, I did this before writing the report, but the warning disappeared from the front, but not in the admin panel. But running now I saw that the warning is gone. Many thanks. sorry for my English
