### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by berlege** [oceanwp/oceanwp#337]
Hi, just installed version 3.0. At the bottom of a page/post (below the footer widgets), there are some new (non-working) buttons, see below. I couldn't find a related setting . The bottom footer is not activated.
KR

                        <div class="pswp__top-bar">
                            
                            <div class="pswp__counter"></div>

                            <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                            <button class="pswp__button pswp__button--share" title="Share"></button>
                            <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                            <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                            
                            
                            <div class="pswp__preloader">
                                <div class="pswp__preloader__icn">
                                <div class="pswp__preloader__cut">
                                    <div class="pswp__preloader__donut"></div>
                                </div>
                                </div>
                            </div>
                        </div>

                        <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                            <div class="pswp__share-tooltip"></div> 
                        </div>

                        <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                        </button>

                        <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                        </button>

                        <div class="pswp__caption">
                            <div class="pswp__caption__center"></div>
                        </div>

**Comment by MarkHollo** [comment]
Hello @berlege,

Kindly go to Elementor > System Info and copy/paste your report here so that we can check your system.

Did you update all plugins? Are all scripts enabled via Theme Panel > Scripts & Styles? Did you purge cache on your website/browser/cloud?

Thanks

**Comment by berlege** [comment]
Purging the cache did the trick. Sorry for the false alert! I thought I had done this. Thank you.
