### ISSUE TITLE
php warning when installing Ocean Extra after theme install

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#34]
Hi,
I receive the following PHP Warning in PHP error log and WP Backend when installing Ocean Extra after theme install...

"PHP Warning:  array_intersect_key(): Argument #1 is not an array in C:\laragon\www\testing\wp-content\plugins\ocean-extra\includes\panel\scripts.php on line 605"

Latest OWP Theme / Extra  | Tested PHP 7.2.0, 7.2.1 / Laragon 3.2

thx!

stefan

**Comment by stevek28** [comment]
Just tested it with a fresh install on live server as well (Siteground Hosting) .. 

There I receive and additional message in WP backend: 

"...ader information - headers already sent by (output started at /home/c3drealb/public_html/wp-content/plugins/ocean-extra/includes/panel/scripts.php:605) in /home/c3drealb/public_html/wp-admin/includes/misc.php on line 1114"

**Comment by nicolas-owp** [comment]
Hello, thank you for letting me know, I will look into this.

**Comment by obe1968** [comment]
Nicolas;

First off, thanks for a GREAT theme and all the hard work you put into it!! I am still learning and researching about OWP and plan to by a full site license in the very near future, and if things work out, upgrade my package from there.

Anyway, on this error. I am no developer by any means, and hack around a bit. I think I found a solution to this issue, but not sure. I "think" I fixed it on my end, and what I did was add a closing ?> on the last line of includes/panel/scripts.php after new Ocean_Extra_Scripts_Panel();

Is thhis the correct way to fix this problem?

Cheers!!!

**Comment by nicolas-owp** [comment]
Hello @obe1968, thank you for the nice words and for using OceanWP, very glad that you like it :)
I will work on this feature because some things don't work so I will try to fix the bugs and improve it.
It is usually not good to close a PHP file but maybe, in that case, it is the solution, I will check this. Thank you very much for your feedback :)

**Comment by leogaggl** [comment]
Can confirm this issue on Ubuntu 16.04 Apache 2.4 PHP 7.0
PHP Warning:  array_intersect_key(): Argument #1 is not an array in /wp-content/plugins/ocean-extra/includes/panel/scripts.php on line 630

**Comment by nicolas-owp** [comment]
Hello, glad to tell you that in the next release of Ocean Extra, you will don't have this kind of issues anymore :)

**Comment by babbage2018** [comment]
Good day.
After installing and activating the plugin, I can not access the site in denwer. It produces the following error.
Parse error: syntax error, unexpected '[' in Z:\home\*******\www\wp-content\plugins\ocean-extra\includes\panel\demos.php on line 1159

**Comment by HanFur** [comment]
> Good day.
> After installing and activating the plugin, I can not access the site in denwer. It produces the following error.
> Parse error: syntax error, unexpected '[' in Z:\home*******\www\wp-content\plugins\ocean-extra\includes\panel\demos.php on line 1159

Hello!
I have the same error as Babbage2018,
As long as I run the website on my localhost  mamp  there is no problem. I can export it with all-in-one migration to a file. But the error pops up when I want to import it to my hostingprovider. When I disable the plugin, I can import it to my  hostingprovider, but the layout of the website is gone.

**Comment by nicolas-owp** [comment]
You're welcome :)
