### ISSUE TITLE
No font loading in latest version

### ISSUE THREAD

**Issue by kaustubhk24** [oceanwp/oceanwp#341]
![image](https://user-images.githubusercontent.com/57136442/127097055-dad509e1-77a4-4472-b583-6aa0ebcb7f87.png)

check if it helps

**Comment by MarkHollo** [comment]
Hello @kaustubhk24,

Thanks for reaching out.

I'm afraid this is unrelated to OceanWP or any of the Ocean Extensions, therefore you really need to check other plugins you're running.

It would also be helpful to us help you identify the cause if you could share your Elementor > System Info report, and specify where exactly are you experiencing this problem
