### ISSUE TITLE
Uncaught ReferenceError: oceanwpLocalize is not defined

### ISSUE THREAD

**Issue by juejixiaohaipi** [oceanwp/oceanwp#342]
on dashboard widget,throw this error  from this file :
/themes/oceanwp/assets/js/wp-plugins/woocommerce/woo-quick-view.min.js?ver=1.0:1 Uncaught ReferenceError: oceanwpLocalize is not defined

**Comment by MarkHollo** [comment]
Hi @juejixiaohaipi,

This issue has been resolved a while ago, but we're now checking all threads we didn't close for whatever reason.

Can you please check if you're still experiencing this problem on your end?
