### ISSUE TITLE
Anchor link + Vanilla JS

### ISSUE THREAD

**Issue by matthewmurdoch** [oceanwp/oceanwp#343]
Uncaught TypeError: Cannot read property 'classList' of null
    at e.value (theme.vanilla.min.js?ver=1.0:1)
    at HTMLAnchorElement.value (theme.vanilla.min.js?ver=1.0:1)
value @ theme.vanilla.min.js?ver=1.0:1
value @ theme.vanilla.min.js?ver=1.0:1

Above issue is showed when using Anchor links ie: www.website.com/#something

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.21
	PHP Max Input Vars: 3500
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://www.fancyinc.co.za
	Home URL: https://www.fancyinc.co.za
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 3.0.3
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62

== Active Plugins ==
	Advanced CF7 DB
		Version: 1.8.2
		Author: Vsourz Digital

	Anywhere Elementor
		Version: 1.2.4
		Author: WPVibes

	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.0
		Author: Gabe Livan

	Contact Form 7
		Version: 5.4.2
		Author: Takayuki Miyoshi

	Contact Form 7 Captcha
		Version: 0.0.9
		Author: 247wd

	Date and Time Picker by Input WP
		Version: 2.0
		Author: Input WP

	Disable Comments
		Version: 2.1.2
		Author: WPDeveloper

	Duplicate Page
		Version: 4.4.1
		Author: mndpsingh287

	Elementor
		Version: 3.3.1
		Author: Elementor.com

	Elementor Hero Slider
		Version: 1.0.3
		Author: Pixel+

	Elementor Pro
		Version: 3.3.4
		Author: Elementor.com

	Envato Elements
		Version: 2.0.9
		Author: Envato

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	JetElements For Elementor
		Version: 2.5.8
		Author: Crocoblock

	JetEngine
		Version: 2.8.7
		Author: Crocoblock

	JetSmartFilters
		Version: 1.8.3
		Author: Crocoblock

	JetThemeCore
		Version: 1.2.2
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.9.2
		Author: Crocoblock

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	ManageWP - Worker
		Version: 4.9.9
		Author: GoDaddy

	NP Quote Request WooCommerce
		Version: 1.8.255
		Author: Neah Plugins

	Ocean Custom Sidebar
		Version: 1.0.7
		Author: OceanWP

	Ocean Extra
		Version: 1.7.8
		Author: OceanWP

	Pinterest for WooCommerce
		Version: 2.4.2
		Author: premmerce

	Popup Maker
		Version: 1.16.2
		Author: Popup Maker

	Product Feed PRO for WooCommerce
		Version: 10.4.7
		Author: AdTribes.io

	Rank Math SEO
		Version: 1.0.69.1
		Author: Rank Math

	SEO Friendly Images
		Version: 3.0.5
		Author: Vladimir Prelovac

	Shortcode in Menus
		Version: 3.5.1
		Author: Gagan Deep Singh

	Tidio Chat
		Version: 4.3.0
		Author: Tidio Ltd.

	Widgets for Google Reviews
		Version: 6.7
		Author: Trustindex.io <support@trustindex.io>

	WooCommerce
		Version: 5.5.2
		Author: Automattic

	WooCommerce Admin
		Version: 2.4.4
		Author: WooCommerce

	Woo Image SEO
		Version: 1.2.3
		Author: Danail Emandiev

	WP Activity Log
		Version: 4.3.1
		Author: WP White Security

	WP Activity Log for WooCommerce
		Version: 1.2.2
		Author: WP White Security

	WP Rocket
		Version: 3.9.0.5
		Author: WP Media

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy

== Elementor - Compatibility Tag ==
	
	Anywhere Elementor: Incompatible
	Elementor Hero Slider: Compatibility not specified
	Elementor Pro: Compatible
	Envato Elements: Compatible
	JetElements For Elementor: Incompatible
	JetWooBuilder For Elementor: Incompatible
	Make Column Clickable Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Anywhere Elementor: Incompatible
	Envato Elements: Compatible
	JetElements For Elementor: Incompatible
	JetWooBuilder For Elementor: Compatible

== Elements Usage ==
	
	page : 23
		button : 19
		divider : 4
		heading : 24
		icon-list : 3
		image : 9
		jet-listing-dynamic-field : 1
		jet-single-add-to-cart : 1
		jet-single-content : 1
		jet-single-images : 1
		jet-single-related : 1
		jet-single-tabs : 1
		jet-smart-filters-active : 5
		jet-smart-filters-checkboxes : 11
		jet-smart-filters-color-image : 5
		jet-smart-filters-pagination : 4
		jet-smart-filters-remove-filters : 4
		jet-smart-filters-search : 5
		jet-woo-products : 5
		shortcode : 3
		social-icons : 1
		spacer : 4
		text-editor : 33
	wp-post : 
		heading : 5
		html : 2
		icon-list : 4
		image : 1
		jet-smart-filters-active : 57
		jet-smart-filters-checkboxes : 45
		jet-smart-filters-color-image : 54
		jet-smart-filters-pagination : 54
		jet-smart-filters-remove-filters : 57
		jet-smart-filters-search : 57
		jet-woo-builder-products-ordering : 3
		jet-woo-products : 54
		spacer : 58
		wp-widget-ocean_social : 1
	wp-page : 91
		accordion : 5
		button : 87
		contact-form-7 : 2
		divider : 22
		form : 11
		heading : 284
		html : 13
		image : 131
		image-carousel : 1
		jet-button : 2
		jet-portfolio : 1
		jet-smart-filters-active : 4
		jet-smart-filters-checkboxes : 6
		jet-smart-filters-color-image : 4
		jet-smart-filters-pagination : 4
		jet-smart-filters-remove-filters : 4
		jet-smart-filters-search : 4
		jet-woo-products : 4
		lottie : 1
		shortcode : 76
		slider-hero-with-elementor : 2
		spacer : 187
		text-editor : 201
		woo-best-selling-products : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	jet-woo-builder-shop : 0
		button : 1
		divider : 1
		heading : 1
		image : 1
		jet-smart-filters-active : 1
		jet-smart-filters-checkboxes : 3
		jet-smart-filters-color-image : 1
		jet-smart-filters-pagination : 1
		jet-smart-filters-remove-filters : 1
		jet-smart-filters-search : 1
		jet-woo-products : 1
		spacer : 1
		text-editor : 2
	jet-woo-builder : 2
		heading : 1
		jet-listing-dynamic-field : 1
		jet-single-add-to-cart : 1
		jet-single-content : 1
		jet-single-images : 1
		jet-single-related : 1
		jet-single-tabs : 1
		text-editor : 6

== Log ==
	
Log: showing 20 of 392021-06-17 09:29:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]
2021-06-21 08:47:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-13 16:34:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:34:17 [info] elementor::elementor_updater Started 
2021-07-13 16:34:17 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-13 16:34:20 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-13 16:34:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:34:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:34:22 [info] elementor::elementor_updater Started 
2021-07-13 16:34:22 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-13 16:34:24 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-13 16:34:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 17:13:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.2',
)]
2021-07-21 09:48:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-21 09:48:55 [info] elementor::elementor_updater Started 
2021-07-21 09:48:55 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-21 09:48:58 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-21 09:48:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-21 09:49:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.2',
  'to' => '3.3.3',
)]
2021-07-22 08:35:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.3',
  'to' => '3.3.4',
)]

PHP: showing 4 of 4PHP: 2021-06-24 15:23:13 [notice X 10][/usr/www/users/fancynugbz/wp-content/plugins/elementor/includes/template-library/sources/local.php::1040] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-20 13:29:39 [notice X 1][/usr/www/users/fancynugbz/wp-content/plugins/elementor/core/app/modules/import-export/module.php::156] Undefined index: session [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-02 10:33:32 [notice X 1][/usr/www/users/fancynugbz/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-02 10:56:21 [notice X 1][/usr/www/users/fancynugbz/wp-content/plugins/elementor/modules/usage/module.php::78] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by MarkHollo** [comment]
Hello @matthewmurdoch,

Thank you for the feedback and apologies for the delay in response.

All anchor links have been resolved with the version 3.0.4 (3.0.5 is the current OceanWP version).

But, if you're still experiencing problems, you can submit a support ticket with us (even a prepurchase one), and we'd be happy to take a look at your site and inspect the issue on your end.

Wishing you a great day
