### ISSUE TITLE
Remove non-standard outdated CSS

### ISSUE THREAD

**Issue by S-K-Tiger** [oceanwp/oceanwp#349]
Repeating what I found from a [similair issue](https://github.com/woocommerce/storefront/issues/698):
-moz-osx-font-smoothing and -webkit-font-smoothing should be removed.

`These settings are non-standard with [no future ahead of them](https://caniuse.com/#feat=font-smooth) (and no past or present, either, unless you're using OSX).`

**Comment by eramits** [comment]
Hello @S-K-Tiger 

Thank you for pointing out it. We will definitely look into it and remove the old code.
