### ISSUE TITLE
Default Sidebar not showing on Search Page

### ISSUE THREAD

**Issue by Zunichi** [oceanwp/oceanwp#35]
![image](https://user-images.githubusercontent.com/10968011/35316362-141a59d0-0086-11e8-8dd0-7b1ce52dbf8e.png)

If Custom Sidebar is turned off, it should have the default sidebar correct? If so, it's not showing in my search pages.

**Comment by nicolas-owp** [comment]
Hello, you found a bug :)
I will fix it for the next release.
