### ISSUE TITLE
Gutenberg Wide align width issue

### ISSUE THREAD

**Issue by bfintal** [oceanwp/oceanwp#351]
Hello, I have OceanWP installed and using Gutenberg and when you set a block to wide align, it shows up narrower than the default block width. This is a fresh install.

Here's the screenshot from Gutenberg when I create a new page that uses the landing page template: 3 native image blocks aligned differently - top is center aligned, second is wide aligned, and bottom is full aligned:
![image](https://user-images.githubusercontent.com/1033611/136681056-c305c55c-daf5-4480-a67d-84230815aed4.png)

Here's what it looks like in the frontend:
![image](https://user-images.githubusercontent.com/1033611/136681109-6bcb9838-1b6f-490f-a5f6-ed48636cc993.png)

The top center aligned block looks okay, the second wide aligned as you can see is narrower.

Found some CSS that's causing the wide align to be smaller:
![image](https://user-images.githubusercontent.com/1033611/136681137-49501aa9-4e89-47e9-96c5-682bb33aa16f.png)

**Comment by eramits** [comment]
Hello @bfintal 

Can you please tell which width layout you are using for page? If possible, please share the page url.

**Comment by MarkHollo** [comment]
Hello @bfintal,

Hope all is well.

We haven't heard back from you, but this issue has been completely resolved with OceanWP 3.1.3 version.

If you're still experiencing issues after the update, kindly reopen this or start a new thread.

Thank you very much
