### ISSUE TITLE
Site Logo Disappears on Distraction Free Cart

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#353]
Just updated to 3.1.1 and the site logo disappears from the distraction free basket and checkout

**Comment by MarkHollo** [comment]
Hello @deebz, hope all is weel.

This issue has been resolved with the OceanWP 3.1.3 version. Please test, and if you're still experiencing problems, kindly reopen the thread or start a new one :)

Looking forward to your feedback
