### ISSUE TITLE
Menu Basket Dropdown bug

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#354]
This issue has been pretty long standing. When dropdown is selected the contents of the mini basket are shown. Strangely this isn't an issue when logged in as admin. 

Once a product is added, the menu basket dropdown behaves as expected even when a product is removed and the basket is empty.

Tried everything, clearing/disabling server side caches, clearing browser cache nothing resolves it. 

As for theme customisations, I have disabled the one or CSS rules applied and retested with flushed caches. I have feeling that this is a JS issue that I first noticed about version 2.1.1

<img width="328" alt="Screenshot 2021-12-15 at 09 47 35" src="https://user-images.githubusercontent.com/462011/146170631-8b6febb4-3e44-4fa4-b711-f6b38ad900d3.png">

**Comment by MarkHollo** [comment]
Hello @deebz,

Any chance you could reach us directly regarding this matter, share your System Info and some videos of the problem? That would really help us understand the problem in full.

Thank you

**Comment by deebz** [comment]
Hi Mark,

What's the best way of contacting you with video's and sys info?

**Comment by MarkHollo** [comment]
Hello @deebz,

Thank you very much for the feedback! Nothing better than knowing the issue was resolved :)

And thank you for your continuous support and detailed reports!

In case you notice something else, we're counting on you :)
