### ISSUE TITLE
Mandatory fields multistep checkout

### ISSUE THREAD

**Issue by Svney** [oceanwp/oceanwp#358]
Hello,

since the update 3.1.3, the mandatory fields at the multistep checkout are bugged.
When a customer enters his informations in billing informations you can proceed to shipping, where you have the option to enter a different shipping adress. Normaly you wouldn't do that, so you skip this step by clicking next, wich doesnt work because it wants the mandatory fields for shipping adress to be filled, wich you can't see because it is hidden if you dont check the "want a different shipping adress" box.
This destroys my checkout page completly at the moment.

OcenWp version 3.1.3
webside for testing where the problem happens: https://tanafleur.de/kasse/

thanks in advance. need a quick fix asap pls.

**Comment by MarkHollo** [comment]
Hello @Svney,

Any chance you can create a staging site and reach us with login details, along with a video of the issue, so that we can check it out?

Thank you

**Comment by Svney** [comment]
Hey @MarkHollo,
i have no staging website and no plugin to do so. Here is the video from the problem. Where i right clicked, i clicked like crazy left. nothing happens because the fields are mandatory and are not shown until you check the box.

https://user-images.githubusercontent.com/98956955/152893629-c85165a5-176a-43e5-bc59-b9a57c5e95c4.mp4

**Comment by Svney** [comment]
> I have the same error when I use it together with the plugin with additional checkout fields, this plugin hides some fields according to the user's selection and the _formValidate2 function is not prepared for this. A change similar to this solves the problem:
> 
> ```
> function _formValidate2(section) {
>   var invalidRows = Array.from(section.querySelectorAll(".validate-required")).filter(function (row) {
> 
>   // Ignore hidden fields
>   if (row.style.display=='none') return false;
> 
>     return "input, select, textarea".split(", ").find(function (selector) {
>       var input = row.querySelector(selector);
>       if (input) return input.value.trim() === "";
>     });
>   });
> ```


hey @kaoecoito, thanks for your reply. Sadly i dont know what to do with this. I dont use additional checkout fields. Just the Oceans recommended WpForms. I use Mostly standard code and plugins. I tried to make them optional by using this function:

function custom_override_default_address_fields( $fields ) {
	$fields['shipping_first_name']['required'] = false;
	$fields['shipping_last_name']['required'] = false;
	$fields['shipping_address_1']['required'] = false;
	$fields['shipping_address_2']['required'] = false;
	$fields['shipping_city']['required'] = false;
	$fields['shipping_postcode']['required'] = false;
	$fields['shipping_country']['required'] = false;
	$fields['shipping_state']['required'] = false;
		
return $fields;
}

wich doesn't work for all fields...

**Comment by kaoecoito** [comment]
it's actually more complicated as any hidden field that is mandatory causes errors.
After this adjustment I had to make one more because in the part of the delivery address it can happen to mark to send in the same address and then the mandatory fields are hidden and the validation is not able to identify this and prevents the operation.
The plugin I used is important in the case of Brazil due to the need for additional data at checkout for tax issues, but I understand that it is difficult to find a simple way to validate considering the possibilities.
The adjustment that seems to make sense is to see if the field is visible and in case the address does not validate the fields if it is marked to use the same billing address.

**Comment by kaoecoito** [comment]
Maybe it's an option to create a filter that complements your custom_override_default_address_fields function so that we can add unforeseen fields.

**Comment by skalanter** [comment]
Hello @Svney and @kaoecoito 

Thanks for reaching out and letting us know. 
We did see this happening on our end, so we'll share this with our team for investigation.

For a temporary solution in ordinary cases, you can use the code below in Customizer > Custom CSS/JS > JS Code:

```
jQuery(document).ready(function($) {  
    var checkboxInput = jQuery(".woocommerce-checkout .input-checkbox");
    if( checkboxInput.is(":not(:checked)") ) {
        jQuery(".woocommerce-checkout .input-checkbox").parents().eq(3).addClass("checkbox-is-false");
        jQuery("body .checkbox-is-false p").removeClass("validate-required")
        jQuery("body .checkbox-is-false p").addClass("for-next-click")
    }
    jQuery(".woocommerce-checkout .input-checkbox").on("click", function() {

        if( checkboxInput.is(":checked") ) {
            jQuery(".woocommerce-checkout .input-checkbox").parents().eq(3).removeClass("checkbox-is-false");
            jQuery("body .for-next-click").addClass("validate-required")
            jQuery("body .for-next-click p").removeClass("for-next-click")
        }
        if( checkboxInput.is(":not(:checked)") ) {
            jQuery(".woocommerce-checkout .input-checkbox").parents().eq(3).addClass("checkbox-is-false");
            jQuery("body .checkbox-is-false p").removeClass("validate-required")
            jQuery("body .checkbox-is-false p").addClass("for-next-click")
        }
    });
});
```

If the code above didn't help you to solve your issue (as a temporary solution), please open a pre-purchase ticket and send your URL via this link: https://oceanwp.org/pre-purchase-question/; we'll check your website conditions to reproduce the issue on our ends and fix it asap.

**Please Note:** the code above is jQuery, and we'll fix the issue in vanilla JS, so don't worry if the code is not vanilla.

Best Regards

**Comment by Svney** [comment]
Hello @skalanter your script works like a charm.

its a temporary fix that works for now. Thank you so much.

**Comment by Svney** [comment]
@skalanter
its broken again. Whenever someone is on my webside for the first time it's not working for him!
i'll write at prepurchase.

**Comment by skalanter** [comment]
Hello @Svney,

For a temporary solution, you can update the theme manually to the dev version, so please do the steps below:

To update the theme manually, please do the steps below:

0- First, download the theme (https://github.com/oceanwp/oceanwp/archive/refs/heads/master.zip).
1- Head over to WP Dashboard > Appearance > Themes > Add New.
2- Click on the "Upload Theme" button.
3- Choose the theme and click on the install now button: https://i.postimg.cc/y8tSqfH2/image.png
4- Next, click on the "Replace current with uploaded" button: https://i.postimg.cc/jSctP28c/image.png

Now, please recheck your issue.
Note: if you have a cache plugin or server/CDN or LiteSpeed cache. You need to clear its cache contents or disable them to see your changes.

Best Regards
