### ISSUE TITLE
Why is it possible to change the post layout from the url ?

### ISSUE THREAD

**Issue by ajoah** [oceanwp/oceanwp#36]
Hi,

I am discovering your great theme and i have seen a strange thing in your code : 
https://github.com/oceanwp/oceanwp/blob/c44734e5c5a4ec7ad3b68afde648717790d31f20/inc/helpers.php#L291-L294

What is this code purpose?

Because of it, it is possible to change the post layout of any website using the theme.

For exemple : https://oceanwp.org/?post_layout=both-sidebars

**Comment by nicolas-owp** [comment]
Hello, you have right, I will fix this for the next release.
