### ISSUE TITLE
Css layout-sticky menu and submenu issues 

### ISSUE THREAD

**Issue by stevenbrok** [oceanwp/oceanwp#363]
[](url)Since 2 weeks i have issues with a white bar showing on top of my pages of my website as well as desktop and on mobile screen. It interferes with the sticky menu. 
Furthermore on mobile the submenu's are not shown anymore and thus not clickable. 
I have had contact with support and created a staging site but it remains quiet after several emails in where i ask the status for this issue. Hope someone can help me out as its interferes with functionality of my website and business. 
Thanks 

See screenshots
![2022-02-20_1235](https://user-images.githubusercontent.com/100831289/156521699-10e00240-7772-4bd1-b57d-25c86873a15e.png)

![2022-02-20_1259](https://user-images.githubusercontent.com/100831289/156521844-ec4f1105-5e2a-494a-af57-7672ea8170e8.png)

![white bar on top ](https://user-images.githubusercontent.com/100831289/156521886-118f5bbb-7484-4fb8-b585-24db770e4801.png)

**Comment by eramits** [comment]
Hi @stevenbrok 

Can you please disable the topbar from the Customize > topbar > general section to see it fixes the top whitespace issue?

For the mobile menu and submenu, it is working fine on my end. I didn't see any issue with it.

**Comment by MarkHollo** [comment]
Closing this thread due to inactivity and especially since no other or similar issues have been reported. If you continue to experience further problems or experience new ones, please feel free to start a new thread. Thank you very much
