### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ')' in /home/xxxxxxx/wp-content/themes/oceanwp/inc/template-helpers.php on line 349

### ISSUE THREAD

**Issue by limjunk2015** [oceanwp/oceanwp#372]
[31-Mar-2022 20:34:48 UTC] PHP Parse error:  syntax error, unexpected ')' in /home/xxxxxxxxxxxxxx/wp-content/themes/oceanwp/inc/template-helpers.php on line 349

Looks like there is an extra comma on Line 348 with OceanWPVersion: 3.2.1

https://github.com/oceanwp/oceanwp/blob/15871aad9fb6552b71a20ad6323556721796966d/inc/template-helpers.php#L348

It's picked up in most PHP editors as being an error

**Comment by MarkHollo** [comment]
Hello @limjunk2015,

You can resolve the problem by upgrading your PHP to a 7.4+ version, which is the version WordPress strongly recommends, or you can[ check this doc and see how to resolve the problem manually](https://docs.oceanwp.org/article/776-known-bugs-issues#oceanwp).

With the next update, we'll add the PHP 7.2 support as well for those several parts.

Did you notice any other problems perhaps?

**Comment by limjunk2015** [comment]
I am looking at upgrading but as it broke my site after I upgraded I was looking for a quick fix to get the site back up and running. 

Thanks for the info and yes the comma tweak resolves it.
