### ISSUE TITLE
Menu Cart in Customizer not having any effect

### ISSUE THREAD

**Issue by matthewmurdoch** [oceanwp/oceanwp#373]
The menu cart , when changing the color in customizer, it doesnt actually changing anything and cannot override with css as it uses normal Woo classes affecting the whole site
![screenshot-staging radiantweb co za-2022 04 08-09_24_53](https://user-images.githubusercontent.com/14326452/162385497-5189fa99-34e0-4629-9582-7fc3f884093b.png)

**Comment by eramits** [comment]
Hello @matthewmurdoch 

Can you please change the settings that you want and save it? After that reload the site and add/remove a product, then check the mini cart changes you have done.

**Comment by MarkHollo** [comment]
Closing this thread due to inactivity and also because no similar issues or problems have been reported. If you continue to experience this problem further or experience new problems, please feel free to start a new thread. Thank you very much
