### ISSUE TITLE
border-radius on .button doesn't work on frontOffice

### ISSUE THREAD

**Issue by remyrichard** [oceanwp/oceanwp#38]
when i configure the border-radius, i see the preview in backoffice, but not active in frontoffice :(

**Comment by nicolas-owp** [comment]
Hello, can you show me the url where you have this problem?

**Comment by remyrichard** [comment]
For example : here : https://studio-kardamome.fr/mentions-legales/
on "notre formulaire de contact" button.
In Theme button panel, when i edit it,  i see the border-radius, but neither in frontoffice and nor if i return in backoffice and reload it, only when i manipulate the cursor.

**Comment by nicolas-owp** [comment]
Thanks, I will fix this for the next release :)

**Comment by remyrichard** [comment]
Great ! 
If we could set the font of the .button, it would be wonderful too ;)
