### ISSUE TITLE
Update notification always on 

### ISSUE THREAD

**Issue by ady001** [oceanwp/oceanwp#385]
I’m using a child theme for OceanWp and I’ve updated the theme and Extra plugin to the latest version but the admin notice “We made changes to our Theme Panel. To complete the installation and enjoy both old and new features, please make sure the OceanWP theme and all Ocean plugins are up to date“ is appearing every time. I guess this is because I use a child theme..

**Comment by MarkHollo** [comment]
Hi @ady001,

Yes, that was a problem with the child theme (sorry about that), but was taken care of immediately.

Thanks for using OceanWP and if you notice anything else in the future releases, we count on your input :)
