### ISSUE TITLE
Invalid HTML codes

### ISSUE THREAD

**Issue by yoneth** [oceanwp/oceanwp#4]
I've just installed fresh WordPress with OceanWP with Theme Unit Test imported.

There are bunch of invalid HTML codes my testing site: https://validator.w3.org/nu/?doc=http%3A%2F%2Fyellowed-sandpiper.w1.poopy.life%2F

Cheers

**Comment by oceanwp** [comment]
Hello, sorry for this issue, I fixed that :)
