### ISSUE TITLE
Ocean-Extras Color Palettes

### ISSUE THREAD

**Issue by eplanetdesign** [oceanwp/oceanwp#40]
In wp-color-picker-alpha.js the colors are locked in and `add_filter( 'ocean_default_color_palettes, ...` doesn't work.

Request that you comment out or remove line 209 in wp-color-picker-alpha.js:
`// colors    = ['#000000', '#ffffff', '#f44336', '#E91E63', '#03A9F4', '#00BCD4', '#8BC34A', '#FFEB3B', '#FFC107', '#FF9800', '#607D8B'];`

**Comment by nicolas-owp** [comment]
Hello, you can only change the color palette in the customizer not the metabox.
