### ISSUE TITLE
oceanwp-pagination

### ISSUE THREAD

**Issue by ameenahmad707** [oceanwp/oceanwp#408]
oceanwp-pagination is generating redirect

**Comment by ameenahmad707** [comment]
Hi Mr Amit

I am using oceanwp theme on my website and its pagination generating
redirect links on my posts page

Website link is
www.learnsen.com

**Comment by MarkHollo** [comment]
Hi @ameenahmad707 

Please provide more information about the problem. I checked your website, checked your blog page, checked pagination and works as it should. So we need to know exactly what you're referring to so we can understand the problem on your site. Thanks

**Comment by MarkHollo** [comment]
Closing this thread due to inactivity. If you continue to experience more problems or have more details please feel free to start a new thread. Thank you very much
