### ISSUE TITLE
Number List & Gallery CSS

### ISSUE THREAD

**Issue by swostiksatpathy** [oceanwp/oceanwp#41]
On fresh addition or migration from existing to this theme has issues whenever : 
1. the Number List or 
2. the Images Gallery is added to posts
![css issue 1](https://user-images.githubusercontent.com/18367244/35546472-56ca95b0-059a-11e8-81a8-e28557fd3238.png)
![css issue 2](https://user-images.githubusercontent.com/18367244/35546473-56fa064c-059a-11e8-9773-9de9a3d8c27f.png)

Anything with Lists breaks the Content Section.
-- Even the popular SyntaxHighlighter Evolved by Alex Mills (Viper007Bond)

PS: Kudos on the theme otherwise. Fast, Clean and Elegant even for a free theme. Keep up the good work.

**Comment by nicolas-owp** [comment]
Hello, it is on single post? Go to the Blog > Single Post section of the customizer, add 0 to the Full width Content field, tell me if it solves the problem.

**Comment by swostiksatpathy** [comment]
Yes it does fix the issue. Only con to this solution is the layout and spacing from the left margin.
But it still looks good. Videos stretch up a bit. But all in all Thumbs Up.
![result 1](https://user-images.githubusercontent.com/18367244/35602995-1f193726-0661-11e8-9bb1-54cc31d4c701.png)
![result 2](https://user-images.githubusercontent.com/18367244/35602996-1f54a2c0-0661-11e8-909f-c2293a2ec417.png)

Thank you... Keep up the great work.

**Comment by nicolas-owp** [comment]
You're welcome :)
