### ISSUE TITLE
Compatibility with Polylang (templates in the customizer)

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#42]
Hello again,

I am working with Ocean and Polylang. (Not a fan of WPML...)

I see you already registered string for Polylang, it works as expected.

The problem I have, is with OceanWP templates selected in the customizer. For example, all the theme mods like `ocean_footer_widgets_template`.

## How to reproduce ##

In the customizer, I select my "Footer FR" template for the field `ocean_footer_widgets_template`.
![Image](https://i.imgur.com/Myzqn8G.png)

With Polylang, I translated the "Footer FR" into a "Footer EN".
![Image](https://i.imgur.com/TPISb0P.png)

I expected that "Footer EN" template would show up in my english version of the website, instead of the french template.

## Suggestion ##
In https://github.com/oceanwp/oceanwp/blob/master/inc/helpers.php#L3789 you could do as:

```php
function oceanwp_footer_template_content() {

	// Return false if disabled via Customizer
	if ( true != get_theme_mod( 'ocean_footer_widgets', true ) ) {
		return null;
	}

	// Get template ID from Customizer
	$content = get_theme_mod( 'ocean_footer_widgets_template' );

	// Get Polylang Translation of template
	if( function_exists('pll_get_post') ){
		$content = pll_get_post($content, pll_current_language());
	}

	// Get template content
	if ( ! empty( $content ) ) {

		$template = get_post( $content );

		if ( $template && ! is_wp_error( $template ) ) {
			$content = $template->post_content;
		}

	}

	// Apply filters and return content
	return apply_filters( 'ocean_footer_template_content', $content );

}

```

The other theme also need to be translated:
ocean_top_bar_template
ocean_top_bar_social_alt_template
ocean_vertical_header_template
ocean_vertical_header_bottom_template
ocean_header_template
ocean_menu_social_template
ocean_footer_widgets_template
ocean_error_page_template

Since you already partially support Polylang, it would be nice to have a complete compatibility.
Kind regards
Nico

**Comment by nicolas-owp** [comment]
Bonjour, nous pouvons parler Français si vous voulez :)
Je ne connais pas très bien Polylang, vous avez essayer et ça fonctionne si j'ajoute le code dans les templates?
Si oui, je le ferais pour la prochiane mise à jour :)

**Comment by nicomollet** [comment]
Je me dis que sur Github, il vaut mieux parler anglais pour que tout le monde puisse comprendre ;)

Sinon sur https://www.restaurant-caphorn.fr/ et sa version anglaise https://www.restaurant-caphorn.fr/en/ vous pouvez voir que le template sur la zone `#footer-widgets` s'affiche bien en fonction de la langue.
Je n'ai fait le hack uniquement sur cette zone, pas encore sur les autres zones, mais ça devrait fonctionner sur le même principe.

**Comment by nicolas-owp** [comment]
No problem to speak english :)
Thank you for letting me know I will add it for all custom part of OceanWP.

**Comment by nicomollet** [comment]
@nicolas-owp I just checked the master version with the fix for Polylang.

In some cases, like the footer, it doesn't work as expected. `OceanWP_Elementor::get_footer_content()` is called.
It seems we also need to patch the Elementor Class, for all the *_template get_theme_mod

For example on https://github.com/oceanwp/oceanwp/blob/master/inc/third/class-elementor.php#L171 with footer_id and ocean_footer_widgets_template.

should be: 
```php
public static function get_footer_id() {

	// Template
	$id = get_theme_mod( 'ocean_footer_widgets_template' );

	// If template is selected
	if ( ! empty( $id ) ) {

		// Get Polylang Translation of template
		if ( function_exists( 'pll_get_post' )) {
			$id_polylang = pll_get_post( $id, pll_current_language() );
			if ( ! empty( $id_polylang ) ) {
				$id = $id_polylang;
			}
		}

		return $id;
	}

	// Return
	return false;

}
```

Is it possible for you to add this fixes?
Thank you

**Comment by nicolas-owp** [comment]
Hello, I need to add the code only in the class-elementor.php or also in the helpers.php file?
And this way it works perfectly, right?
I ask you because I don't know well Polylang.
If it is good, yes I can add the code.
Thank you :)

**Comment by nicomollet** [comment]
@nicolas-owp The code needs to be in class-elementor.php AND helpers.php.

Everytime you try to `get_theme_mod` for a template, actually.

**Comment by nicolas-owp** [comment]
Okay, I updated the files, can you test and tell me if everything is good?
Thank you.

**Comment by nicolas-owp** [comment]
Thanks.

**Comment by nicomollet** [comment]
Getting the "Uncaught ReferenceError: butterbean is not defined" in Elementor Edit Mode. 
Not sure it is related. Reverting to the latest version to check.

**Comment by nicolas-owp** [comment]
No it is not related, don't worry about this error, you will see nothing wrong with Elementor. It is just the script I use for the OceanWP Settings metabox.

**Comment by nicomollet** [comment]
Elementor editor is not loading at all :( Not just the error in the console.

**Comment by nicolas-owp** [comment]
If you enable WP_DEBUG, do you see an error? I just tried, Elementor works for me.

**Comment by nicomollet** [comment]
Sorry false alert, it was probably a test I left in a OceanWP file.

Je continue de tester ;)

**Comment by nicomollet** [comment]
Alright, the reason for Elementor breaking was some Elementor library widgets didn't have a defined language.

I had to go to Polylang Languages settings page `/wp-admin/admin.php?page=mlang` and "set default language for contents without language" or something like that.

**Comment by nicolas-owp** [comment]
But the custom templates, custom header, custom footer, etc... work with Polylang now?
I need to know because I update OceanWP soon so if it doesn't work I will remove the code I have added.

**Comment by nicomollet** [comment]
Doing the latests checks again with the latest version. Hold on a couple of hours ;)

**Comment by nicolas-owp** [comment]
You have time :)
I mean by soon, this week :)

**Comment by nicomollet** [comment]
Everything is fine for now.
I will submit the new website I am developing once ready.

The last website I made https://www.restaurant-caphorn.fr/ now displays well the english templates, with the latest OceanWP version (master) and latest Polylang version. See header and footer templates.

**Comment by nicolas-owp** [comment]
Perfect, thank you very much for the code and the tests :)

**Comment by nicomollet** [comment]
Me again...

Continuing with the compatibility with Polylang, your plugin `ocean-extra` needs a `wpml-config.xml`.

This config allows translation of the title and the subheading:

```xml
<wpml-config>
    <custom-fields>
        <custom-field action="translate">ocean_post_subheading</custom-field>
        <custom-field action="translate">ocean_post_title</custom-field>
    </custom-fields>
</wpml-config>
```

This should make this plugin with WPML too ;)
Can you add it please?

**Comment by nicolas-owp** [comment]
Hello, sure thing :)

**Comment by nicomollet** [comment]
I just released the new website with OceanWP and Polylang.

You can check it here: https://www.antineahotel.com

**Comment by nicolas-owp** [comment]
Whao, it is very beautiful, well done :)
