### ISSUE TITLE
"Your theme (OceanWP) contains outdated copies of some WooCommerce template files."

### ISSUE THREAD

**Issue by Ver3** [oceanwp/oceanwp#44]
This is the error shown in my WP Admi, due to the known problem caused by Woo's update recently.

Will OWP become independent of this?

I have this quote from another theme dev, I hope this helps you: "Most of the themes available today have overridden WooCommerce templates. That means — anytime WooCommerce team make changes in the template files, the theme can break. Looking at this situation, I'm really glad about the approach we took of not overriding any WooCommerce templates; but using hooks instead. It was a bit more work, and less design freedom. But for crucial integrations such as WooCommerce, reliability comes first!"

Cheers @nicolas-owp

**Comment by nicolas-owp** [comment]
Hello Verdi :)
I know, it is the pagination template, in the next release, I don't use this template anymore but hook so you will don't have this issue.
