### ISSUE TITLE
Import Customizer Styling: Invalid Import Data 

### ISSUE THREAD

**Issue by d3nny89** [oceanwp/oceanwp#445]
I don’t have any child theme so I’m following this guide before updating the main theme:

[https://docs.oceanwp.org/article/90-sample-child-theme](https://docs.oceanwp.org/article/90-sample-child-theme?fbclid=IwAR3lN3g9VgBJmClio2EvlwIDHyOdttWIpnrhlyH3hktzsfXqtJKpHaR-Rfg)

But in the last phase (importing parent style into child theme) I got the error attached in photo: “Invalid Import Data”

Side Note
I've done a test also in the main Ocean WP theme only, exporting Customizer Styling and trying to then re-import the .dat file but I get the same "Invalid Import Data" Issue

What could It be?
Many thanks

![339739292_932900707909080_1317100079556315297_n](https://user-images.githubusercontent.com/9018045/230430388-69127f05-95d2-4829-8d92-c863c594bab3.jpeg)

**Comment by MarkHollo** [comment]
Hi @d3nny89,
