### ISSUE TITLE
Suggestion for extra widgets naming

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#45]
Hello,

Sorry if I post this in the wrong place.

This is related to Ocean Extra plugin.
At the moment, the widgets are named like `&raquo; Custom Menu`.

The `»` doesn't sound standard to me. 
My suggestion would be to rename the widgets to `OceanWP Custom Menu` or `Custom Menu by OceanWP`.

Thanks for considering this.
Nico

**Comment by nicolas-owp** [comment]
Hello, there is one reason for this, because some users want a white label theme, so this way no name is added to the widget and is the user buy the white label extension to change the theme name, the end user will see no brand in the widget page.

**Comment by nicomollet** [comment]
That makes sense, thank your for the explanation.

**Comment by nicolas-owp** [comment]
You're welcome :)
