### ISSUE TITLE
Customizer | Page Title | BG Image height issue

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#47]
Hi Nicolas,
guess I just found a bug.. In Customizer | Page Title | BG Image (no image set, only color overlay selected) -> when you change the height it shows fine within the customizer but the changes are not taken over when published.. The strange thing is that it worked fine, changing it a few times to different values and then it stopped working.. Now it is always height 400px (default) no matter what value I set in Customizer height..
but - E.g Color change etc. is still working.. 

I was able to make the height setting to be saved again with entering a bg image..

Thank you!

Greetings,

stefan

OWP Version: 1.4.16 /plugins (all latest)

**Comment by nicolas-owp** [comment]
Hello, thank you, fixed for the next release :)
