### ISSUE TITLE
Page title background image size being forced as 'Full'

### ISSUE THREAD

**Issue by leecollings-sb** [oceanwp/oceanwp#474]
_Foreword: I raised this as a WordPress support ticket three months ago (https://wordpress.org/support/topic/page-title-background-image-size/), the error had been acknowledged, but I can't find any evidence in GitHub to say it had been raised as an issue or not, so I'm raising it as an issue here myself._

I’m struggling with being able to find a way to use a different image size other than the full size for the page title background image.

There doesn’t seem to be any option to select an image size within WordPress but I thought there must be a hook or filter to be able to change this.

When I found this page (https://docs.oceanwp.org/article/459-alter-the-page-header-background-image) I thought this would be it.

But it turns out (and isn’t very well documented) this only affects the CSS styling for the page title.

It does also mention an image URL but this is for the header, NOT the page title.

I’m trying to simply stop full size images be loaded for the background image on page titles, I’d much rather prefer either medium or large images.

Is there any possible way of doing this via a child theme?

```
// Page Title Background Image Size
function my_page_header_bg_img( $url ) {

	// Get the attachment ID from the URL
	$id = attachment_url_to_postid($url);

	// Get the new URL
	$url = wp_get_attachment_image_url($id, 'medium');

	// Return
	return $url;

}
add_filter( 'ocean_page_header_background_image', 'my_page_header_bg_img' );
```

The value for ‘full’ seems to be hardcoded here https://github.com/oceanwp/oceanwp/blob/7163ab345155fd401f0e507128a2da191bc1475e/inc/helpers.php#L2485

But the filter in my original post should happen BEFORE this line happens, and only if it is a numeric value.

From what I can see, the filter I’ve got SHOULD be working, but it seems to be ignoring it?

**What I'm raising here in summary, is that when selecting an image for the background image on Page Title, it shouldn't force the full size image to be used, it would be nice to be able to select either 'Full', 'Large', 'MediumLarge', or 'Medium'.**

**Comment by eramits** [comment]
Hi @leecollings-sb 

The filter is added and the function is improved to handle the image size. Now you can use the filter `ocean_page_header_background_image_size` to change the size as you need. 

See - [Page title background image size](https://github.com/oceanwp/oceanwp/commit/e39aa32505e27834b2199a1f1b25074e710a1b96)

Branch - [rc-3.5.4](https://github.com/oceanwp/oceanwp/compare/rc-3.5.4)

Let me know if there is any issue related to it.

**Comment by leecollings-sb** [comment]
Hi @eramits,

Thanks for the update! I'll check this out and will pass on any feedback I find.

**Comment by leecollings-sb** [comment]
Hi there, just wanted to re-open this and query this, as I think this may have another flaw in it.

Within the initial parameter passed through this function:

``` function my_page_header_bg_img( $url ) { ``` which is being actioned using ``` add_filter( 'ocean_page_header_background_image', 'my_page_header_bg_img' ); ``` ...

On a page which has had a custom background image applied (when editing the page), the value of $url is always being returned as the default background image set in the Customizer, whereas if a custom image has been set, it should be using that value instead.

**Comment by eramits** [comment]
Hi @leecollings-sb 

Can you please share the complete code of what you want to achieve? Also, please try to change the priority of the filter in your code to something like 25 or 99. 

`add_filter( 'ocean_page_header_background_image', 'my_page_header_bg_img', 99 );`
