### ISSUE TITLE
Page Title Overlay Opacity not being used in Customiser

### ISSUE THREAD

**Issue by leecollings-sb** [oceanwp/oceanwp#475]
The Overlay Opacity slider setting in the WP Customiser seems to have no affect on the front end display.

The Overlay Colour is being set fine, but the setting for Overlay Opacity isn't being used, instead a generic CSS rule in the theme stylesheet is always being used.

![Screenshot 2024-02-13 at 14 58 23](https://github.com/oceanwp/oceanwp/assets/12139008/f9d4f206-504f-4a72-8241-1173e8f7425b)
![Screenshot 2024-02-13 at 14 58 33](https://github.com/oceanwp/oceanwp/assets/12139008/7eba8111-b85a-4e0d-9f0b-fe6fab7c9cb3)

**Comment by skalanter** [comment]
Hello @leecollings-sb,

Thank you for reaching out,

I fully examined the issue you raised in this post and could not see it on my end, and I couldn't reproduce/duplicate it.

Please check the following screenshots:
I. https://postimg.cc/F1KmjD7M
II. https://postimg.cc/F7Bn2xFJ

It might affected by three things:
1. **Cache:**
If you have any cache plugin or server cache(CDN / Browser Cache and Cookies and ...), you need to clear its cache contents or disable them to see your changes.
To clear cookies, use this icon: https://postimg.cc/0rtp7SS9.
To refresh the page, please follow the steps explained in this link:
https://www.documate.org/automation/what-is-a-hard-refresh-how-to-do-a-hard-refresh-in-any-browser/
https://www.usmobile.com/blog/how-to-do-a-hard-refresh-on-your-browser/ 

2. **Plugin conflicts:**
In this case, deactivate all other plugins, then activate them one by one and check for this issue. Continue doing this until you find out what product is causing a conflict.

3. **Different settings under the page settings:**
Please check OceanWP settings under the edit page/post > Title: https://postimg.cc/CnHScQpD Try to set those options somewhere in the customizer that does not have special settings on the page.

_

If you have any more questions, please join our Facebook group for support. We don’t monitor GitHub for support.

**Facebook Community Support Group:**
​https://www.facebook.com/groups/oceanwptheme/  

I hope it helps.

Thank you for understanding.
Best Regards
