### ISSUE TITLE
Where is 3.5.8 changelog?

### ISSUE THREAD

**Issue by jeroenrotty** [oceanwp/oceanwp#483]
I have https://github.com/oceanwp/oceanwp/blob/master/changelog.md bookmarked to check your changelog when new versions come out, yet I don't see 3.5.8 on that page. Where is the changelog?

**Comment by skalanter** [comment]
Hello @jeroenrotty,

Thank you for reaching out,

The changelog for the new version(s) is always available at the related branch.
For example, the changelog for the current version is included at the following links: https://github.com/oceanwp/oceanwp/blob/rc-3.5.8/changelog.md.

Also, you'll find it at this link:  https://docs.oceanwp.org/article/653-oceanwp-theme-changelog.

Now it is available here too: https://github.com/oceanwp/oceanwp/blob/master/changelog.md.

_______

**Please note that** if you have any more questions or want to continue this conversation, please join our Facebook group for support. So you can share the details as explained above on our Facebook support page.

We don’t monitor GitHub for support.

Facebook Community Support Group: ​https://www.facebook.com/groups/oceanwptheme/

I hope this helps.
And thank you for understanding,
Best Regards

**Comment by jeroenrotty** [comment]
Too bad you're only on Facebook then. I'm not on any meta products whatsoever. But thank you for including it at the link provided.
