### ISSUE TITLE
Custom css enqueue code needs update for custom wp folders

### ISSUE THREAD

**Issue by takispap** [oceanwp/oceanwp#50]
I just found out that when selecting Custom File in _General Styling > Styling Options Location_ the theme tries to enqueue the css file from the default uploads folder (wp-content/uploads) which is hardcoded.

Not all wp installs have the default folders, which breaks the site's styling options.

https://github.com/oceanwp/oceanwp/blob/7ede8019e07a2960cb4310ea766e7a79914100c1/functions.php#L737

**Comment by nicolas-owp** [comment]
Hello, unfortunately, I can't do this in another way, if you don't use the uploads folder, you can select the other option to add the css code in the wp_head.

**Comment by takispap** [comment]
Wouldn't something the code below do it?

`$uploads = trailingslashit( $upload_dir['basedir'] );
wp_enqueue_style( 'oceanwp-custom',  $uploads . 'oceanwp/custom-style.css', false, null );`

**Comment by nicolas-owp** [comment]
Hi, yes you have totally right, I don't know why I don't done that, thank you very much :)

**Comment by takispap** [comment]
;)
