### ISSUE TITLE
Update from 1.4.7 to 1.5.4 broke header menu

### ISSUE THREAD

**Issue by hbnxcoder** [oceanwp/oceanwp#53]
I updated from 1.4.7 to 1.5.4 and broke the styling of my menu. 

Wordpress 4.9.4

![bildschirmfoto 2018-02-20 um 18 06 28](https://user-images.githubusercontent.com/36673218/36438163-54da5bc0-1669-11e8-8571-f8dea0b27423.png)

**Comment by hbnxcoder** [comment]
The problem was Ocean Extra 1.4.4. Deactivated it!

**Comment by nicolas-owp** [comment]
Hello, go to Theme Panel > Scripts & Styles, if everything is disabled, check everything, click Save Changes, then go to wp-content/uploads and delete the oceanwp folder.
