### ISSUE TITLE
[Feature Request/Question] update safe language files 

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#54]
Hi Nicolas,
as many seem to have troubles with this..

1. Are the languages files in oceanwp/languages update safe, or will they be overwritten when one updates the theme (and there are new languages files provided by you)?

2. If yes, I read here: https://localise.biz/wordpress/plugin/faqs/files-deleted  that some themes provide an update safe place for language files.. Is there such a place in OWP?

3. Or to make them update safe while using a childtheme, can I just copy the languages folder to the childtheme to make them update safe?

Thank you!

Have a great day!

stefan

**Comment by nicolas-owp** [comment]
Hello, if you want to translate OceanWP, just send me the translate po and mo files, then I will add them directly into the languages folder so no problem with future updates. Otherwise, yes, the update will remove those files.

**Comment by stevek28** [comment]
Hi Nicolas, thx for your answer!

I was asking this questions since sending the po mo files to you so you integrate them in the next theme version isn't really a super solution;-) As different people make/need different translations even for the same language.. e.g one uses formal german, one not etc.

So if one wants he's own translation and wants to use and keep this exact one, the problem of overwriting during theme update persists.. Therefore I asked questions 2. and 3.

Or do you propose a better way to handle this?

Thx for your answer!

stefan

**Comment by nicolas-owp** [comment]
Hello, I think that the best thing to do in your case would be to use a plugin to translate your site so when you will update OceanWP you will lose nothing. Because adding a languages files in the child theme is to translate words in the child theme, not the parent theme.

**Comment by stevek28** [comment]
Thank you Nicolas! So you mean e.g. Loco translate, right?

**Comment by nicolas-owp** [comment]
Yes a plugin like that :)

**Comment by stevek28** [comment]
Great thx! Have a nice afternoon!

**Comment by nicolas-owp** [comment]
You're welcome, you too :)

**Comment by nicomollet** [comment]
@nicolas-owp you could invite users to complete the translations in Rosetta https://translate.wordpress.org/projects/wp-themes/oceanwp

Rosetta translations (with a language pack) override the `.mo` files in /languages/ FIY. The /languages/fr_FR.mo is not used by OceanWP since there is a language pack for French.

**Comment by nicolas-owp** [comment]
Yes, true, even better :)

**Comment by AhmedSuror** [comment]
If I created my own .mo language file and put it under the languages folder, will that work?
