### ISSUE TITLE
Cannot Write Custom Meta Data to Product Line

### ISSUE THREAD

**Issue by Fellowfromearth** [oceanwp/oceanwp#55]
I am using a plugin that works on Avada and takes custom images uploaded by customers and adds them to their corresponding order. The images are conveyed to the backend system. For some unidentified reason, this function does not work either due to thematic issues or something introduced by version 3.3.3. Any help?

**Comment by nicolas-owp** [comment]
Hello, I have answered to your topic on the forum, it is better to keep this in one place.

**Comment by Fellowfromearth** [comment]
Where?

**Comment by nicolas-owp** [comment]
Here: https://wordpress.org/support/topic/cannot-write-custom-meta-data-to-product-line/
