### ISSUE TITLE
Shortcode in ocean_library gets fatal error when saving in admin

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#56]
Hello I am using the shortcode `[oceanwp_woo_cart total=true]` in an Ocean Library template.

When saving the post in the admin, I get a fatal error:
`Fatal error: Uncaught Error: Call to a member function get_cart_total() on null in /wp-content/plugins/ocean-extra/includes/shortcodes/shortcodes.php:436`

I guess `WC()->cart` is not defined in admin. Shouldn't we test the existence of the function, or simply add a condition `if(!is_admin()){}` in all the functions for the shortcodes?

Thank you

**Comment by nicolas-owp** [comment]
Hello, it is in the default WordPress editor? No a page builder? If yes, I will need to add if is not admin.

**Comment by nicomollet** [comment]
Yes, it is the default WP editor. Not in a page builder.

**Comment by nicolas-owp** [comment]
Okay, I will add is_admin to avoid the error.
