### ISSUE TITLE
Header menu displayed even when no menu

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#57]
Hello again,

My new website https://www.residence-neptunia.com/ is a one page website.

I don't have a main menu and the bug is `#site-navigation` is showing html markup with empty menu items. Which is not valid html indeed.

Not sure how to fix this, can you help?

Kind regards

**Comment by nicolas-owp** [comment]
Hi, that is very weird, can you create a menu in Appearance > Menus, add menu items to it, check Main Menu, save, then remove the menu and check if you have the markup again.

**Comment by nicomollet** [comment]
If I create an empty menu, it doesn't change anything.

When I assign it to "Main", the empty menu items disappear but the `<nav id="site-navigation">` is still displayed though.

If a delete the menu, the  `<nav id="site-navigation">` is not displayed anymore in the html markup. So it is now fixed. Thank you very much.

See it live on https://www.residence-neptunia.com/

Closing the issue.

**Comment by nicolas-owp** [comment]
I don't know why you had this issue but glad that it is fixed :)
