### ISSUE TITLE
Bug with stripe and the new pay method (step method)

### ISSUE THREAD

**Issue by Joss47** [oceanwp/oceanwp#61]
Bonjour !

Je viens de remarquer que les paiements via stripe en mode "Paiement en plusieurs étapes", si on a plusieurs modes de paiement, stripe ne fonctionne pas avec ce nouveau mode.
Si je bascule sur l'ancien mode classique, le paiement abouti sans soucis.

**Comment by nicolas-owp** [comment]
Bonjour, pouvez vous télécharger le thème ici sur github et me dire si vous avez le même problème?
Merci.

**Comment by Joss47** [comment]
Négatif, le bug est toujours la :/

**Comment by nicolas-owp** [comment]
Quel est le problème exactement? Lorsque vous essayer de payer via Stripe la page se charge, ça retourene une erreur?

**Comment by Joss47** [comment]
Juste ici > https://jayant.fr/manzocco/ , ajouter un produit au panier, à l'étape du checkout (sans compte nécessaire, stipe en mode test) vous allez voir le problème.
Si je switch sur l"affichage classique le paiement se déroule correctement

**Comment by nicolas-owp** [comment]
Le problème est lorsque je remplit tous les champs et que j'essaie de payer, j'ai cette erreur:
Le traitement du paiement a échoué. Merci de réessayer.

C'est bien ça?

**Comment by Joss47** [comment]
Voila, on a rien de plus et seulement dans ce mode Stripe ne fonctionne pas avec OceanWP.

**Comment by nicolas-owp** [comment]
D'accord, je vais voir ça en local et fixer ce problème. Merci de me l'avoir signalé :)

**Comment by nicolas-owp** [comment]
Avez vous ajouté quelque chose de spécifique? Je viens d'essayer sur mon site en local, il n'y a aucun problème, la commande est passé.
Je peux essayer de voir quel est le problème sur votre site, créez un ticket pre-purchase et envoyez moi les informations d'un compte admin.

**Comment by Joss47** [comment]
Rien du tout, j'ai même désactivé toutes les extensions autres que celle recommandée avec OceanWP.
Ok ça marche

**Comment by nicolas-owp** [comment]
Je vais essayer de voir quel est le problème car pour moi ça fonctionne.

**Comment by Joss47** [comment]
C'est envoyé !

**Comment by nicolas-owp** [comment]
Le problème vient de vos clés publique et secrète, j'ai essayé avec mes propres clés et ça fonctionne, c'est pour ça qu'aucun autre utilisateur n'a ce problème.
Créez de nouvelles clés sur votre compte Stripe et réessayez.

**Comment by Joss47** [comment]
Etrange, pourquoi cela passe alors quand seulement stripe est activé et quand j'active un autre mode de paiement cela fonctionne O_o, j'ai pourtant déjà changé les clés, je vais le re faire

**Comment by nicolas-owp** [comment]
Je ne sais pas du tout. En tout cas maintenant on sait d'où ça vient :)
Je trouvais ça bizarre car je n'ai pas touché au moyen de paiements.

**Comment by Joss47** [comment]
haha, je viens de générer des nouvelles clés, ajouts ok en back office.
J'active PayPal aussi, pour avoir deux modes de paiements > le paiements stripe ne passe pas

**Comment by nicolas-owp** [comment]
Dîtes moi si cela fonctionne en changeant vos clés, peut-être que c'est un setting mal configuré sur votre compte Stripe.

**Comment by Joss47** [comment]
Je désactive PayPal, le paiement stripe passe -_-

**Comment by nicolas-owp** [comment]
Je viens d'essayer avec des clés live de PayPal, et Stripe fonctionne. Pouvez vous essayer de générez de nouvelles clés PayPal? Ou essayer en mode sandbox pour voir si le problème vient bien des clés.

**Comment by Joss47** [comment]
PayPal fonctionne bien.
Si on prends les deux cas  > Stripe comme paiement seulement avec mes clés : le paiement passe.
Stripe comme paiement avec le paiement par cheque > le paiement ne passe pas.

Maintenant si on migre sur la version de paiement d'Ocean sans le système de paiement en plusieurs étapes >  dans les deux cas ça fonctionnne.

**Comment by nicolas-owp** [comment]
Pouvez vous me donner les étapes pour reproduire le problème? Je vais voir ça sur mon site demain.
Merci.

**Comment by Joss47** [comment]
Pas de soucis, c'est rapide :)

Configuration : paiement actif >Stripe - PayPal - Cheque

Les paiements fonctionnent sans soucis en mode affichage classique.

Quand la case (dans le customizer de WP) qui se trouve dans WooCommerce > Panier/Paiement > Paiement en plusieurs étapes est activée, la configuration de paiement comme indiquée ci-dessus ne fonctionne pas.
Le paiement passe dans ce mode la si j'ai uniquement Stripe comme mode de paiement activé.

Les paiements fonctionnent sans soucis pour les autres modes de paiement, seul Stripe pose problème.
Le soucis de clés, je pensais également, mais en mode d'affichage classique cela fonctionne, donc je doute que cela provienne des clés.

Merci d'avance !

**Comment by nicolas-owp** [comment]
Bonjour, j'ai essayé avec/sans PayPal, uniquement Stripe, avec chèque, ça fonctionne très bien, je ne sais pas du tout pourquoi vous avez ce problème en multi-checkout.

**Comment by Joss47** [comment]
C'est vraiment très étrange.
Tant pis pour moi, j'utiliserai l'ancien mode de visualisation du checkout.
Je verrais sur un nouveau site client avec la même configuration si le soucis est encore présent.

**Comment by nicolas-owp** [comment]
Oui je pense que c'est la meilleure chose à faire :)
Je ferme ce topic, n'hésitez pas à le commenter si vous avez toujours ce problème sur d'autres sites.
