### ISSUE TITLE
Reset password form alignment

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#62]
Hello again,
I just found a CSS issue on the reset password page. The page you see after requesting a new password and clicking on the link in the notification.

The "password again" field is aligned right with a 48% width.

See the capture.
![image001](https://user-images.githubusercontent.com/108828/37038146-4cddcd26-2154-11e8-93a1-0033bb24150f.jpg)

Not sure how to fix it.
Thank you

**Comment by nicolas-owp** [comment]
Hello, how can I reproduce the issue?

**Comment by nicomollet** [comment]
Like this:

1. Request a new password on a frontend with WooCommerce
2. Click on the link in the email notification
3. The form displayed is not aligned

**Comment by nicolas-owp** [comment]
Oh thanks, fixed for the next release: )
