### ISSUE TITLE
[BUG] [Feature Request] Woocommerce | Single Product | Product navigation 

### ISSUE THREAD

**Issue by stevek28** [oceanwp/oceanwp#64]
Hi Nicolas,

1. Found a bug in the product navigation. It doesn't cycle through all products within the product's category. Leaves out at least one product during the cycle... 

E.g. Shoes demo /sandals/ "sort by newness (date)", Grid View.
https://shoes.oceanwp.org/product-category/sandals/?orderby=date

**Example 1 to  reproduce:** When you start the cycling with the first one "Skelter Heeled Sandals" 
"Rose Gold Barely Sandals" and "Rose Gold Strappy Sandals" are left out when you cycle through all.

**Example 2 to reproduce:**  
Click "Metallic Heeled Sandal" . Now left should be "Rose Gold Barely Sandals" but is "Clear Block Heeled Sandals" instead. Right is correct: "Aster Clear Strappy Sandals". 
Go to right "Aster Clear Strappy Sandals" then left is correct"Metallic Heeled Sandal" while right is "Sandal With Cross Over" (last one) while it should be "Rose Gold Strappy Sandals", ....

As far as I see you do not (cannot?) take the sorting method set in grid/list view into account but always use "sort by date" for the cycling process which causes even more strange navigation behavior for all other sorting methods than "sort by newness (date)"...

2. Besides that, a **Deactivate CM Option /or  code for the image thumbs shown when hoovering over the nav icons would be super.** 

Thank you!

Greetings,

stefan

**Comment by nicolas-owp** [comment]
Hello, it is by "product_cat" I can do nothing about that, the products are searched by categories but probably not by date.
To remove the thumbnails, use this css code:
```
.owp-product-nav li .owp-nav-thumb {
    display: none;
}
```
