### ISSUE TITLE
WooCommerce mini cart styles when on cart page

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#67]
Hello
The mini cart (on hover the cart icon) works well with Ocean styles, see:
![otherthancart](https://user-images.githubusercontent.com/108828/37391685-3282d9bc-276c-11e8-9b60-e8d5b480b7ff.jpg)

When on the cart page, the mini cart is empty (normal behaviour), but the Ocean styles are still applied (border+background).
![cart](https://user-images.githubusercontent.com/108828/37391714-4cfe28f0-276c-11e8-990a-158f60e2a62d.jpg)

It should be resolved by appliying styles to `.current-shop-items-dropdown .widget_shopping_cart` instead of `.current-shop-items-dropdown`

Thank you.

**Comment by nicolas-owp** [comment]
Hello, I don't know why you have this issue because in the caret and cart, there is no mini cart, add a product in the cart with this demo: https://store.oceanwp.org/shop/
You can see that there is no mini cart.

**Comment by nicomollet** [comment]
In fact, I use the `[oceanwp_woo_cart]` shortcode inside a template assigned to a "top bar" zone.

**Comment by nicolas-owp** [comment]
Hi, I will add the shortcode in my top bar to check if I can reproduce the issue.

**Comment by nicolas-owp** [comment]
Fixed for the next release of Ocean Extra :)
