### ISSUE TITLE
can not remove site background after importing demo content

### ISSUE THREAD

**Issue by codeagencybe** [oceanwp/oceanwp#68]
I have found a bug or at least an irritating issue that happens after importing demo content. 
I don't know if it's a OceanWP issue or a specific WP Customizer issue, but here we go:

When importing demo content (e.g. construction demo), there is a site background image from the brick wall very light. 
But when you go to customizer settings, no image is set to change or remove that points to this brick wall. 
The buttons for removing or changing the image ar not there

So when I go to general styling where to apply site width and background color, I set a different color but nothing changes so it is very confusing. 

Sure I can also delete the image file from media library, but that is no a clean way, and it leaves a 404 broken link. 

How to solve the issue:
1. go to customizer setttings to change the background image and select the same file or another image file
2. now you have the options to change image or delete the image
3. now click delete
And now finally the brick-wall image is gone

Here is screenshot:
AFTER DEMO IMPORT: http://sharing.codeagency.be/0K082Z0C0s1d
AFTER APPLY "FIX": http://sharing.codeagency.be/2s340n3m2g2f

You can replicate this issue with all demo content that has background image. 
If somebody can confirm please?

**Comment by nicolas-owp** [comment]
Hello, yes, I'm aware of this issue, unfortunately, I can do nothing, there is the exact same issue if the demo is imported manually, you will have no image selected, it is a WordPress issue. Your solution is good, you need to select an image, save, then remove it and save again.

**Comment by codeagencybe** [comment]
Hello Nicolas,

Ah ok, sorry Nicolas! 
So it seems to be a Wordpress issue. As I started my topic, I already said I didn't know for sure. But thanks for confirmation anyway! Now I know where it comes from and how to workaround. 

Perhaps it would be good to make some note about this and mention it in the documentation for other users how to import demo content. Because I have lost a lot of time searching for this and now it seems an issue/limitation from Wordpress itself. 

Thanks!

**Comment by nicolas-owp** [comment]
Hi, you're right, I will add a note in the article to import a demo. Thank you :)
