### ISSUE TITLE
header and footer width not full width when set to full width

### ISSUE THREAD

**Issue by codeagencybe** [oceanwp/oceanwp#69]
After importing construction demo site, I change the site width settings to full width (not boxed) and set width to 1600px
But the header and footer stay fixed at 1200px

When I change to boxed layout with 1600px,  then the header and footer do change accordingly. 

When I check the CSS details, I notice in full width settings, there is CSS applied that fixates the container width to 1200px, but it's not inside the custom CSS/JS section

See attached screenshots
full width layout
<img width="223" alt="schermafbeelding 2018-03-15 om 12 30 56" src="https://user-images.githubusercontent.com/7568546/37460853-cf38f378-284c-11e8-90c3-6d441d041f07.png">

boxed layout
<img width="243" alt="schermafbeelding 2018-03-15 om 12 30 12" src="https://user-images.githubusercontent.com/7568546/37460854-cf525912-284c-11e8-884a-7d582872ce75.png">

recording: http://sharing.codeagency.be/1t242b2i1C0W

**Comment by nicolas-owp** [comment]
Hi, can you show me the site url where you have this problem?

**Comment by codeagencybe** [comment]
Hello Nicolas,

Currently working on a new project on a test server here: https://aks.nieuwesite.online

Did you check the link to the screen recording yet? It shows very precise the issue when switching between boxed and full width layout. 
recording: http://sharing.codeagency.be/1t242b2i1C0W

I have tried it on another fresh install (currently already deleted again), and I could replicate the issue again and again. 
I was using the construction demo, so I can't say if it only happens with this theme or if there are others too, but this what I can keep replicating with construction theme. 

FYI, I have only these plugins installed:
- OceanWP theme
- OceanWP premium bundle
- OceanWP whitelabel
- OceanWP sticky header
- Ocean Elementor Widgets
- Ocean Extra
- Elementor
- Elementor Pro
- Central Color Palette
- Granular Controls Elementor

**Comment by nicolas-owp** [comment]
Hi, the issue comes from the "Widgetkit For Elementor", because the plugin uses the same container class than the theme, you will need to check this with the plugin author.
