### ISSUE TITLE
Page Layout Selection not working

### ISSUE THREAD

**Issue by bensteers** [oceanwp/oceanwp#7]
None of the page layout theme mods in the Wordpress customizer panel are working. I try and select a different layout, but it never actually changes the layout. It is happening on both regular pages and archive pages and has been an issue on two different sites.

This is the theme mod I'm referring to:
![screen shot 2017-07-01 at 23 35 34](https://user-images.githubusercontent.com/6741720/27767060-2326e0a0-5eb6-11e7-9577-cc3031f12e21.png)
However the archive page is still rendering with a stubborn right sidebar.

I am running Wordpress 4.8 with OceanWP 1.2.8.

**Comment by oceanwp** [comment]
Hello, there are several layout for several places of the theme, blog, pages, WooCommerce, etc. So for the page layout, it's in General Options > General Settings.
