### ISSUE TITLE
Cart icon twice (mobile)

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#71]
Hello
Having some problems with the menu cart icon, even with latest OceanWP 1.5.7.

It is displayed twice on mobile.

My options are:
* Header: medium
* Cart menu visibility: disabled_desktop

It looks like this combination fires the  `oceanwp_wcmenucart_menu_item()` function twice.

Thanks!

**Comment by nicolas-owp** [comment]
Hi, solved in OceanWP 1.5.8 :)

**Comment by nicomollet** [comment]
Thanks ;)
