### ISSUE TITLE
Reorder Content on WooCommerce Single Product Page in OceanWP

### ISSUE THREAD

**Issue by Fellowfromearth** [oceanwp/oceanwp#72]
I cannot find where to rearrange element contents on the Woocommerce integration with OceanWP. I have tried to reorder the content-single-product.php and add and remove priority assignments on the woocommerce plugin and have uploaded the as necessary with no success. Anyone had to deal with this or know which file to address?

**Comment by nicolas-owp** [comment]
Hello, you can re(order them via the WooCommerce > Single Product section of the customizer.

**Comment by Fellowfromearth** [comment]
Unfortunately, it's not that easily especially if you have at least 1 active plugin...

**Comment by nicolas-owp** [comment]
What do you mean?
