### ISSUE TITLE
hamburger menu displaying all the time

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#73]
Just updated and noticed that using the "Medium" header style that the hamburger menu now displays continuously, no matter what breakpoint is selected for display.

**Comment by nicolas-owp** [comment]
Hello, it is just a cache issue, clear your cache. Also, if you have disabled any script, click Theme Panel > Scripts & Styles, click Save Changes, then clear your cache.

**Comment by codeagencybe** [comment]
This issue is still not resolved. 
I have latest version of both OceanWP and Elementor Pro, and still the hamburger menu is shown on the desktop version. 

I have cleared all possible cache multiple times, hence it stays there. 
URL: https://transcoma.be

**Comment by nicolas-owp** [comment]
Hello, go to Theme Panel > Scripts & Styles, click Save Changes, then clear your cache. Tell me if it solves the issue.

**Comment by codeagencybe** [comment]
Hello Nicolas,

Thanks, saving that page and then clearing cache fixed the issue! Without re-saving that specific page, it does not work.

**Comment by nicolas-owp** [comment]
You're welcome :)
It is the css file who need to be re-generated.
