### ISSUE TITLE
Search Form

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#74]
There was a useful quirk in the previous version that allowed the hiding of the search form in the header, by selecting "header -> menu" and setting search icon style as disabled.

This meant that using the medium header style, the search box element still occupied space and kept the layout centred. I realise this was probably a bug that's been fixed but disabling the seach form but maintaining the relative positioning of other elements would be useful

**Comment by nicolas-owp** [comment]
Hello, to disable the search icon in the navigation for the medium header style, you just need to go to the Header > Menu section of the customizer and select Disabled in the "Search Icon Style" field.

**Comment by deebz** [comment]
I was referring to the search form in the header css id #medium-searchform
By disabling the menu search icon in the old version this caused the search form to disappear but retain the same layout.

setting the css to:

`#medium-searchform {
	display:none;
}`

hides the header search box and retains the layout as before. maybe useful to be able to hide this in a future update without the need for the css over-ride?
