### ISSUE TITLE
Oceanwp Product sharing plugin has errors after upgrade theme to ver 1.5.9

### ISSUE THREAD

**Issue by tonytanlh** [oceanwp/oceanwp#75]
Owp Product sharing plugin has errors after upgrading theme to ver 1.5.9: 
sharing on twitter, and sharing on Pinterest did not work. Error in the auto-generated urls found when sharing the product. checkout this : https://inpasar.com/product-category/watch/

**Comment by nicolas-owp** [comment]
Hello, can you show me a little video of the problem? When I click the twitter button, there is nothing wrong.

**Comment by tonytanlh** [comment]
share on facebook ok

**Comment by tonytanlh** [comment]
when testing oceanwp social share on twitter, found there is automatic generated double @@ in front of the twitter user name
![double at](https://user-images.githubusercontent.com/37864848/38039303-8cf11534-32df-11e8-9b9a-7e4509edf752.png)

**Comment by nicolas-owp** [comment]
Thanks for the double handle, I updated the plugin. For the url issue, maybe it is a conflict, go to the General Options > General Settings of the customizer and disable the "ENABLE OPENGRAPH" setting.

**Comment by tonytanlh** [comment]
Thanks for the updated plugin of social share, for the url issue of product share, I did minor touch-up on the code of the product share plugin, now my problem solved. BTW, I had played with the "ENABLE OPENGRAPH" setting, but it seems having no effect on the url issue.

**Comment by nicolas-owp** [comment]
Hi, you're welcome :)
So the url issue is solved?

**Comment by tonytanlh** [comment]
Yes, problem solved, thanks !

**Comment by nicolas-owp** [comment]
Glad to hear that :)
