### ISSUE TITLE
My orders "view order" button missing icon

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#76]
Hello,

In `/my-account/orders/` the button "View" has no icon, where I guess it should have one.
No font family maybe?

See the screenshot.

![ordericons](https://user-images.githubusercontent.com/108828/38098289-f586bb56-3377-11e8-9c71-eddafab1871e.PNG)

Thanks

**Comment by nicolas-owp** [comment]
Hello, thank you, fixed for the next release :)
