### ISSUE TITLE
Broken customizer

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#77]
Hello

After updating to 1.5.10, I noticed the "add to cart button" in my single product pages disappeared  (Which is itself a big problem!).
I went to Customizer > WooCommerce > Single Product and "Quantity and add to cart" was unchecked.
I checked it. It make the "add to cart button" appear again in my frontend.

Problem now is I can't use the Customizer anymore:
![customizr](https://user-images.githubusercontent.com/108828/38364504-4cba59da-38d9-11e8-9094-0109cc0264ca.PNG)

Can you fix it?
The only log I have in the debug.log is:
`PHP Notice:  Array to string conversion in /home/html/samba/cosmetique/wp-includes/formatting.php on line 1045`

Thank you

**Comment by nicolas-owp** [comment]
Hello, follow this article: https://docs.oceanwp.org/article/510-add-to-cart-button-missing
