### ISSUE TITLE
Keep footer on bottom - fixed

### ISSUE THREAD

**Issue by paaljoachim** [oceanwp/oceanwp#78]
Hey

It would be good to add code to fix the footer to the bottom.
Or add a fixed footer checkbox to the Customizer -> Footer bottom area. (Just under enable footer bottom.)
Or have code that people want to see added to the child theme functions and style.css.

Have a great day!

**Comment by rindoshingen** [comment]
Hey there, 

There is an option to fix the footer to the bottom. In the customizer, make sure "Footer Widgets" is enabled and the option for the fixed footer is there. Works great for me. 

Even if you don't used the Footer Widgets option, you can still enabled the fixed footer in that area and then disable the Footer Widgets and all still works. =)

Cheers
Mike

**Comment by paaljoachim** [comment]
Man I just saw it...
Thanks Mike..:)

**Comment by rindoshingen** [comment]
Excellent. =)
