### ISSUE TITLE
Mobile Menu appearing near logo even in desktop version

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#79]
I noticed that the latest version of the theme show this problem in every site i used the oceanWP theme

![image](https://user-images.githubusercontent.com/16102074/38456797-d49b8a8a-3a88-11e8-8139-a96185533779.png)

you can check here: https://www.iciappinari.it/

**Comment by HartLarsson** [comment]
I noticed that if i dusable the JS : full screen mobile and save the options the error disappears.
Probably was some parameters unsaved during the update?

**Comment by renehamburger** [comment]
For us, Sticky Header stopped working, too. Could this be related?

**Comment by renehamburger** [comment]
Actually, after a few more (apparently insignificant) changes to the header layout, this issue is resolved and Sticky Header works again, similar to @HartLarsson's second comment.

**Comment by nicolas-owp** [comment]
Hello, it is just a cache issue, the CSS file need to be re-generated, just click the Save Changes button in Theme Panel > Scripts & Stylezs, then clear your cache and that will fix the issue :)
