### ISSUE TITLE
Warning:  preg_match() 

### ISSUE THREAD

**Issue by jimmychoxiling** [oceanwp/oceanwp#81]
Warning: preg_match() expects parameter 2 to be string, array given in /home/gadhentravel/public_html/wp-content/themes/oceanwp/header.php(1) : runtime-created function on line 1

**Comment by nicolas-owp** [comment]
Hello, what is your PHP version? If it is not PHP 7, upgrade to it and tell me if it solves the issue.

**Comment by nicolas-owp** [comment]
Hello, having no answer from you, I assume that your issue is solved. Feel free to reach me again if you have any problem with the theme.
