### ISSUE TITLE
Floating add-to-cart bar alignment incorrectly if using boxed layout style

### ISSUE THREAD

**Issue by tonytanlh** [oceanwp/oceanwp#82]
If we choose the boxed layout style at general options > general setting>boxed layout style, and use floating add to cart bar at single product page setting, the floating add to cart bar will have miss alignment issue of unable to align to the center of the line. 

No problem if using wide layout style setting: general option > general setting > wide layout style

Is this a bug?

**Comment by nicolas-owp** [comment]
Hello, yes it is bug, fixed for the next release, thank you for letting me know :)
In the meantime, you can use this css code:
```
.boxed-layout .owp-floating-bar {
    width: 1280px;
}
```

**Comment by tonytanlh** [comment]
Thanks for your fast response, the above css works for desktop , but it seems affect mobile devices, please consider mobile devices as well for your next release.  :)

**Comment by nicolas-owp** [comment]
Oh yes, sorry, yes you can be sure that it will work on mobile too :)
