### ISSUE TITLE
Modal Window: allow additional events on open

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#83]
Hello

This is about Ocean Modal Window.

I want to open a modal, and bind another event to the button that opens the modal.
In the current state I can't.

`oceanwpInitModal()` has a `return false;` that prevents additional events.
Instead you could use `e.preventDefault();` (with `e` has a parameter of the function, without changing anything in the behaviour of this plugin.

Thank you for considering this.

**Comment by nicolas-owp** [comment]
Hello, I will fix this for the next release :)
Thank you.
