### ISSUE TITLE
Wishlist Button

### ISSUE THREAD

**Issue by voznyuk-design** [oceanwp/oceanwp#87]
Hi! Excellent theme, Nick!

I want to make the "Add to Wishlist" button after the "Add to cart" button. Maybe you can tell me how to do this?
![group](https://user-images.githubusercontent.com/11272575/40197557-6ffeec9e-5a1c-11e8-9723-fa27707ca542.png)

**Comment by nicolas-owp** [comment]
Hello, thank you :)
Add this css code:
```
.tinv-wraper.tinv-wishlist {
    display: inline-block;
    margin-left: 20px;
    line-height: 1;
    vertical-align: top;
}
```
