### ISSUE TITLE
Blog Grid is broken

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#88]
Hello

I am using Blog Entries in the customizer.
With the option Style = Grid, the entries are not displayed in columns.

It seems to be missing a call to `oceanwp_blog_wrap_classes` to wrap the entries in a `oceanwp-row` class.
Can you fix this?
Thank you

**Comment by Kezaro** [comment]
@nicomollet I am also experiencing the same problem with blog entries set to Grid style. Happened after updating the theme to version: 1.5.14. Until an official fix is made, a temporary css fix can be used on the class "blog-entry.grid-entry". For example I use a 3 column blog layout so to achieve that I added custom css in the customizer:

.blog-entry.grid-entry {
    float: left;
    width: 30%;
    margin: 0% 1.5%;
}

note once the official fix is made, remove the custom css for the class "blog-entry.grid-entry". Hopefully its fixed as soon as possible.

**Comment by nicomollet** [comment]
This is fixed. Thank you!
