### ISSUE TITLE
Display Floating Bar doesn't redirect to cart page

### ISSUE THREAD

**Issue by TATIYA** [oceanwp/oceanwp#89]
Hello,
First thank you for this amazing theme.
The Display Floating Bar add to cart override woocommerce settings Products > Add to cart behaviour "Redirect to the cart page after successful addition" it use AJAX!

Thanks in advance

**Comment by tonytanlh** [comment]
Yes, have similar issue, need to refresh the page to see the cart

**Comment by nicolas-owp** [comment]
Hello, you're right, I forgot about this setting :)
Fixed for the next release.
Thank you for letting me know.

**Comment by tonytanlh** [comment]
Awaiting for the next release...

**Comment by nicolas-owp** [comment]
Hi, you can use the GitHub version, the issue is fixed :)
