### ISSUE TITLE
Microdata problems

### ISSUE THREAD

**Issue by HartLarsson** [oceanwp/oceanwp#9]
I still evaluate the theme checking some demo and how the microdata are inserted inside the page, and I've many question to ask because i've found some errors:

1) first, is possible to disable in BO the microdata feature?
2) checkign with google microdata structure testing tool, there is an error: https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fsimple.oceanwp.org%2Fshop%2F
3) checkign a blog post there is an error like other blogpost: https://simple.oceanwp.org/duis-sagitis-ipsum-prasent/

For production i prefer to disable the microdata feature and use an external plugin for JSON-LD version.
Is that possible?

**Comment by oceanwp** [comment]
Hello,

1. It is true that I did not think to put the microdata in a function to allow users to disable them, I will take care of it for the next version :)
2-3. There are no errors, I tested on the testing tool.

**Comment by HartLarsson** [comment]
the problem is for the article DATA.
seems in my localization (italian) the date is not correctly placed in the JSON.

**Comment by HartLarsson** [comment]
I've just chekced again the point#3 and i get errors:

![image](https://user-images.githubusercontent.com/16102074/28322884-90c6a89c-6bd7-11e7-9a66-249f66f234f6.png)

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fsimple.oceanwp.org%2Fduis-sagitis-ipsum-prasent%2F

**Comment by oceanwp** [comment]
Thank you very much for letting me know, I will solve this problem in the next version and I will also add an option in the customizer to allow you to completely disable the microdata :)

**Comment by HartLarsson** [comment]
i find a solution that validate

for example if the data is in italian format day Month year like: 30 giugno 2017
to validate the microdata you can use **<time> </time>** like:

<time class='date-container minor-meta updated'  itemprop="datePublished" datetime="2017-06-30T07:00:06+00:00" >30 giugno 2017</time>

**Comment by HartLarsson** [comment]
Other problem on image:

`<div class="thumbnail"><img width="1100" height="400" src="https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice.jpg" class="attachment-full size-full wp-post-image" alt="Pasta sfoglia al mattarello o a macchina?" itemprop="image" srcset="https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice.jpg 1100w, https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice-300x109.jpg 300w, https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice-768x279.jpg 768w, https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice-1024x372.jpg 1024w, https://www.lapastadibologna.com/wp-content/uploads/2017/07/header-mattarello-vs-sfogliatrice-800x291.jpg 800w" sizes="(max-width: 1100px) 100vw, 1100px" /></div>`

will not validate because it requires only one image. In the example i used a featured image but as yuo know WP add other sizes.
I found and interesting convo here: https://webmasters.stackexchange.com/questions/90233/why-is-my-itemprop-image-markup-incorrect
you can take out the idea and implement the fix

**Comment by HartLarsson** [comment]
Another not valid parameter is the Author:

`<li class="meta-author" itemprop="name"><i class="icon-user"></i><a href="https://www.lapastadibologna.com/author/p-canossa/" title="Articoli scritti da: Paolo Canossa" rel="author" itemprop="author" itemscope="itemscope" itemtype="http://schema.org/Person">Paolo Canossa</a></li>`

for some reason is not valid:

![image](https://user-images.githubusercontent.com/16102074/28625871-cc82f5ec-721d-11e7-8505-d1817ee6534c.png)

**Comment by oceanwp** [comment]
Hi, I added an option in the customizer in the next version, you will be able to completely disable the microdata.

**Comment by HartLarsson** [comment]
perfect! i have only one doubt about using any 5 star rating system that actually with the microdata of oceanWP is integrating well (even if there are some oceanWP microdata problemas as we spoke before).
After removing all microdata 99% of these plugins add extra microdata to the blog post/page.
I'm just curious to see how google will validate the adding :)

Any chance you will fix your microdata output? i would like to use your feature instead to add another extra plugin for json-ld version. ;9

anyway thank you s much i will wait you pull the new version on wordpress theme catalog ;)
