### ISSUE TITLE
Unable to set up breadcrumb in mobile and tablet

### ISSUE THREAD

**Issue by tonytanlh** [oceanwp/oceanwp#90]
Thanks for the awesome design of the theme ! 
Below two points are not really issues....

1) Is there any setting to enable breadcrumbs in mobile? I could not find a setting to enable breadcrumbs in mobile and tablet. 

2) Can the breadcrumbs be added in front of the title? Currently there is no such style option for breadcrumb locating in front of the title.

**Comment by nicolas-owp** [comment]
Hello,  thank you :)

1. You can do it via a css code, hide it on desktop and display it on tablet and mobile.
2.  Have you an example?

**Comment by tonytanlh** [comment]
Thanks, done, everything work perfectly! Just played a bit with the css  :)

**Comment by tonytanlh** [comment]
This case can be closed already

**Comment by nicolas-owp** [comment]
Great :)
