### ISSUE TITLE
Page title background image

### ISSUE THREAD

**Issue by jrc2** [oceanwp/oceanwp#91]
Hi,

I have set background image as the default page title style. When I go to the title section of settings for a particular page, I can only change the background image if I change the style from 'Default' to 'Background Image,' even though my default style is 'Background Image.'

**Comment by nicolas-owp** [comment]
Hello, sorry I not quite understand the issue, if you add the title style as background image in OCeanWP Settings, the Default mean the default value in the customizer so in your case Background Image, so if you want to add a different page title style for one page, you need to choose the style you want.

**Comment by jrc2** [comment]
@nicolas-owp 

Nick, I was trying to make it so when 'Background Image' is the default style, the user can change the background image on each page. This is possible when Background Image is not default and the user changes the style to background image, but it is not possible when background image is the default style. I'm not sure if this is a bug or a feature request.

**Comment by nicolas-owp** [comment]
Hi, yes, it is possible, edit a page or post, click the Title tab in OCeanWP Settings, select the Background Image style and add your image, you will have this image only for this page or post and the image from the customizer for the rest of your site.
It works perfectly, I just tried on my site.

**Comment by jrc2** [comment]
@nicolas-owp The image just cannot be changed if default is left as the style even though default is background image?

**Comment by nicolas-owp** [comment]
If you have selected the background image from the customizer, you will have an image for your page title for all your site. If you want to change the image for one particular page, you just need to select Background Image in OceanWP Settings and select a different image. It would be too complicated to make fields appear in the OCeanWP Settings metabox related to the customizer.

**Comment by jrc2** [comment]
@nicolas-owp Ok, thank you!

**Comment by nicolas-owp** [comment]
You're welcome :)
