### ISSUE TITLE
Bug: Primary color overtakes link hover color

### ISSUE THREAD

**Issue by tannerchung** [oceanwp/oceanwp#94]
I took a screen video of how the Primary Color in the Customizer menu overtakes the Links Color, Color: Hover

http://nimb.ws/BsS1v9

This doesn't seem like normal behavior.

**Comment by nicolas-owp** [comment]
Hello, yes, it is normal, the Primary Color is the blue color of the theme, so when you change it, that change all the blue color by your custom color, then you can change the links color in the same section.
