### ISSUE TITLE
Feature Request: WooCommerce Grid/List Elements Positioning & Save Checkout Data

### ISSUE THREAD

**Issue by voznyuk-design** [oceanwp/oceanwp#96]
1. Add the ability to select Title, Category, Price etc. separately for Grid View and List View.
2. Persistent Checkout Form Data. It will retain the Checkout form fields even if the visitor accidentally reloads the checkout page. An example of Astra Theme.

**Comment by nicolas-owp** [comment]
Hello,
1. It is not possible, the Grid and List view are actually the same views, so if you remove something in the Grid view, it is automatically removed int he List view.

2. Can you show me?

**Comment by nicolas-owp** [comment]
Hello, I close this as you don't answer, but feel free to answer me even if it is closed.
