### ISSUE TITLE
updating cookie notice extension fails

### ISSUE THREAD

**Issue by codeagencybe** [oceanwp/oceanwp#98]
Hello Nicholas,

I can not update the cookie notice extension on none of my websites. I tried 7 website so far, and all of them return an error. 
* It only happens for this extension. Other extensions update just fine. 
* Other plugins (e.g. WooCommerce, Yoast SEO, ... also just update fine. 
It's really something specific with this plugin package that goes wrong. 

![image 2018-06-17 at 1 15 19 pm](https://user-images.githubusercontent.com/7568546/41507430-8e7eea60-7232-11e8-906d-e82c9332d723.png)

http://sharing.codeagency.be/3G1M0i2B2a1j

**Comment by nicolas-owp** [comment]
Hello, thank you for letting me know, I have the same issue on one of my site, I have contacted Easy Digital Downloads which is the plugin I use for the license.

**Comment by nicolas-owp** [comment]
Hello, can you try again and tell me if you still have the issue?

**Comment by codeagencybe** [comment]
On 1 website it works updating so far. So it seems the package is fixed for downloading.

On the other websites, the update is not showing (anymore). It stays at version 1.0.2 and does not give me warning that version 1.0.4 is available. 
I already tried forcing checking, removing license key and re-adding back, etc... but it's not showing me version 1.0.4 anymore.
 
Perhaps it can take some time now due to your changes before it shows up in backend?

**Comment by nicolas-owp** [comment]
Hello, that is very weird, wait a little longer, if you don't see the update notification tomorrow, update the plugin manually.

**Comment by nicolas-owp** [comment]
Hello, ifs this issue solved?

**Comment by codeagencybe** [comment]
Hello Nicolas,

Yes this issue is solved. 
Thanks!

**Comment by nicolas-owp** [comment]
Hello, perfect :)
