### ISSUE TITLE
Form button style location

### ISSUE THREAD

**Issue by nickmadedesign** [oceanwp/oceanwp#99]
Hi,

From what I understand via the inspector, the theme form button styles is set for uppercase styling, font size of 12px, etc.

Is there a setting via the Customizer I'm missing?

I can set it via the custom CSS / child theme CSS, of course, but it'd be great to adjust the typography of the buttons.

Thank you!

**Comment by nicolas-owp** [comment]
Hello, no, sorry, you will need to do it via css, tell me if you want me to give you the css code, it is very simple.
